### ISSUE TITLE
document XYZ vs ZYX

### ISSUE THREAD

**Issue by fcollman** [seung-lab/cloud-volume#107]
You have a note in the example to be wary of XYZ vs ZYX, but you aren't actually explicit about whether the library expects numpy arrays to be ZYX or XYZ ordered.

**Comment by william-silversmith** [comment]
Good call. It's a little odd but the way CV expects you to write arrays in Python notation is: `vol[ X:Xf. Y:Yf, Z:Zf, Chan:Chanf ]` however, the underlying array can be in either C or Fortran order, it will convert automatically. The serialized format of Precomputed is in Fortran order.

**Comment by william-silversmith** [comment]
I'm planning on revamping the documentation in the very near future, I think it could read a lot better.

**Comment by fcollman** [comment]
to add some extra confusion neuroglancer-python has ZYX ordering in its interface.

**Comment by william-silversmith** [comment]
Is neuroglancer-python the python code in the main neuroglancer repo?

**Comment by william-silversmith** [comment]
This is in the documentation under setting up info files. If there's another place you'd like to see it, please reopen or edit the readme!
