### ISSUE TITLE
Hash Prefix for Filenames

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/cloud-volume#116]
Sometimes if you launch too many workers (well over a thousand) that target a narrow region of space, it can slam a single machine in S3 or Google Storage. This can be mitigated by prefixing a hash in front of the key which ensures more even distribution in the cloud irrespective of spatial region.

Should this be a default feature? It does make gsutil and the web UI harder to use. Should it be a flag? 

Which hash to use? Security isn't a concern at all since the idea is to make the filenames easily computable. md5 is about 2x faster than sha functions according to:

https://stackoverflow.com/questions/2722943/is-calculating-an-md5-hash-less-cpu-intensive-than-sha-family-functions

**Comment by jingpengw** [comment]
a flag would be nice. 
It would be better to make neuroglancer works with the new name style too.

**Comment by william-silversmith** [comment]
Looks like there's a fast-enough md5 JS implementation here: http://www.myersdaily.org/joseph/javascript/md5.js

**Comment by william-silversmith** [comment]
https://aws.amazon.com/about-aws/whats-new/2018/07/amazon-s3-announces-increased-request-rate-performance/?sc_channel=em&sc_campaign=GLOBAL_LA_NY-Summit-Recap_20180717&sc_medium=em_98735&sc_content=PA_la_la&sc_geo=mult&sc_country=global&sc_outcome=pa&trk=em_98735&mkt_tok=eyJpIjoiT1RRd1kySmhZalEyWWpFMyIsInQiOiJsV1wvbXJwTEZyRDRFWlhnQXJcL3hDTUVkOGpYenhnY3duQWRPRjBySytJNmZKYnlUUFFRa09zeHlvNnUxbWZSVVVcL1NxWW12QzExSHBkWk45NTkxbjQ1Zzkra2w5VkFMN3U5aTQzbUhHZHhOcUVIbGhTTk1XckRFaGtwZ3B6dUtCNCJ9

"This S3 request rate performance increase removes any previous guidance to randomize object prefixes to achieve faster performance. That means you can now use logical or sequential naming patterns in S3 object naming without any performance implications. This improvement is now available in all AWS Regions. For more information, visit the Amazon S3 Developer Guide."

**Comment by william-silversmith** [comment]
I think the cloud services are now advanced enough to not need this. Let's reopen if we find it's different in reality.
