### ISSUE TITLE
Annotations at higher mip levels

### ISSUE THREAD

**Issue by zashwood** [seung-lab/cloud-volume#136]
I have a list of coordinates and I want to convert these to coordinates at higher mip levels using the same method as cv.bbox_to_mip. The goal is to be able to overlay points on top of cropped segmentations at these higher mip levels.  Would be nice to have a function that does this, without me having to come up with a hack.

**Comment by william-silversmith** [comment]
Also, Tommy showed me a proof that nested divisions of ceilings are equivalent to a single division with a single ceiling. 

https://math.stackexchange.com/questions/233670/nested-division-in-the-ceiling-function
