### ISSUE TITLE
A More Generic Storage Interface

### ISSUE THREAD

**Issue by wongwill86** [seung-lab/cloud-volume#153]
CloudVolume is great because it is backend agnostic and centralizes our credential system.
I want to be able to use Storage for arbitrary object storage access (i.e. network model and checkpoints) access. I don't want to rewrite this logic myself and also ensuring the credentials are the same format. 

Right now this may fail because of the necessity of  `Cloud path must conform to PROTOCOL://BUCKET/zero/or/more/dirs/DATASET/LAYER`. From what I can see Storage's main purpose is to provide an interface to each provider. Why does it need to validate whether or not the `layer_path` conforms to some format? Can we move this validation one level above to the the objects that _use_ Storage?

Also, why does storage parse out the intermediate, dataset, layer? I didn't find where any of these field are being used. In fact every request we make, in `get_path_to_file` we call `filter` and `os.join` to always reconstruct it. Did I miss something that makes it necessary to recompute this every time?

**Comment by william-silversmith** [comment]
Related to #16

**Comment by william-silversmith** [comment]
You're correct in your criticisms of the architecture. Initially, Storage was considered more the Precomputed reading/writer rather than a generic storage mechanism, but that's what it evolved into. These are good updates to make.
