### ISSUE TITLE
Increasing memory consumption by random access

### ISSUE THREAD

**Issue by unidesigner** [seung-lab/cloud-volume#184]
I'm running into the issue that when I open a CloudVolume stack, my memory consumption always increases until the processed is killed by the OS while retrieving random locations in the stack, even with parallel=1. My code is this:
```
import cloudvolume 
import numpy as np
vol = cloudvolume.CloudVolume(local_fname, fill_missing = True, 
   progress = False, cache = True, parallel=1)
max_x = vol.shape[0]
max_y = vol.shape[1]
max_z = vol.shape[2]
for i in range(1000):
   x = np.random.randint(0, max_x)
   y = np.random.randint(0, max_y)
   z = np.random.randint(0, max_z)
   print(vol[y,x,z,0][0][0][0][0])
```
Can you point me into the right direction to limit the threads/processes, flush the cache or limit memory consumptions? Thanks.

**Comment by william-silversmith** [comment]
Hi Stephen!

I tried running this script against black 16-bit images, 8-bit gray images, gzipped segmentation, and compressed segmentation on my Ubuntu 16.04 LTS machine on python 3.6 (Anaconda). I saw memory climb as high as 200 MB and flatline over the course of a minute or so on the worst case. Would you be able to  furnish additional details about your setup? Do you know what version of CloudVolume you have installed? `import cloudvolume; print(cloudvolume.__version__)`

**Comment by unidesigner** [comment]
Hi Will!
It's a Ubuntu 16.04 LTS machine with Python 2.7.12, Cloud Volume Version 0.27.1. I updated now to the latest version and the problem seems to be gone. Thanks for the hint.
