### ISSUE TITLE
separate info as a class?

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/cloud-volume#187]
currently, the info code was mixed within CloudVolume, is it better to separate it out as a class in a separate file? 
I can work on it if you feel appropriate. @william-silversmith

**Comment by william-silversmith** [comment]
I've been thinking about this for a while. Breaking it out into a class will allow it to be more polymorphic if we need to support additional types of protocols (Forrest and Sven are investigating that).

**Comment by jingpengw** [comment]
@william-silversmith is there any update on this? 
I can work on it if appropriate.

**Comment by william-silversmith** [comment]
Resolved in #230
