### ISSUE TITLE
local file protocol with root directory

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/cloud-volume#189]
if I would like to use a layer path from root directory, such as `/tmp/foo`, how can I do it?

currently, `file://tmp/foo` will means local `./tmp/foo`
if I use `file:///tmp/foo`, the regular expression check will fail and report an error:

```
cloudvolume.exceptions.UnsupportedProtocolError:
    Cloud path must conform to PROTOCOL://BUCKET/zero/or/more/dirs/DATASET/LAYER
    Example: gs://test_bucket/mouse_dataset/em

    Supported protocols: gs, s3, file, matrix, boss, http, https

    Received: file:///tmp/foo
```

**Comment by william-silversmith** [comment]
That's... odd. There are tests that ensure it works with `file:///tmp`. See https://github.com/seung-lab/cloud-volume/blob/master/test/test_cloudvolume.py#L41

Can you provide more context and a code sample?

**Comment by jingpengw** [comment]
It turns out that I have to use one more directory layer, `file:///tmp/foo/bar` works.
