### ISSUE TITLE
Where does the 2 in map2 come from?

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/cloud-volume#190]
I don't understand this function name, it sounds like it will only change the first two elements, but it actually changed all of them.

https://github.com/seung-lab/cloud-volume/blob/54ca4c67b5c96ade53adc1dda2d66da697e26b17/cloudvolume/lib.py#L240

**Comment by william-silversmith** [comment]
It's mapping using two arguments instead of just one. This could probably be accomplished with:

```
[ fn(x,y) for x,y in zip(a,b) ]
```

I wrote that function when I was re-familiarizing myself with python.

**Comment by jingpengw** [comment]
tks, I see.
