### ISSUE TITLE
Install on virgin image of gcloud instance

### ISSUE THREAD

**Issue by macrintr** [seung-lab/cloud-volume#2]
I ran into issues with `pip install cloud-volume` on a clean image of a gcloud instance.

I got around it by first installing anaconda2:
```
wget https://repo.continuum.io/archive/Anaconda2-4.4.0-Linux-x86_64.sh
bash Anaconda2-4.4.0-Linux-x86_64.sh
```

That worked within python. I think there might be a package missing -- something related to blosc.

**Comment by william-silversmith** [comment]
Can you show me what the error was?

**Comment by william-silversmith** [comment]
I think you have to do this if you're using anaconda: `../anaconda2/bin/pip install cloud-volume`

**Comment by william-silversmith** [comment]
I haven't heard anything about this issue in a long time. Is this still a problem?

**Comment by william-silversmith** [comment]
I'm going to close this issue as no one has reported this problem in a long time.
