### ISSUE TITLE
Use cloud-volume with Google Cloud Public Data

### ISSUE THREAD

**Issue by unidesigner** [seung-lab/cloud-volume#220]
Hi!

I wanted to load a dataset with cloud-volume that is publicly accessible via github.com/google/neuroglancer like so:

`cloudvolume.CloudVolume("gs://neuroglancer-public-data/kasthuri2011/image")`

But this returns permission errors for the Google Cloud Project. I can `gsutil ls` the repo in a shell and retrieve data. Is there a way to make array-based access via cloud-volume work on this dataset?

Thanks, Stephan

**Comment by william-silversmith** [comment]
Hi Stephan!

Yes, it is possible to use CloudVolume with kasthuri2011. :) The problem is that the `gs://` interface uses the authentication interface underneath which has read and write access. For public read-only data, it's possible to use the `https://` interface like so:  

```python
from cloudvolume import CloudVolume

vol = CloudVolume("https://storage.googleapis.com/neuroglancer-public-data/kasthuri2011/image")
```

Google Cloud is having some problems at the moment, so if it doesn't work for you wait a few hours and try again.

Hope that helps!
Will

**Comment by william-silversmith** [comment]
I was playing around with this and found a bug in the http interface code. I released version 0.49.2 which contains a fix. :)

**Comment by fcollman** [comment]
FWIW this is why we have this option in this branch https://github.com/seung-lab/cloud-volume/blob/1f0881055d0fef6bd336d8825a5c0b1196efc5de/cloudvolume/cloudvolume.py#L140

To automatically remap the gs path to https paths. As long as your data is public readable this is strictly better...

**Comment by unidesigner** [comment]
This works for me now, thanks!

**Comment by william-silversmith** [comment]
That's an interesting idea Forrest. Though, if it's not enabled by default, people who don't understand why it doesn't work may still be mystified. 

Why do you say it's strictly better? Because the https interface has caching enabled?

**Comment by fcollman** [comment]
Because the https interface is faster than the gs interface in practice.

**Comment by fcollman** [comment]
And agreed I don’t love the solution either, but it’s better than having to remember/know the magic remapping yourself... though of course if you do want to write... perhaps it should fallback to this remap strategy if authentication fails
