### ISSUE TITLE
Support of new Sharded Neuroglancer Format for Image Data

### ISSUE THREAD

**Issue by unidesigner** [seung-lab/cloud-volume#221]
I was trying to pull a cut-out from the new Google segmentation data of FAFB using the following code

```
from cloudvolume import CloudVolume
vol = CloudVolume("https://storage.googleapis.com/fafb-ffn1-20190521/segmentation")
```

but I get a voxel_offset error. I think this is related to the new [Sharded Format](https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/README.md#sharded-format) not yet being supported by cloud-volume.
Is there a plan to support this new format in the library?

@jbms: Is the new format going to be supported by the new TensorStore implementation?

**Comment by william-silversmith** [comment]
Hi Stephen, 

I've been busy with [Kimimaro](https://github.com/seung-lab/kimimaro) at the moment, so I haven't yet fully digested the new Sharding spec. It makes a lot of sense to me to shard skeletons and meshes to avoid the high file creation fees on Google and Amazon ($4 per million, but we make billions). I don't immediately understand the point of sharding segmentation though since in a way, it is already sharded.  

I've started planning on adding sharding for meshes and skeletons at least as those have been major cost centers for us. I was starting to invent my own sharding design when @nkemnitz told me there already was one on Thursday. (Thanks Jeremy!)

It's gonna bit at least a few weeks if not longer depending on my availability before sharding support is released though.

**Comment by william-silversmith** [comment]
Skimming through the spec, I guess if you want to reduce the number of image chunks as well, that makes sense. Those have been the least of our problems fwiw though. I will note that not all servers that we use support HTTP `Range` queries, but I suppose so long as we don't use sharding it's fine.

**Comment by jbms** [comment]
The new sharded format will be supported by Tensorstore but support in cloud-volume would certainly be useful as well.  The sharded format does have downsides as listed in the spec, but when using GCS, even aside from write costs it is also possible to write much faster and makes moving/copying the data much easier.

**Comment by unidesigner** [comment]
@jbms Do you have a rough estimate on when Tensorstore will be released?

**Comment by jbms** [comment]
Also, which server do you use that doesn't support HTTP Range queries?

**Comment by william-silversmith** [comment]
We have some S3 emulation service set up, but while I was told to regard
operations as entire file, it also promises full emulation of the S3 api so
I should try it before I say conclusively that it doesn't. I figure Range
is a subtlety that is usually not asked about by most people.

**Comment by jbms** [comment]
@unidesigner Likely we will be able to release TensorStore within the next couple months.

**Comment by unidesigner** [comment]
@jbms Thanks for informing me about this. It might be better for me to wait until TensorStore is released before trying to implement my own (likely suboptimal) sharded format parser. If I get to it and have questions, I'll use the neuroglancer issue page.

**Comment by william-silversmith** [comment]
I'm hoping to have this implemented in cloud-volume eventually so I'd rather keep this thread open.

**Comment by william-silversmith** [comment]
As of 0.53.0, there's an operational version of the plugin system. I may start working on the sharded format soon. https://github.com/seung-lab/cloud-volume/wiki/Galaxy-Brain-Topic:-Subsystem-Architecture

**Comment by unidesigner** [comment]
Great news about the plugin system and that you may start working on the sharded format. I'd be happy to test and provide feedback. If I may try to bias your prioritization on features ... I'd love to have cut-out functionality (i.e. Numpy-array slicing style).

**Comment by fcollman** [comment]
@unidesigner do you mean on meshes?

**Comment by william-silversmith** [comment]
I suspect Stephan is talking about the FFN FAFB segmentation which is inaccessible without image cutout features.

**Comment by william-silversmith** [comment]
I'm trying to decide what to implement first, but I'm certainly going to implement reading before I do writing. ^_^

**Comment by unidesigner** [comment]
Yeah, I meant the  FFN FAFB segmentation. On meshes would also be cool ;)

**Comment by fcollman** [comment]
oh i didn't realize sharded extended beyond meshes... i guess i need to read about it

**Comment by william-silversmith** [comment]
It's images, meshes, and skeletons.

**Comment by william-silversmith** [comment]
You can follow along in #239 I'm working on the Skeletons first because the spec is simplest for them.

**Comment by unidesigner** [comment]
I'll follow along.

**Comment by william-silversmith** [comment]
I have something working. :) Hopefully I can polish it and have it out tomorrow.

**Comment by unidesigner** [comment]
Great! That was quick :)

**Comment by william-silversmith** [comment]
CloudVolume 0.60.0 can read the FAFB dataset.

**Comment by unidesigner** [comment]
I tested 0.60.0 and it works very well. This will be incredibly useful to people working with the FFN autoseg skeletons from Google in CATMAID - will make sure that they know that you implemented this. Thanks again for implementing this.

One thing, unrelated to the implementation, but perhaps @jbms reading here might now the answer: Scale level 0 of `https://storage.googleapis.com/fafb-ffn1-20190805/segmentation` is 8x8x40nm and has dimension 124416,67072,7063. However, the generally used CATMAID configuration for FAFB (e.g. in publicly hosted Virtual Fly Brain instance) specifies the 4x4x40nm stack resolution with dimension (253952, 155648, 7063), which would be 126976,77824,7063. @jbms do you know where this mismatch in x,y dimension come from?

**Comment by perlman** [comment]
A quick answer to @unidesigner (in case someone stumbles across this): CATMAID was configured to the nearest 8192x8192 tile size (@4nm), as that was the unit size we used for various imaging rendering and processing steps. It looks like the Google version was cropped down to the minimal bounding box.
