### ISSUE TITLE
fpzip + posix_ipc errors compiling on windows

### ISSUE THREAD

**Issue by Cervidellus** [seung-lab/cloud-volume#225]
Both fpzip and posix_ipc fail to build when installing cloud-volume on windows, greatly complicating installation. Installing from binary might be an option, but our complicated installation process prevents bringing new users up to speed quickly (in a workshop, for example).

**Comment by william-silversmith** [comment]
Hi Dan,

Currently Windows is not supported... The main reason for this is that I do not have access to a Windows machine (I use Linux and Mac OS for everything). I can ask about getting a Windows VM installed on my workstation. 

It might be possible to get this stuff working by making the posix_ipc installation platform dependent. posix_ipc is used for shared memory, which in turn is used for parallel. It might be possible for me to get Windows working sans parallel processing.  

Can you post the fpzip compilation error? It might just be missing a header or two.

**Comment by william-silversmith** [comment]
Also, thanks for helping teach people how to use CloudVolume! I ran into a similar issue at a conference workshop and it was disappointing to have to exclude one person from the exercise. :(

**Comment by fcollman** [comment]
i just want to plus one this, in august we are going to have a workshop to show students how to interact with some data and i'm sure some of them will come with windows laptops.  One option to avoid you needing a laptop to test is to use appveyor to setup windows based tests.

**Comment by Cervidellus** [comment]
I am not so great at diagnosing python compilation errors, but if there is anything I can try on windows I am happy to do so.. for my own needs I have a linux box sitting here, but for getting other people onboard simplifying an install process would be helpful. Also, according to the website for posix_ipc it should be able to work on windows? Maybe this has only recently been supported. 

Here's the output for compilation errors for both fpzip and posix_ipc:
`Building wheels for collected packages: cloud-volume, fpzip, posix-ipc, blosc
  Building wheel for cloud-volume (setup.py) ... done
  Stored in directory: c:\users\acrob\appdata\local\temp\pip-ephem-wheel-cache-1qkrxc\wheels\5b\a3\b6\b60e389be36e3ca063a38743d82b6dd5dc3363f2a5e32a7bdd
  Building wheel for fpzip (setup.py) ... error
  ERROR: Complete output from command 'C:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'c:\\users\\acrob\\appdata\\local\\temp\\pip-install-w75b7b\\fpzip\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'c:\users\acrob\appdata\local\temp\pip-wheel-viwjhf' --python-tag cp27:
  ERROR: running bdist_wheel
  running build
  running build_ext
  building 'fpzip' extension
  error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
  ----------------------------------------
  ERROR: Failed building wheel for fpzip
  Running setup.py clean for fpzip
  Building wheel for posix-ipc (setup.py) ... error
  ERROR: Complete output from command 'C:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'c:\\users\\acrob\\appdata\\local\\temp\\pip-install-w75b7b\\posix-ipc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'c:\users\acrob\appdata\local\temp\pip-wheel-uqgujz' --python-tag cp27:
  ERROR: ******************************************************************************
  * Setup can't determine if it needs to link to the realtime libraries on your
  * system, so it will default to 'no' which may not be correct.
  *
  * Please report this message and your operating system info to the package
  * maintainer listed in the README file.
  ******************************************************************************
  ******************************************************************************
  * Setup can't determine the value of PAGE_SIZE on your system, so it will
  * default to 4096 which may not be correct.
  *
  * Please report this message and your operating system info to the package
  * maintainer listed in the README file.
  ******************************************************************************
  ******************************************************************************
  * Setup can't determine the value of PRIORITY_MAX on your system, so it will
  * default to 32 which may not be correct.
  *
  * Please report this message and your operating system info to the package
  * maintainer listed in the README file.
  ******************************************************************************
  running bdist_wheel
  running build
  running build_ext
  building 'posix_ipc' extension
  error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
  ----------------------------------------
  ERROR: Failed building wheel for posix-ipc`

**Comment by william-silversmith** [comment]
@Cervidellus it looks like you are missing the appropriate Windows based compiler. Try installing https://www.microsoft.com/en-us/download/details.aspx?id=44266 and see if CloudVolume will work.

**Comment by william-silversmith** [comment]
Also, Python 2.7 is nearing its end of life. I would recommend upgrading to Python 3.6 or 3.7.

**Comment by william-silversmith** [comment]
I tried setting up appveyor and got this: 
```
posix_ipc_module.c(37) : fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
******************************************************************************
* Setup can't determine if it needs to link to the realtime libraries on your
```

**Comment by Cervidellus** [comment]
Python 3.7 is installed. Setup.py asks for 2.6 or 2.7, maybe this is where the error comes from? I did install the compilation tools for python, it does change the errors I get.. The output is a huge mess, here is just a bit of it.: 

>   ERROR: Complete output from command 'C:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'c:\\users\\acrob\\appdata\\local\\temp\\pip-install-fyx25c\\fpzip\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'c:\users\acrob\appdata\local\temp\pip-wheel-hvvl8i' --python-tag cp27:
  ERROR: running bdist_wheel
  running build
  running build_ext
  building 'fpzip' extension
  creating build
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\fpzip-1.2.0
  creating build\temp.win-amd64-2.7\Release\fpzip-1.2.0\src
  C:\Users\acrob\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ifpzip-1.2.0\inc -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\lib\site-packages\numpy\core\include -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\include -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\PC /Tpfpzip-1.2.0\src\error.cpp /Fobuild\temp.win-amd64-2.7\Release\fpzip-1.2.0\src\error.obj -std=c++11 -DFPZIP_FP=FPZIP_FP_FAST -DFPZIP_BLOCK_SIZE=0x1000 -DWITH_UNION
  cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
  error.cpp
  C:\Users\acrob\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ifpzip-1.2.0\inc -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\lib\site-packages\numpy\core\include -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\include -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\PC /Tpfpzip-1.2.0\src\rcdecoder.cpp /Fobuild\temp.win-amd64-2.7\Release\fpzip-1.2.0\src\rcdecoder.obj -std=c++11 -DFPZIP_FP=FPZIP_FP_FAST -DFPZIP_BLOCK_SIZE=0x1000 -DWITH_UNION
  cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
  rcdecoder.cpp
  fpzip-1.2.0\inc\rcdecoder.h(8) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
  fpzip-1.2.0\src\rcdecoder.cpp(66) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
  C:\Users\acrob\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ifpzip-1.2.0\inc -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\lib\site-packages\numpy\core\include -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\include -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\PC /Tpfpzip-1.2.0\src\rcencoder.cpp /Fobuild\temp.win-amd64-2.7\Release\fpzip-1.2.0\src\rcencoder.obj -std=c++11 -DFPZIP_FP=FPZIP_FP_FAST -DFPZIP_BLOCK_SIZE=0x1000 -DWITH_UNION
  cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
  rcencoder.cpp
  fpzip-1.2.0\inc\rcencoder.h(8) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
  fpzip-1.2.0\src\rcencoder.cpp(59) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
  C:\Users\acrob\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ifpzip-1.2.0\inc -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\lib\site-packages\numpy\core\include -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\include -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\PC /Tpfpzip-1.2.0\src\rcqsmodel.cpp /Fobuild\temp.win-amd64-2.7\Release\fpzip-1.2.0\src\rcqsmodel.obj -std=c++11 -DFPZIP_FP=FPZIP_FP_FAST -DFPZIP_BLOCK_SIZE=0x1000 -DWITH_UNION
  cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
  rcqsmodel.cpp
  C:\Users\acrob\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ifpzip-1.2.0\inc -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\lib\site-packages\numpy\core\include -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\include -IC:\Users\acrob\AppData\Local\conda\conda\envs\emtoolschool\PC /Tpfpzip-1.2.0\src\write.cpp /Fobuild\temp.win-amd64-2.7\Release\fpzip-1.2.0\src\write.obj -std=c++11 -DFPZIP_FP=FPZIP_FP_FAST -DFPZIP_BLOCK_SIZE=0x1000 -DWITH_UNION
  cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
  write.cpp
  c:\users\acrob\appdata\local\temp\pip-install-fyx25c\fpzip\fpzip-1.2.0\inc\rcencoder.h(8) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
  c:\users\acrob\appdata\local\temp\pip-install-fyx25c\fpzip\fpzip-1.2.0\inc\pcencoder.inl(25) : warning C4244: 'argument' : conversion from 'U' to 'unsigned int', possible loss of data
          c:\users\acrob\appdata\local\temp\pip-install-fyx25c\fpzip\fpzip-1.2.0\inc\pcencoder.inl(19) : while compiling class template member function 'double PCencoder<T,M>::encode(T,T,unsigned int)'
          with
          [
              T=double,
              M=MAP
          ]
          fpzip-1.2.0\src\write.cpp(41) : see reference to class template instantiation 'PCencoder<T,M>' being compiled
          with
          [
              T=double,
              M=MAP
          ]
          fpzip-1.2.0\src\write.cpp(167) : see reference to function template instantiation 'void compress3d<T,4>(RCencoder *,const T *,unsigned int,unsigned int,unsigned int)' being compiled
          with
          [
              T=double
          ]
          fpzip-1.2.0\src\write.cpp(295) : see reference to function template instantiation 'bool compress4d<double>(FPZoutput *,const T *)' being compiled
          with
          [
              T=double
          ]
  c:\users\acrob\appdata\local\temp\pip-install-fyx25c\fpzip\fpzip-1.2.0\inc\pcencoder.inl(25) : warning C4244: 'argument' : conversion from 'U' to 'unsigned int', possible loss of data
          c:\users\acrob\appdata\local\temp\pip-install-fyx25c\fpzip\fpzip-1.2.0\inc\pcencoder.inl(19) : while compiling class template member function 'double PCencoder<T,M>::encode(T,T,unsigned int)'
          with
          [
              T=double,
              M=MAP
          ]
          fpzip-1.2.0\src\write.cpp(41) : see reference to class template instantiation 'PCencoder<T,M>' being compiled
          with

>

**Comment by william-silversmith** [comment]
"cl : Command line warning D9002 : ignoring unknown option '-std=c++11'", that's... not great. I forget if we actually are using any C++11 features in fpzip though. We might not be.  

It looks like your output is truncated. Is there more to it?

**Comment by william-silversmith** [comment]
Actually, I might be able to just use shared memory emulation on windows too for parallel....

**Comment by william-silversmith** [comment]
If you have trouble, I think you have two alternatives: Cygwin and the Windows Linux Subsystem https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by Cervidellus** [comment]
The -std=c+11 error I am pretty sure is related to it being a gcc option that gets ignored because it defaults to an msvc compiler.. I think it could be dealt with by having an if-else statement in setup.py for that option. I have a hunch that this is just an annoying flag rather than something causing a problem.  The output was highly truncated... it was long enough that I thought it would be awkward to post here.. should I send the whole thing via email? Many of the errors ( warning C4146: unary minus operator applied to unsigned type, result still unsigned) seem to be related to differences in how types are defined on windows or maybe a 32bit vs 64 bit thing(normal int is smaller? ). I don't know. But, for example, in rcencoder.h there is a "-1u" applied to an unsigned int in the constructor in line 8, which might be misinterpreted in MSVC but not GCC as "-1*u". It might be replaced by the UINT_MAX macro?

**Comment by Cervidellus** [comment]
Ok.. some small progress, I guess the way I installed menpo actually downgraded my python to 2.7, so I changed that to force it to keep 3.6.. after doing that I get a different set of errors that might be consistent with some namespace clashing?  In pcmap.h, not everything is defined within an ifndef statement. Could be a clue?


c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(17): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(24): note: see reference to class template instantiation 'PCmap<T,width,void>' being compiled
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(17): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(21): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(22): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(22): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(23): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(23): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(29): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(44): note: see reference to class template instantiation 'PCmap<float,width,void>' being compiled
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(29): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(32): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(32): note: see reference to class template instantiation 'PCmap<float,width,void>::UNION' being compiled
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(34): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(34): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(39): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(40): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(40): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(41): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(42): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(42): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(43): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(43): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(49): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(64): note: see reference to class template instantiation 'PCmap<double,width,void>' being compiled
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(49): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(52): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(52): note: see reference to class template instantiation 'PCmap<double,width,void>::UNION' being compiled
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(54): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(54): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(59): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(60): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(60): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(61): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(62): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(62): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(63): error C2059: syntax error: 'constant'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(63): error C2238: unexpected token(s) preceding ';'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(4): error C2244: 'PCmap<float,width,void>::fcast': unable to match function definition to an existing declaration
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(3): note: see declaration of 'PCmap<float,width,void>::fcast'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(4): note: definition
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(4): note: 'unsigned int PCmap<float,width,void>::fcast(float) const'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(4): note: existing declarations
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(4): note: 'PCmap<float,width,void>::RANGE PCmap<float,width,void>::fcast(void) const'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(20): error C2039: 'icast': is not a member of 'PCmap<float,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(28): note: see declaration of 'PCmap<float,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(20): error C2447: '{': missing function header (old-style formal list?)
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(36): error C2244: 'PCmap<float,width,void>::forward': unable to match function definition to an existing declaration
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(35): note: see declaration of 'PCmap<float,width,void>::forward'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(36): note: definition
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(36): note: 'unsigned int PCmap<float,width,void>::forward(float) const'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(36): note: existing declarations
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(36): note: 'PCmap<float,width,void>::RANGE PCmap<float,width,void>::forward(void) const'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(47): error C2039: 'inverse': is not a member of 'PCmap<float,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(28): note: see declaration of 'PCmap<float,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(47): error C2447: '{': missing function header (old-style formal list?)
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(57): error C2039: 'identity': is not a member of 'PCmap<float,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(28): note: see declaration of 'PCmap<float,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(57): error C2447: '{': missing function header (old-style formal list?)
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(67): error C2244: 'PCmap<double,width,void>::fcast': unable to match function definition to an existing declaration
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(66): note: see declaration of 'PCmap<double,width,void>::fcast'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(67): note: definition
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(67): note: 'unsigned __int64 PCmap<double,width,void>::fcast(double) const'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(67): note: existing declarations
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(67): note: 'PCmap<double,width,void>::RANGE PCmap<double,width,void>::fcast(void) const'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(83): error C2039: 'icast': is not a member of 'PCmap<double,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(48): note: see declaration of 'PCmap<double,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(83): error C2447: '{': missing function header (old-style formal list?)
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(99): error C2244: 'PCmap<double,width,void>::forward': unable to match function definition to an existing declaration
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(98): note: see declaration of 'PCmap<double,width,void>::forward'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(99): note: definition
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(99): note: 'unsigned __int64 PCmap<double,width,void>::forward(double) const'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(99): note: existing declarations
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(99): note: 'PCmap<double,width,void>::RANGE PCmap<double,width,void>::forward(void) const'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(110): error C2039: 'inverse': is not a member of 'PCmap<double,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(48): note: see declaration of 'PCmap<double,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(110): error C2447: '{': missing function header (old-style formal list?)
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(120): error C2039: 'identity': is not a member of 'PCmap<double,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.h(48): note: see declaration of 'PCmap<double,width,void>'
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\pcmap.inl(120): error C2447: '{': missing function header (old-style formal list?)
  c:\users\acrob\appdata\local\temp\pip-install-494h7liq\fpzip\fpzip-1.2.0\inc\rcencoder.h(8): warning C4146: unary minus operator applied to unsigned type, result still unsigned
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by william-silversmith** [comment]
This is pretty weird. I'm still working on getting access to Windows. This
may be a dumb question, but are you sure it's a C++ and not a C compiler
that you're using? Can I see the command you're using to compile? Maybe the
command needs to be specified differently. fpzip has some constants that
are defined at compile time "'-DFPZIP_FP=FPZIP_FP_FAST',
'-DFPZIP_BLOCK_SIZE=0x1000', '-DWITH_UNION',", maybe they are causing
problems if your compiler doesn't handle -D?

>

**Comment by william-silversmith** [comment]
I should have a VM with Windows 10 tomorrow or Monday. Not 100% sure when I'll get a chance to work on these issues, but that's a necessary condition to fufill.

**Comment by Cervidellus** [comment]
I think there is a name clashing for the RANGE and DOMAIN keywords used in pcmap.h. If I can get permission to push some changes to fpzip I have fixed that in a way that seems to allow everything to compile on windows with MSVC. I may also try and get rid of some of the annoying warnings just for fun. This is just for FPZIP, I haven't done anything to deal with the posix_ipc problems.

**Comment by william-silversmith** [comment]
If you fork and submit a pull request to fpzip, that would be ideal. I just got a Windows 10 VM installed today so when I have a chance I can actually attack this problem.

**Comment by william-silversmith** [comment]
It might take me a bit even when I find the time. I'm a linux/command line guy -- it'll take some time to understand how to use Visual Studio.

**Comment by william-silversmith** [comment]
Ok! I upgraded fpzip with your PR

**Comment by william-silversmith** [comment]
@Cervidellus Would you mind checking out the above referenced PR and see if it works on Windows for you? I think with fpzip and this out of the way there's a chance it'll work.

However, I do want to be clear that I'm not currently able to offer extended Windows support. I'm looking to get something basically working, but if there are a lot of Windows specific use cases, I'll accept PRs but I can't spend a lot of time working on it.

**Comment by william-silversmith** [comment]
I did some more work on that PR using my VM. Many features should be working now. The biggest pain was getting windows type file paths to play nice with everything else.

**Comment by william-silversmith** [comment]
Also, I released a Windows compiled version of fpzip for python3.6 and 3.7.

**Comment by william-silversmith** [comment]
These issues should be resolved. Please reopen if you continue having issues.
