### ISSUE TITLE
skeletonservice: handle exceptions in skel.to_swc()

### ISSUE THREAD

**Issue by zhihaozheng** [seung-lab/cloud-volume#232]
[This](https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/skeletonservice.py#L678) would cause a bug for some skeletons for which there are vertices that are not in the edges.

**Comment by william-silversmith** [comment]
@zhihaozheng Can you point this issue out again? The file you pointed to no longer exists.

**Comment by zhihaozheng** [comment]
@william-silversmith around here[https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/datasource/precomputed/skeleton.py#L679](url), probably.

**Comment by william-silversmith** [comment]
Fixed in 2ebfba3b58a501421e205901d171df6787ccd07c
