### ISSUE TITLE
graphene __get___ method broken

### ISSUE THREAD

**Issue by fcollman** [seung-lab/cloud-volume#265]
the current code passes the mask_base parameter to download and fails

**Comment by fcollman** [comment]
https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/frontends/graphene.py#L141

https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/frontends/graphene.py#L86

**Comment by william-silversmith** [comment]
Resolved by #266
