### ISSUE TITLE
Uploaded chunks are compressed, but the content-encoding is not set

### ISSUE THREAD

**Issue by macrintr** [seung-lab/cloud-volume#27]
I ingested some chunks (uint8 layers that were representing mask objects), and it seems that they were compressed by the content-encoding in the metadata wasn't set.

Here's an example script you can run to test:
```
from cloudvolume import *

vol = CloudVolume('gs://neuroglancer/pinky40_alignment/prealigned_test_masks/')
upload = (255*(np.random.rand(512, 512, 1) > 0.8)).astype(np.uint8)
vol[60055:60055+512, 6094:6094+512, 783:783+1] = upload
```

**Comment by macrintr** [comment]
I used a clean gcloud instance to rerun this ingest job, and I had no issues this time around. Also reinstalled cloud-volume on my workstation with a new virtualenv and had no issue. Likely that I had something stale on my workstation.

**Comment by william-silversmith** [comment]
Most likely this was due to a google-cloud version < 0.26.
