### ISSUE TITLE
Fragment path join separator wrong on Windows

### ISSUE THREAD

**Issue by ntabris** [seung-lab/cloud-volume#273]
The fragment file paths should use "/", as in

`fly_v31_meshes_v2_062619/175949365414725006:0:28928-29184_6400-6656_2048-2560`

But the code uses `os.path.join`, which will use "\\" on Windows. See:

https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/datasource/precomputed/mesh.py#L58

**Comment by william-silversmith** [comment]
Hi Nat,

The latest version 0.62.1 should have this fix in it. Let me know if you need more assistance! 

Will
