### ISSUE TITLE
Why is resolution int when Neuroglancer supports floats?

### ISSUE THREAD

**Issue by falkben** [seung-lab/cloud-volume#280]
Just wondering if there was a reason resolution gets coerced into an `int` here? 

https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/datasource/precomputed/metadata.py#L112

We have datasets with non integer resolution values and Neuroglancer precomputed supports floats for the scale keys so just curious if there was a reason for this before I submitted PR.  I suppose actual int keys would become `x.0` which is not as clean if it was a straight replacement to `float`

**Comment by william-silversmith** [comment]
At the time this was written (2017), we weren't sure if neuroglancer supported floating point resolution. It may have, but we thought that our use cases probably wouldn't need it given we were talking about single digit nanometers. I am currently working with a dataset that would prefer fractional units, so it's possible this may change. There may be a good deal of software written with integer units in mind though.

**Comment by william-silversmith** [comment]
I am currently working on this, but it is a slow process to make sure everything is working in both CV and Igneous before releasing it.

**Comment by william-silversmith** [comment]
This was resolved in https://github.com/seung-lab/cloud-volume/pull/467!
