### ISSUE TITLE
Is it safe to upload in parallel workers?

### ISSUE THREAD

**Issue by chrisroat** [seung-lab/cloud-volume#282]
I have on-disk data from the same large volume (many ims hdf5 files), and want to run a cluster of workers to upload regions of data in parallel.  If I initialize the `info` file up front, can I perform parallel uploads in my workers, so long as the chunking will fall on region boundaries?   Will they have the potential to clobber each other writing metadata or anything else?  Is there anything else to watch out for?

Is chunking in the channel dimension allowed?  Meaning, can chunks be 4-d: (x_width, y_width, z_width, c_width)?  It would be useful if I can have the channels for a given upload region split across workers.

I briefly looked at Igneous, but noted the HDF5 Ingest task seems to be deprecated (and I'm not sure it processes IMS format, specifically).

**Comment by william-silversmith** [comment]
Hi Chris,

It's safe to perform parallel upload so long as there is zero overlap between uploading processes (which is usually easy to accomplish). The HDF5 ingest hasn't been worked on in a while, but you can take inspiration from it and build a docker container to your liking. CloudVolume supports up to three channels natively. I haven't tried more so I forget if it works. 

I'm not familiar with IMS format, but if you can convert it into a numpy array, you can load it into CloudVolume like so: https://github.com/seung-lab/cloud-volume/wiki/Example-Single-Machine-Dataset-Upload

Let me know if you need a few more pointers!

**Comment by chrisroat** [comment]
I have been able to do IMS->numpy->cloud-volume in a single worker.  My guess is that the old HDF5 ingest doesn't understand the IMS hdf5 format.

For parallel upload, I want to dig in a little further.  My initial thought was that the chunking would have to align with the region I'm uploading.  When I try to do non-aligned writing, I get a warning:

```
AlignmentError: 
  Non-Aligned writes are disabled by default. There are several good reasons 
  not to use them. 
...
```

I can override this, but I'd still worry that two workers operating on the same chunk (even if they don't overlap) could run into a potential conflict.

**Comment by william-silversmith** [comment]
It would probably be easier to write a new Igneous task than to reuse the HDF5 stuff we have in there. Fortunately, those tasks are pretty easy to write:

```python
class SomeTask(RegisteredTask):
    def __init__(self, arguments....):
         super(SomeTask, self).__init__(arguments)
    def execute(self):
         # logic goes here
```
You'd then need to build the docker container and upload it to dockerhub (or your container service of choice).

Regarding the alignment error, so long as the `chunk_sizes`  in your info file evenly divides task shapes you are uploading, there will be no conflicts. If you're getting an alignment error, I would strongly encourage not overriding it as you'll end up with race conditions unless you are very careful. It's okay to override when using a single process or when you know that there is no spatial overlap between concurrent tasks.

https://github.com/seung-lab/cloud-volume/wiki/Advanced-Topic:-Non-Aligned-Writes

**Comment by chrisroat** [comment]
Thanks for all the help.  I've found I can parallel write so long as I don't have multiple workers write the same chunk.  I also found that you cannot chunk along the channel dimension, though perhaps I wasn't do something correctly.
