### ISSUE TITLE
os.path.join bug

### ISSUE THREAD

**Issue by ntabris** [seung-lab/cloud-volume#284]
Got this error on a Windows machine:
```
 File "C:\Anaconda3\lib\site-packages\cloudvolume\datasource\precomputed\skeleton\unsharded.py", line 80, in get
    raise SkeletonDecodeError("File(s) do not exist: {}".format(", ".join(missing)))
cloudvolume.exceptions.SkeletonDecodeError: File(s) do not exist: skeletons_mip_1_v2\81137567487249263, skeletons_mip_1_v2\80715767406190857, skeletons_mip_1_v2\80505692033228303, skeletons_mip_1_v2\81210410334024657
```

On my local install I changed these lines
https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/datasource/precomputed/skeleton/unsharded.py#L73

https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/datasource/precomputed/skeleton/unsharded.py#L113

to use "/" instead of "\\" and was able to download the files.

This is similar to issue #273.

**Comment by ntabris** [comment]
Fyi, this is cloudvolume 0.65.1.

**Comment by william-silversmith** [comment]
Hi Nat, CloudVolume 0.65.2 should have a fix for you.

**Comment by ntabris** [comment]
Thanks, Will!
