### ISSUE TITLE
Refactor: Cloud Volume Factory

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/cloud-volume#29]
The Key-Value precomputed and the BOSS are kind of entangled. It works for now, but if we wanted to add another cutout service (e.g. nifty, ndio, dvid, etc) we'd be in a jam. 

We should make it so that there's some kind of factory that produces the right object that has a (mostly) uniform interface.

**Comment by jingpengw** [comment]
For BOSS, creating a separate package might be better, since it is completely different with other cloud storages.

**Comment by william-silversmith** [comment]
We've reached the point where it makes sense to support a suite of features in order to support images, meshes, and skeletons on Precomputed, Sharded Precomputed, Graphene, and Boss (which sort of demos the idea of a plugin system).

The design I'm thinking of is that there is e.g. a PrecomputedMetadataService that fetches and manages info files and provenance files and a Boss version that provides an analogous interface. 

The metadataservice feeds e.g. PrecomputedImageSource, PrecomputedMeshSource, and PrecomputedSkeletonSource which can in theory point at different locations (e.g. Google Storage and BigTable).

**Comment by william-silversmith** [comment]
Mostly addressed in #230 

This will evolve a bit more as we integrate graphene and the new Precomputed shards.

**Comment by william-silversmith** [comment]
Resolved in #236
