### ISSUE TITLE
Graphene does not get a GrapheneMeshSource

### ISSUE THREAD

**Issue by ceesem** [seung-lab/cloud-volume#295]
A recent commit (87d5197) refactored the PrecomputedMeshSource with a `__new__` method. Because GrapheneMeshSource subclasses PrecomputedMeshSource, it gets the wrong type (`cloudvolume.datasource.precomputed.mesh.unsharded.UnshardedLegacyPrecomputedMeshSource`) and thus can't load any meshes.

Aside from fixing this one issue, this makes me think a useful refactor would be to create a basic MeshSource class that both Precomputed and Graphene inherit from, thus freeing Precomputed-specific changes from propagating into mesh sources for the different but critical proofreading tasks.

**Comment by william-silversmith** [comment]
Forrest has a fix for this in #297 where he updates the class to the `UnshardedLegacyPrecomputedMeshSource`

**Comment by ceesem** [comment]
Do you think that this new subclassing is a stable, long-term solution, or do you see `UnshardedLegacyPrecomputedMeshSource` as something that might need to drift away and include additional changes that should not affect Graphene?

**Comment by william-silversmith** [comment]
It's relatively stable. It corresponds to the existing mesh code. Jeremy
defined a multi-res sharded and unsharded format, and implicitly there
would also be a sharded legacy format that is unsupported by neuroglancer.
Fwiw, this breaking change would have been caught by tests and Forrest
seems to be adding some.

I'm a little surprised you encountered this problem as this code hasn't
been featured in a release yet. It's not a problem, but are you using CV
directly from master?

**Comment by ceesem** [comment]
Yeah, on my analysis environment I'm running CV from code instead of release versions, since there have been several occasions where small tweaks have been necessary to diagnose mesh-stitching problems. I happened to pull it recently because of a particular mesh issue where the recent code worked to fix a merge elsewhere.

I hadn't realized that code that didn't pass tests was pushed into master.

**Comment by william-silversmith** [comment]
Code must pass tests to get merged into master... it's just in this case there were none. :(

**Comment by ceesem** [comment]
Yeah, this turned out to be a good impetus to get graphene-specific tests going posthaste, and it looks like they should catch the basic problems now. This should help keep things stable going forward! I'm going to close the issue.
