### ISSUE TITLE
Properly support graphene draco meshes at multiple graph levels

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/cloud-volume#299]
In order to provide properly stitched meshes, we need to account for the draco grid size during quantization, which can only be gotten from the PyChunkGraph (PCG) in graphene. 

@manuel-castro and I discussed the proper way to serve entire meshes and it requires integrating some of the PCG server code into CloudVolume. PCG only generates some of the mesh levels initially (up to 6), which still leaves cells split into chunks. Fusing those chunks requires a somewhat sophisticated procedure as the PCG includes "skip connections" from upper levels to lower levels to reduce the total storage requirement. 

In order to get adjacent chunks to stitch correctly, cyclic draco quantization, conversion into physical coordinates, deduplication, and stitching are required to walk up the PCG levels until a whole cell is constituted. 

We considered keeping the code in only the PCG and downloading from there, but this would make the PCG a bottleneck for mesh downloading, which we assume will have a spiky access pattern when researchers wish to perform a bulk analysis. Putting the code in cloudvolume allows us to reduce the centralized load and allow more horizontal scale-out.

We discussed how to maintain two versions of the code, and it seems like perhaps putting it into cloudvolume and then having PCG use that version would simplify things.

**Comment by fcollman** [comment]
i'm guessing you are all aware of this, but to do proper vertex deduplication with meshes that are at multiple levels, you will need to explicitly map the level of each fragment and do deduplication differently based upon what fragments are involved.  This is going to be much more computationally expensive that the present approach which can use modulus math and some clever use of unique to find the right subset of duplicates to merge.  The ideal situation would be for mesh vertices to come with their own special flags that indicate that they are 'border' vertices and are eligible for merging, and then you could deduplicate 'border' vertices when there are exactly two of them. This would require some major lifting of the meshing infrastructure though.

**Comment by william-silversmith** [comment]
I think for the present attempt, we are going to just try to get base deduplication working and build on it in a second attempt as just getting this non-autapse respecting version working will be a good amount of effort and there's something sitting broken in there right now. However, we could possibly raise our level of ambition.

**Comment by william-silversmith** [comment]
![Screen Shot 2020-03-19 at 5 51 54 PM](https://user-images.githubusercontent.com/2517065/77118406-7dbd5a00-6a0a-11ea-96bb-003b83beb866.png)

Description of graphene label structure. Credit: Sven Dorkenwald
