### ISSUE TITLE
Return `shape` as a tuple for consistency with numpy

### ISSUE THREAD

**Issue by chrisroat** [seung-lab/cloud-volume#304]
[Dask](https://dask.org/) is a great library for doing massive parallel processing on multidimensional datasets.   It is based heavily on the numpy interface.  Given how good CloudVolume is as a storage backend with similar semantics, it would be a great addition to have CloudVolume work with Dask.

As a first attempt to do local processing using CloudVolume and Dask, I encountered a small discrepancy in the CloudVolume API, as compared to Numpy, that I had to paper over.  In [this gist](https://gist.github.com/chrisroat/2024a495710a871fc7484a5071356815), you can see how I needed to return the CloudVolume `shape` property as a tuple rather than as an array.

Would updating CloudVolume to use a tuple for `shape` be problematic?

I have not tried doing more complex operations (like multi-machine processing), for which additional API methods may be necessary.

**Comment by william-silversmith** [comment]
Hi Chris,

I'm open to this, it would be good to be Dask compatible. I prefer array
return type because it's easier to manipulate, so I'd like to see if
another approach is possible first. Can you post the error you got?

Thanks!

Will

**Comment by chrisroat** [comment]
Yes, there are pros and cons to tuples, and I don't tend to use them. 

A concern with trying something different than what numpy is doing is that there may be other gotchas down the road.  I've only tried a small, local dask task.   When going to larger calculations and distributed calculations, there may be other issues (caching, data transfer, etc).

I have the error messages shown in [this thread](https://github.com/dask/dask-image/issues/128).  It centers around a boolean test, which arrays aren't suited for because it's unclear if it's an `and` or `or`.  In this case, I believe it simply was checking existence.

**Comment by chrisroat** [comment]
Also, I did forget to mention the `ndim` method is missing in CloudVolume, which seems to be simply `len(self.shape)`.

**Comment by william-silversmith** [comment]
I checked one of the other projects that uses CloudVolume (Igneous) and it seems that there's a small bit of code that assumes the array form there.  It does make me a bit nervous to change this all of a sudden as it could break the code for several people. I'll see if I can audit other lab members' code. 

An alternative would be a "dask_compatibility" flag, but that's ugly.

**Comment by chrisroat** [comment]
I agree that a flag isn't the right way to go.  One approach would be to add a warning notice of some type for some weeks/months, and the bump a major version number when the change released.  It's likely not a major change to people's downstream code, but not knowing your users, I defer to your judgement.

Scikit-learn has  [a decent recommendation on changing behaviors](https://scikit-learn.org/stable/developers/contributing.html#change-the-default-value-of-a-parameter).

**Comment by william-silversmith** [comment]
I did a survey of seung-lab repos and it seems like only igneous is obviously affected. I'll put this through.
