### ISSUE TITLE
Auth tokens should be passable to Graphene

### ISSUE THREAD

**Issue by ceesem** [seung-lab/cloud-volume#311]
The auth tokens that we are converging on for pychunkgraph and other endpoints are not limited to cloudvolume, and it's even conceivable that someone might need them to programmatically access data even without cloudvolume installed. I can also see cases where, for testing, we need to use different tokens with different access levels. It would thus be good to not purely hard code the tokens to a cloudvolume secrets file, but also allow a graphene cloudvolume to accept an auth token as an argument on initialization.

**Comment by william-silversmith** [comment]
Hi Casey, 

This is a good feature idea and something we should try to implement. I'm backed up at the moment, but if you have a pressing need for it, let me know and I can bump it up the priority list.

**Comment by ceesem** [comment]
It seems like the main barrier to adding `auth_token` as an argument to CloudVolume initialization is that all keyword arguments for the plugins are specified exactly and thus need to match across precomputed, graphene, etc. Given the way the plugin architecture works, is there any reason to not have a **kwargs argument for CloudVolume and each specific CloudVolume plugin init function so that they can take optional, plugin-specific arguments without throwing an error if the plugin and the keyword arguments are inadvertently mismatched? If so, this would be easy to implement and I'd be happy to give it a pass myself, but it's also simple enough that I wonder if you intentionally avoided doing it.

**Comment by ceesem** [comment]
Btw, this isn't urgent, but we are starting to experiment with a dataset that's fully behind an auth server and I would like to update all the framework clients in a uniform way, including those that rely on cloudvolume.

**Comment by william-silversmith** [comment]
Hi Casey,

I've been trying to avoid **kwargs as much as possible as it makes the code more difficult to read and use. There will come a point where it is necessary, but I would like to postpone it as long as possible. In this case, I think a kind of generic secrets mechanism would work well for both graphene and precomputed. That is, you provide a `secrets={ .. }` where the form of the secret is identical to the JSON file form. The service provider can be cribbed from either the protocol (in the case of precomputed 's3', 'gs', etc) or the format in the case of graphene (i.e. `graphene://`).

Would that sound good to you?

**Comment by ceesem** [comment]
That seems like a good solution to me, and then each of the individual datasources can figure out what to with it. Thanks for thinking on it!

**Comment by william-silversmith** [comment]
As a workaround (official solution?) you can do this:

```
import cloudvolume.secrets
cloudvolume.secrets.chunkedgraph_credentials = json.loads(...)
```

**Comment by william-silversmith** [comment]
I guess this solution is deficient as it doesn't allow each CV client to have different tokens. Let me know if you need this feature.
