### ISSUE TITLE
Writing to volume (by slicing notation) is not properly checking slice.start < slice.stop

### ISSUE THREAD

**Issue by shangmu** [seung-lab/cloud-volume#314]
cv[(slice(0,1),slice(0,1),slice(779,344))] = 0  appears to clear out 344:779 rather than the expected behavior of not writing anything because the effective range is empty.

**Comment by william-silversmith** [comment]
What is the chunk size of the dataset? Is non-aligned writes on?

**Comment by shangmu** [comment]
Yes non-aligned writes was on. Chunk size 128*128*64
