### ISSUE TITLE
Error reading sharded volume

### ISSUE THREAD

**Issue by schlegelp** [seung-lab/cloud-volume#329]
Hi William!

Hope this finds you well. I'm trying to access Peter's [tissue mask](https://twitter.com/stardazed0/status/1190689938473242624?s=20) for FAFB but run into the following error:
```Python
from cloudvolume import CloudVolume
vol = CloudVolume('gs://fafb-ffn1-20190805/tissue_mask_argmax')
vol[:,:,100]

--------------------------------------------------------------------------
SpecViolation                             Traceback (most recent call last)
<ipython-input-20-899f3f9cab98> in <module>
----> 1 vol[:,:,100]
Downloading:   0%|                                                    | 0/127332 [00:00<?, ?it/s]
~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/frontends/precomputed.py in __getitem__(self, slices)
    526     requested_bbox = Bbox.from_slices(slices)
    527 
--> 528     img = self.download(requested_bbox, self.mip)
    529     return img[::steps.x, ::steps.y, ::steps.z, channel_slice]
    530 

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/frontends/precomputed.py in download(self, bbox, mip, parallel, segids, preserve_zeros, agglomerate, timestamp, stop_layer)
    568       parallel = self.parallel
    569 
--> 570     img = self.image.download(bbox, mip, parallel=parallel)
    571 
    572     if segids is None:

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/image/__init__.py in download(self, bbox, mip, parallel, location, retain, use_shared_memory, use_file, order)
    120         progress=self.config.progress,
    121         fill_missing=self.fill_missing,
--> 122         order=order,
    123       )
    124     else:

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/image/rx.py in download_sharded(requested_bbox, mip, meta, cache, spec, compress, progress, fill_missing, order)
     63   for gridpoint in gpts:
     64     zcurve_code = compressed_morton_code(gridpoint, grid_size)
---> 65     chunkdata = reader.get_data(zcurve_code, meta.key(mip))
     66 
     67     cutout_bbox = Bbox(

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/sharding.py in get_data(self, label, path)
    390         return cached
    391 
--> 392     index = self.get_index(filename, path)
    393 
    394     minishard_index = self.get_minishard_index(

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/sharding.py in get_index(self, filename, path)
    274       raise SpecViolation(
    275         filename + " was an incorrect length ({}) for this specification ({}).".format(
--> 276           binary_bytes, index_length
    277         ))
    278 

SpecViolation: 000.shard was an incorrect length (0) for this specification (1024).
```

I'm sure I'm doing something wrong here but can't figure out what it is. This is with cloud-volume `1.10.0`.

**Comment by william-silversmith** [comment]
I don't think you're doing anything wrong. It looks like there's a difference in how the shard filenames were generated. CloudVolume is zero padding the shard name to `000.shard` while neuroglancer is accessing `0.shard`. Let me check the spec.

**Comment by william-silversmith** [comment]
https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/sharded.md

"For each shard number in the range [0, 2**shard_bits), there is a <shard>.shard file, where <shard> is the lowercase base-16 shard number zero padded to ceil(shard_bits/4) digits."

In this case, the number of shard bits is 11. ceil(2.75) = 3, so 3 zeros. Let me ask Jeremy what to do.

**Comment by william-silversmith** [comment]
Jeremy correctly pointed out that I was looking at a zoomed out mip level. Oops. Let me investigate further.

**Comment by schlegelp** [comment]
Thanks, your help is very much appreciated!

**Comment by william-silversmith** [comment]
Ah.. [here's the problem](https://neuroglancer-demo.appspot.com/fafb.html#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%2C%22position%22:%5B361.8945617675781%2C161.5236053466797%2C100.5%5D%2C%22crossSectionScale%22:1.0800094185337634%2C%22projectionOrientation%22:%5B0%2C0.7071067690849304%2C0%2C0.7071067690849304%5D%2C%22projectionScale%22:55546.038714232054%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/fafb_v14/fafb_v14_clahe%22%2C%22name%22:%22fafb_v14_clahe%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://fafb-ffn1-20190805/tissue_mask_argmax%22%2C%22crossSectionRenderScale%22:0.846392351886956%2C%22name%22:%22tissue_mask_argmax%22%7D%5D%2C%22showAxisLines%22:false%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22layer%22:%22tissue_mask_argmax%22%2C%22visible%22:true%7D%2C%22layout%22:%22xy%22%7D).

<img width="999" alt="image" src="https://user-images.githubusercontent.com/2517065/79772747-738ac600-82fe-11ea-8124-c4f1645bad3e.png">

<img width="724" alt="image" src="https://user-images.githubusercontent.com/2517065/79772778-7e455b00-82fe-11ea-8d9c-cf5d35986bd5.png">

The shard is present, but is zero bytes.

**Comment by schlegelp** [comment]
I see! I can indeed access data if I make sure it's somewhere in the middle of the volume:
```Python
vol[int(42591/4), int(56962/4), 3843] 
VolumeCutout([[[[1]]]], dtype=uint64)
```
Ideally I would like to be able to load an entire z slice at low resolution at a time. I guess I could wrap this the query in a `try/except` statement. Do you have a better idea?

**Comment by william-silversmith** [comment]
@schlegelp I'm going to release a new version of CloudVolume with support for `fill_missing` in sharded. You can just change your script to this:

```
from cloudvolume import CloudVolume
vol = CloudVolume('gs://fafb-ffn1-20190805/tissue_mask_argmax', fill_missing=True)
vol[:,:,100]
```

**Comment by schlegelp** [comment]
Sweet, thank a lot!

**Comment by william-silversmith** [comment]
@schlegelp version 1.11.0 should have what you're looking for!
