### ISSUE TITLE
Required install: libffi-dev 

### ISSUE THREAD

**Issue by KyleLuther** [seung-lab/cloud-volume#36]
I had to sudo apt-get install libffi-dev before pip installing cloud-volume

**Comment by william-silversmith** [comment]
Hi Kyle! Can you tell me a little bit more about the system you were having
a problem with?

**Comment by william-silversmith** [comment]
I haven't heard of anyone else reporting this issue. Would it be okay to close it?

**Comment by william-silversmith** [comment]
I'm going to close this issue. Let me know if it becomes a problem and we can reopen it.
