### ISSUE TITLE
Get mesh of google segmentation

### ISSUE THREAD

**Issue by jamesnobody** [seung-lab/cloud-volume#368]
Hi cloud-volume group,
I have already download google segmentation of `256.0x256.0x320.0` resolution, because of the native resolution is too big (same as the mesh).
I want to get the `256.0x256.0x320.0` resolution's mesh, and i use the following code:
```
vol= CloudVolume('file:///mnt/d/braindata/google_256.0x256.0x320.0/')
image = vol[:,:,:] 
mesh = vol.mesh.get(labels)
```
But is seems that the volume is too big (The unzipped file is too large), that i could not get the mesh.
Do you have any good solutions for this limited memory (32GB) to get specific labels?

**Comment by jamesnobody** [comment]
When i change the resolution to `512.0x512.0x640.0`, and use the same code as above, it gives me that:
![image](https://user-images.githubusercontent.com/68318867/88497181-2b143000-cff2-11ea-8a6d-6023687f4174.png)
Does the id not exist? But i see the skeleton of this id.

**Comment by william-silversmith** [comment]
To be clear you want to get all the meshes in the volume?

**Comment by jamesnobody** [comment]
I just want to get some specific label's mesh.

**Comment by william-silversmith** [comment]
Why are you downloading the entire volume image if you don't mind my asking? Is the image too large or the mesh?

**Comment by jamesnobody** [comment]
I did not download the mesh because it is too large(1.1T), and i just download the image of `256.0x256.0x320.0` resolution.

**Comment by william-silversmith** [comment]
I think there is something I am not quite understanding. Most meshes (in our pipeline) are not nearly that large as they are derived from a near isotropic mip level and are simplified. Occasionally a mesh might be very large, but this is usually because it is an enormous tangle of pieces of different cells fused together and not worth anything analytically. How is your mesh so big? Is there a public version of this dataset I could try experimenting with?

**Comment by jamesnobody** [comment]
I downloaded the mesh use gsutil `gsutil -m cp -r gs://fafb-ffn1-20190805/segmentation/mesh/* mesh/`, itseems very large,
And my question is how to extract the mesh of the specified label at a specific resolution?
I use the code
```
mesh = vol.mesh.get(labels)
```
but it tells me wrong same like the second comment.
Is it because I didn't download the mesh?
 Is there a public version of mesh i can download or some method to extract the mesh of the specified label at a specific resolution?

**Comment by william-silversmith** [comment]
Could you share which label you're looking at? That would help me a lot in understanding the problem.

One way to download things from Google directly is:

```python
cv = CloudVolume("gs://fafb-ffn1-20190805/segmentation", use_https=True, cache=True)
mesh = cv.mesh.get(label)[label]
```

**Comment by jamesnobody** [comment]
Now I am looking at label:`2143659517`, I saw it on [neuroglancer](https://neuroglancer-demo.appspot.com/fafb.html#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%2C%22position%22:%5B109421.8984375%2C41044.6796875%2C5417%5D%2C%22crossSectionScale%22:2.1875%2C%22projectionOrientation%22:%5B0.5118544697761536%2C0.26221662759780884%2C-0.7955290079116821%2C0.190738245844841%5D%2C%22projectionScale%22:205216.39806641723%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/fafb_v14/fafb_v14_orig%22%2C%22name%22:%22fafb_v14%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/fafb_v14/fafb_v14_clahe%22%2C%22name%22:%22fafb_v14_clahe%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://fafb-ffn1-20190805/segmentation%22%2C%22tab%22:%22segments%22%2C%22segments%22:%5B%222143659517%22%5D%2C%22name%22:%22fafb-ffn1-20190805%22%7D%2C%7B%22type%22:%22annotation%22%2C%22source%22:%22precomputed://gs://neuroglancer-20191211_fafbv14_buhmann2019_li20190805%22%2C%22tab%22:%22rendering%22%2C%22annotationColor%22:%22#cecd11%22%2C%22shader%22:%22#uicontrol%20vec3%20preColor%20color%28default=%5C%22blue%5C%22%29%5Cn#uicontrol%20vec3%20postColor%20color%28default=%5C%22red%5C%22%29%5Cn#uicontrol%20float%20scorethr%20slider%28min=0%2C%20max=1000%29%5Cn#uicontrol%20int%20showautapse%20slider%28min=0%2C%20max=1%29%5Cn%5Cnvoid%20main%28%29%20%7B%5Cn%20%20setColor%28defaultColor%28%29%29%3B%5Cn%20%20setEndpointMarkerColor%28%5Cn%20%20%20%20vec4%28preColor%2C%200.5%29%2C%5Cn%20%20%20%20vec4%28postColor%2C%200.5%29%29%3B%5Cn%20%20setEndpointMarkerSize%285.0%2C%205.0%29%3B%5Cn%20%20setLineWidth%282.0%29%3B%5Cn%20%20if%20%28int%28prop_autapse%28%29%29%20%3E%20showautapse%29%20discard%3B%5Cn%20%20if%20%28prop_score%28%29%3Cscorethr%29%20discard%3B%5Cn%7D%5Cn%5Cn%22%2C%22shaderControls%22:%7B%22scorethr%22:80%7D%2C%22linkedSegmentationLayer%22:%7B%22pre_segment%22:%22fafb-ffn1-20190805%22%2C%22post_segment%22:%22fafb-ffn1-20190805%22%7D%2C%22filterBySegmentation%22:%5B%22post_segment%22%2C%22pre_segment%22%5D%2C%22name%22:%22synapses_buhmann2019%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%22n5://gs://fafb-v14-synaptic-clefts-heinrich-et-al-2018-n5/synapses_dt_reblocked%22%2C%22opacity%22:0.73%2C%22shader%22:%22void%20main%28%29%20%7BemitRGBA%28vec4%280.0%2C0.0%2C1.0%2CtoNormalized%28getDataValue%28%29%29%29%29%3B%7D%22%2C%22name%22:%22clefts_Heinrich_etal%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/elmr-data/FAFBNP.surf/mesh#type=mesh%22%2C%22segments%22:%5B%221%22%2C%2210%22%2C%2211%22%2C%2212%22%2C%2213%22%2C%2214%22%2C%2215%22%2C%2216%22%2C%2217%22%2C%2218%22%2C%2219%22%2C%222%22%2C%2220%22%2C%2221%22%2C%2222%22%2C%2223%22%2C%2224%22%2C%2225%22%2C%2226%22%2C%2227%22%2C%2228%22%2C%2229%22%2C%223%22%2C%2230%22%2C%2231%22%2C%2232%22%2C%2233%22%2C%2234%22%2C%2235%22%2C%2236%22%2C%2237%22%2C%2238%22%2C%2239%22%2C%224%22%2C%2240%22%2C%2241%22%2C%2242%22%2C%2243%22%2C%2244%22%2C%2245%22%2C%2246%22%2C%2247%22%2C%2248%22%2C%2249%22%2C%225%22%2C%2250%22%2C%2251%22%2C%2252%22%2C%2253%22%2C%2254%22%2C%2255%22%2C%2256%22%2C%2257%22%2C%2258%22%2C%2259%22%2C%226%22%2C%2260%22%2C%2261%22%2C%2262%22%2C%2263%22%2C%2264%22%2C%2265%22%2C%2266%22%2C%2267%22%2C%2268%22%2C%2269%22%2C%227%22%2C%2270%22%2C%2271%22%2C%2272%22%2C%2273%22%2C%2274%22%2C%2275%22%2C%228%22%2C%229%22%5D%2C%22name%22:%22neuropil-regions-surface%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22mesh%22%2C%22source%22:%22vtk://https://storage.googleapis.com/neuroglancer-fafb-data/elmr-data/FAFB.surf.vtk.gz%22%2C%22shader%22:%22void%20main%28%29%20%7BemitRGBA%28vec4%281.0%2C%200.0%2C%200.0%2C%200.5%29%29%3B%7D%22%2C%22name%22:%22neuropil-full-surface%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%7B%22url%22:%22precomputed://gs://fafb-ffn1-20190805/segmentation%22%2C%22subsources%22:%7B%22default%22:true%2C%22bounds%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22precomputed://gs://fafb-ffn1-20190805/segmentation/skeletons_32nm%22%5D%2C%22selectedAlpha%22:0%2C%22segments%22:%5B%224613663523%22%5D%2C%22name%22:%22skeletons_32nm%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://fafb-ffn1/fafb-public-skeletons%22%2C%22name%22:%22public_skeletons%22%2C%22visible%22:false%7D%5D%2C%22showAxisLines%22:false%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22layer%22:%22fafb-ffn1-20190805%22%2C%22visible%22:true%7D%2C%22layout%22:%22xy-3d%22%7D)
Due to network problems, I have been unable to download data, which makes me crazy.
I use the code and try to download the mesh. But it tells me:
![image](https://user-images.githubusercontent.com/68318867/88746026-0ea4fe80-d17e-11ea-831e-0b577cd328c8.png)

**Comment by jamesnobody** [comment]
Then I change the label:
```python
vol = CloudVolume("gs://fafb-ffn1-20190805/segmentation/", use_https=True, cache=True, progress=True)
label = 710435991
mesh = vol.mesh.get(label)[label]
```
it gave me the same wrong :
![image](https://user-images.githubusercontent.com/68318867/88747825-28484500-d182-11ea-9b4f-d454d073b175.png)

but i can see this id in [neuroglancer](https://neuroglancer-demo.appspot.com/fafb.html#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%2C%22position%22:%5B109357.625%2C41309.41015625%2C5417%5D%2C%22crossSectionScale%22:2.1875%2C%22projectionOrientation%22:%5B0.12379927933216095%2C0.012880716472864151%2C0.058786578476428986%2C-0.9904806613922119%5D%2C%22projectionScale%22:102608.19903320858%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/fafb_v14/fafb_v14_orig%22%2C%22tab%22:%22source%22%2C%22name%22:%22fafb_v14%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/fafb_v14/fafb_v14_clahe%22%2C%22tab%22:%22source%22%2C%22name%22:%22fafb_v14_clahe%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%7B%22url%22:%22precomputed://gs://fafb-ffn1-20200412/segmentation%22%2C%22subsources%22:%7B%22default%22:true%2C%22bounds%22:true%2C%22mesh%22:true%2C%22skeletons%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22tab%22:%22segments%22%2C%22meshSilhouetteRendering%22:3%2C%22segments%22:%5B%22710435991%22%5D%2C%22segmentQuery%22:%22710435991%22%2C%22name%22:%22fafb-ffn1-20200412%22%7D%2C%7B%22type%22:%22annotation%22%2C%22source%22:%22precomputed://gs://neuroglancer-20191211_fafbv14_buhmann2019_li20190805%22%2C%22annotationColor%22:%22#cecd11%22%2C%22shader%22:%22#uicontrol%20vec3%20preColor%20color%28default=%5C%22blue%5C%22%29%5Cn#uicontrol%20vec3%20postColor%20color%28default=%5C%22red%5C%22%29%5Cn#uicontrol%20float%20scorethr%20slider%28min=0%2C%20max=1000%29%5Cn#uicontrol%20int%20showautapse%20slider%28min=0%2C%20max=1%29%5Cn%5Cnvoid%20main%28%29%20%7B%5Cn%20%20setColor%28defaultColor%28%29%29%3B%5Cn%20%20setEndpointMarkerColor%28%5Cn%20%20%20%20vec4%28preColor%2C%200.5%29%2C%5Cn%20%20%20%20vec4%28postColor%2C%200.5%29%29%3B%5Cn%20%20setEndpointMarkerSize%285.0%2C%205.0%29%3B%5Cn%20%20setLineWidth%282.0%29%3B%5Cn%20%20if%20%28int%28prop_autapse%28%29%29%20%3E%20showautapse%29%20discard%3B%5Cn%20%20if%20%28prop_score%28%29%3Cscorethr%29%20discard%3B%5Cn%7D%5Cn%5Cn%22%2C%22shaderControls%22:%7B%22scorethr%22:80%7D%2C%22linkedSegmentationLayer%22:%7B%22pre_segment%22:%22fafb-ffn1-20200412%22%2C%22post_segment%22:%22fafb-ffn1-20200412%22%7D%2C%22filterBySegmentation%22:%5B%22post_segment%22%2C%22pre_segment%22%5D%2C%22name%22:%22synapses_buhmann2019%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22n5://gs://fafb-v14-synaptic-clefts-heinrich-et-al-2018-n5/synapses_dt_reblocked%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%5D%2C%5B0%2C1%2C0%2C0%5D%2C%5B0%2C0%2C1%2C1%5D%5D%2C%22outputDimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%7D%7D%2C%22opacity%22:0.73%2C%22shader%22:%22void%20main%28%29%20%7BemitRGBA%28vec4%280.0%2C0.0%2C1.0%2CtoNormalized%28getDataValue%28%29%29%29%29%3B%7D%22%2C%22name%22:%22clefts_Heinrich_etal%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-fafb-data/elmr-data/FAFBNP.surf/mesh#type=mesh%22%2C%22tab%22:%22segments%22%2C%22segments%22:%5B%221%22%2C%2210%22%2C%2211%22%2C%2212%22%2C%2213%22%2C%2214%22%2C%2215%22%2C%2216%22%2C%2217%22%2C%2218%22%2C%2219%22%2C%222%22%2C%2220%22%2C%2221%22%2C%2222%22%2C%2223%22%2C%2224%22%2C%2225%22%2C%2226%22%2C%2227%22%2C%2228%22%2C%2229%22%2C%223%22%2C%2230%22%2C%2231%22%2C%2232%22%2C%2233%22%2C%2234%22%2C%2235%22%2C%2236%22%2C%2237%22%2C%2238%22%2C%2239%22%2C%224%22%2C%2240%22%2C%2241%22%2C%2242%22%2C%2243%22%2C%2244%22%2C%2245%22%2C%2246%22%2C%2247%22%2C%2248%22%2C%2249%22%2C%225%22%2C%2250%22%2C%2251%22%2C%2252%22%2C%2253%22%2C%2254%22%2C%2255%22%2C%2256%22%2C%2257%22%2C%2258%22%2C%2259%22%2C%226%22%2C%2260%22%2C%2261%22%2C%2262%22%2C%2263%22%2C%2264%22%2C%2265%22%2C%2266%22%2C%2267%22%2C%2268%22%2C%2269%22%2C%227%22%2C%2270%22%2C%2271%22%2C%2272%22%2C%2273%22%2C%2274%22%2C%2275%22%2C%228%22%2C%229%22%5D%2C%22name%22:%22neuropil-regions-surface%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22mesh%22%2C%22source%22:%22vtk://https://storage.googleapis.com/neuroglancer-fafb-data/elmr-data/FAFB.surf.vtk.gz%22%2C%22shader%22:%22void%20main%28%29%20%7BemitRGBA%28vec4%281.0%2C%200.0%2C%200.0%2C%200.5%29%29%3B%7D%22%2C%22name%22:%22neuropil-full-surface%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://fafb-ffn1/fafb-public-skeletons%22%2C%22tab%22:%22segments%22%2C%22name%22:%22public_skeletons%22%2C%22visible%22:false%7D%5D%2C%22showAxisLines%22:false%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22layer%22:%22fafb-ffn1-20200412%22%2C%22visible%22:true%7D%2C%22layout%22:%22xy-3d%22%7D)

**Comment by william-silversmith** [comment]
Looks like there's some kind of bug with the caching option. Try setting `cache=False` for now.

**Comment by jamesnobody** [comment]
It works now, the mesh i get is `Sharded`? 
I want to save the mesh and use the code
```python
vol.mesh.save(label, file_format='obj')
```
but it tells me `AttributeError: 'ShardedMultiLevelPrecomputedMeshSource' object has no attribute 'save'`? How to slove this problem? Should i change it to `unsharded`?

**Comment by william-silversmith** [comment]
The save function is very simple, you can just write `mesh.to_obj()` to get a text representation and save it to a file. I'll update this with some of the missing functionality in the next release.

**Comment by jamesnobody** [comment]
Thanks a lot, I found this founction and save the mesh in my local dir.
By the way, if i want to see low resolution's (such as `32.0x32.0x40.0`)  mesh of a specified label, can i just downsample the original mesh or some methods to get it?

**Comment by william-silversmith** [comment]
For the multi-LOD format (which is present here) you can specify a different LOD:

```python
mesh = cv.mesh.get(label, lod=3)[label]
```

For datasets that are not multi-LOD, you can attempt using [zmesh](https://github.com/seung-lab/zmesh) to simplify it but there's some problem with that I need to look into: https://github.com/seung-lab/zmesh/issues/15

Glad I could help!

**Comment by jamesnobody** [comment]
Thanks a lot, after read the `multilod.py`, i know the lod = 0 is the original resolution, but i still confuse that how to define `lod` according to a sepcific resolution. We know that google segmentation has different resolutions (from `4.0x4.0x40.0` to `2048.0x2048.0x2560.0`).

**Comment by william-silversmith** [comment]
Not necessarily. I believe the lods are a factor of two reduction along each dimension for each step, but the meshes could have been generated from any resolution in the hierarchy (though most probably the most isotropic resolution). However, since the meshes are represented in physical space, one trick you could use is to look for the closest two points in a mesh and estimate the resolution that way.

**Comment by jamesnobody** [comment]
My understanding is that `lod` represents a multiple of downsampling, am I right?

**Comment by william-silversmith** [comment]
https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/meshes.md#multi-resolution-mesh-format

I'm not precisely sure what they mean, most likely they are 2<sup>lod</sup> downsamples of the highest resolution mesh. You can look at the specification above for more guidance.

**Comment by jamesnobody** [comment]
Hi, cloudvolume team,
After i use the code
```python
cv= CloudVolume("gs://fafb-ffn1-20190805/segmentation/", use_https=True, cache=False, progress=True)
mesh = cv.mesh.get(label)[label]
```
to got the mesh  for some specific labels, I met a question. Some meshes are not correctly of segmentation, such as `label = 4753085277`, this label shows in neuroglancer looks like a neruon:
![image](https://user-images.githubusercontent.com/68318867/92833506-83b95400-f40b-11ea-8092-6b5878f26a83.png)

but the mesh looks like:
![image](https://user-images.githubusercontent.com/68318867/92833614-9e8bc880-f40b-11ea-89d9-53b09e125d22.png)
How does this happened? The mesh result does not correspond to the segmentation result.
How to get the correct mesh of the segmentation result.

**Comment by william-silversmith** [comment]
Hi James,

I executed your script and saw the following image using `mesh.viewer()`:

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/2517065/92850096-09acaf00-f3ba-11ea-87f9-3fbe730af5c1.png">

Admittedly, the mesh.viewer() function just visualizes a point cloud and not a mesh, but it looks okay at first glance.

**Comment by jamesnobody** [comment]
But when i save the mesh in my local file as `.obj` or `.ply`, the mesh file looks like different from the segmentation result
file content:
![image](https://user-images.githubusercontent.com/68318867/92851390-16fc8480-f420-11ea-86b3-114e625604c9.png)
Lots of points are the same

**Comment by william-silversmith** [comment]
Have you tried clearing your cache? Do you have the latest version of CloudVolume?

**Comment by jamesnobody** [comment]
I use the CloudVolume 2.0.0 version, and I set the cache = False in my code, did i missing something else?

**Comment by william-silversmith** [comment]
Can you show me the output of this script?

```
label = 4753085277
cv = CloudVolume("gs://fafb-ffn1-20190805/segmentation/", use_https=True, cache=False, progress=True)
print(cv.mesh)
mesh = cv.mesh.get(label)[label]
mesh.viewer()
```

**Comment by jamesnobody** [comment]
I could not use the last line because of i use the wsl (windows system)
![image](https://user-images.githubusercontent.com/68318867/92855168-9724e900-f424-11ea-9858-bb96aee64726.png)
The above is the result except the last line

**Comment by william-silversmith** [comment]
If you're on Windows, what does the `sys.platform` say? Also, try upgrading to 2.1.1, I included an important windows fix in the last update.

**Comment by jamesnobody** [comment]
I use the  Windows Subsystem for Linux, so, if i use vtk in jupyter notebook, the notebook will be shutdown and restart. Did the mesh i got wrong? or What causes the mesh error

**Comment by william-silversmith** [comment]
oh... another possible issue is that Windows doesn't support DracoPy. Luckily by chance, we (me and @manuel-castro) are working on fixing that over the next few days.

I've never used WSL, I hear it's supposed to be just like Linux, but I dunno. :-/ Can you show me your `sys.platform` string?

**Comment by jamesnobody** [comment]
![image](https://user-images.githubusercontent.com/68318867/92856700-529a4d00-f426-11ea-8094-6f984f2b37bd.png)
Actually i download the Ubuntu 18.04 in windows store and use it.
![image](https://user-images.githubusercontent.com/68318867/92856892-88d7cc80-f426-11ea-8be2-8087d1e0826d.png)

**Comment by william-silversmith** [comment]
That's really weird... I'm not sure what's going on. I don't have access to Windows/WSL so I can't investigate it myself. If you're able to dig into the code you might be able to find something. If not, you can try running it in Anaconda under Windows when we release DracoPy binaries and a compatible CloudVolume version probably by Monday.

You can also try using the Murthy Lab's https://github.com/murthylab/Meshdown Docker which was written to get around CloudVolume's lack of support for meshes on Windows.

**Comment by jamesnobody** [comment]
I ok, i check the code, and did not find something weird.
I use the code to get lots of meshes, and some meshes are correct, but the others are differenet from the segmentation result. Does the `cv = CloudVolume("gs://fafb-ffn1-20190805/segmentation/", use_https=True, cache=False, progress=True)` the code get the wrong mesh?

**Comment by william-silversmith** [comment]
One other thing you can try: set the lod=1 and see if it looks better?

**Comment by jamesnobody** [comment]
I tried lod = 1, 2, but the result is the same, they are all different from the segmentation. 
It contains lots of same points.
The coordinates of many points in a mesh file are the same.

**Comment by william-silversmith** [comment]
Hi James, we just released `cloud-volume==2.2.0` and associated DracoPy binaries for windows. You can try using Anaconda and see if that works for you.

**Comment by jamesnobody** [comment]
Ok, I will try it later.

By the way.
Have you read the specific coordinates? They are the same as mine, there are many repeated numbers.

**Comment by william-silversmith** [comment]
Hi James,

I ran the script and printed out the first 100 mesh vertices like you did. Here were my results:

```
<cloudvolume.datasource.precomputed.mesh.multilod.ShardedMultiLevelPrecomputedMeshSource object at 0x7f87b7be2400>
[[376840.    227375.97  103500.016]
 [376840.    227367.97  103520.016]
 [376840.    227359.97  103500.016]
 [376840.    227367.97  103480.016]
 [376656.    227447.97  103860.02 ]
 [376648.    227447.97  103880.02 ]
 [376648.    227447.97  103840.02 ]
 [376648.    227439.97  103860.02 ]
 [376816.    227383.97  103860.02 ]
 [376824.    227391.97  103860.02 ]
 [376824.    227375.97  103860.02 ]
 [376832.    227383.97  103860.02 ]
 [376688.    227447.97  103780.02 ]
 [376696.    227447.97  103800.02 ]
 [376696.    227439.97  103780.02 ]
 [376696.    227447.97  103760.02 ]
 [376368.    227399.97  103700.02 ]
 [376376.    227399.97  103760.02 ]
 [376384.    227399.97  103740.02 ]
 [376376.    227399.97  103680.016]
 [376344.    227199.97  103700.02 ]
 [376344.    227191.97  103720.02 ]
 [376344.    227183.97  103700.02 ]
 [376360.    227191.97  103680.016]
 [376720.    227239.97  103660.016]
 [376736.    227239.97  103620.016]
 [376728.    227239.97  103680.016]
 [376728.    227239.97  103600.016]
 [376656.    227479.97  103620.016]
 [376672.    227479.97  103620.016]
 [376664.    227479.97  103640.016]
 [376664.    227479.97  103600.016]
 [376792.    227471.97  103620.016]
 [376808.    227463.97  103640.016]
 [376792.    227455.97  103620.016]
 [376792.    227463.97  103600.016]
 [376344.    227455.97  103620.016]
 [376392.    227447.97  103640.016]
 [376360.    227439.97  103620.016]
 [376376.    227447.97  103600.016]
 [376424.    227367.97  103600.016]
 [376424.    227367.97  103680.016]
 [376520.    227375.97  103660.016]
 [376488.    227367.97  103560.016]
 [376312.    227071.97  103620.016]
 [376312.    227095.97  103680.016]
 [376312.    227095.97  103600.016]
 [376312.    227119.97  103660.016]
 [376704.    227495.97  103580.016]
 [376720.    227495.97  103580.016]
 [376712.    227495.97  103600.016]
 [376712.    227495.97  103560.016]
 [376264.    227343.97  103580.016]
 [376264.    227335.97  103600.016]
 [376264.    227327.97  103580.016]
 [376272.    227335.97  103580.016]
 [376216.    227343.97  103580.016]
 [376232.    227335.97  103600.016]
 [376216.    227327.97  103580.016]
 [376232.    227335.97  103560.016]
 [376744.    227271.97  103600.016]
 [376760.    227263.97  103740.02 ]
 [376760.    227287.97  103760.02 ]
 [376728.    227271.97  103560.016]
 [376736.    227319.97  103580.016]
 [376728.    227287.97  103600.016]
 [376408.    227279.97  103580.016]
 [376416.    227271.97  103580.016]
 [376408.    227271.97  103600.016]
 [376408.    227271.97  103560.016]
 [376600.    227407.97  103540.016]
 [376600.    227431.97  103600.016]
 [376632.    227415.97  103520.016]
 [376600.    227431.97  103520.016]
 [376792.    227375.97  103540.016]
 [376776.    227367.97  103600.016]
 [376776.    227367.97  103520.016]
 [376808.    227367.97  103520.016]
 [376584.    227383.97  103520.016]
 [376584.    227383.97  103600.016]
 [376592.    227351.97  103540.016]
 [376608.    227383.97  103540.016]
 [376576.    227335.97  103500.016]
 [376552.    227303.97  103600.016]
 [376544.    227335.97  103540.016]
 [376552.    227303.97  103520.016]
 [376424.    227319.97  103600.016]
 [376376.    227335.97  103600.016]
 [376360.    227319.97  103520.016]
 [376376.    227295.97  103580.016]
 [376816.    227239.97  103540.016]
 [376832.    227239.97  103540.016]
 [376824.    227239.97  103560.016]
 [376824.    227239.97  103520.016]
 [376280.    227079.97  103480.016]
 [376280.    227087.97  103580.016]
 [376280.    227079.97  103600.016]
 [376288.    227079.97  103540.016]
 [376064.    227031.97  103540.016]
 [376080.    227031.97  103540.016]]```

**Comment by jamesnobody** [comment]
Thanks a lot, now i am trying install the cloudvolume on windows, If i meet some problem i will update in this issue.

**Comment by jamesnobody** [comment]
It works now, i got the correct mesh. Thanks a lot!

**Comment by william-silversmith** [comment]
Yay! I'm glad it worked! Please reopen this issue if you have further problems. :)
