### ISSUE TITLE
Should CloudVolume continue supporting Python 2.7?

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/cloud-volume#380]
Post your comment below.

Twitter thread: https://twitter.com/thundercloudvol/status/1292912062662873089

**Comment by nkemnitz** [comment]
The 👎 should be read as "Drop support for Python2.7"
* It's been 8 months since the 5 year grace period for Python2 passed
* No bug fixes for [numpy](https://docs.scipy.org/doc/numpy-1.14.2/neps/dropping-python2.7-proposal.html), [google-cloud](https://cloud.google.com/python/docs/python2-sunset#python-client-library) and other smaller packages available

**Comment by fcollman** [comment]
100% agree with Nico. I would be more passive about it in so far as I would no longer make major design decisions with 2.7 in mind, which means In practice it will take some time to have support actually drop. Most important is that you announce dropping of support before you drop it, which is an argument for making that announcement sooner than later.

**Comment by william-silversmith** [comment]
I am inclined to agree. I was planning on supporting Python2.7 until it became a pain technically. I ran into an issue where I was attempting to detect strings vs bytes for computing integrity checks and the python2.7's intermingling of strings and bytes has become a potential headache. So far I've seen 4 no votes and no yes votes. The python2.7 traffic was also low (and perhaps not human) last time I checked. pypistats.org seems to be down at the moment.

**Comment by william-silversmith** [comment]
Seems the unanimous opinion so far is 8:0 drop support. The people that are likely to be affected (if there are any) are likely to not be super active on social media or on this page. We are starting to accumulate a few reasons to drop support, so doing it sooner is better. How would we feel about dropping support at the end of September? I feel like if someone is actually developing Python2.7 code, end of August would force them to scramble.

**Comment by william-silversmith** [comment]
Of course, they could always just use an older version of CloudVolume...

**Comment by william-silversmith** [comment]
Nico pointed out that it's possible to use the `python_requires` argument in `setup.py`. This would prevent py27 users from downloading an incompatible release. With this technique in hand, we can drop py27 support in the next release without compromising backwards compatibility with py27 users.

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by william-silversmith** [comment]
Updated policy document: https://twitter.com/thundercloudvol/status/1292912062662873089
