### ISSUE TITLE
Graphene get_leaves does not work with v1 API

### ISSUE THREAD

**Issue by ceesem** [seung-lab/cloud-volume#384]
The `CloudVolumeGraphene.get_leaves` function hasn't been updated to the v1 pychunkedgraph API. This prevents `cv.download` from working on a v1 server when specific segmentation ids are specified.

**Comment by william-silversmith** [comment]
@sdorkenw @akhileshh what would be the right call?

**Comment by akhileshh** [comment]
`/segmentation/api/v1/table/<dataset_id>/node/<root_id>/leaves`

**Comment by william-silversmith** [comment]
Man, the placement of "table" is really confusing to me.

**Comment by akhileshh** [comment]
yeah not sure why that part wasn't changed from legacy to v1, maybe in the next api version
