### ISSUE TITLE
ModuleNotFoundError: No module named 'crc32c._crc32c_cffi'

### ISSUE THREAD

**Issue by perlman** [seung-lab/cloud-volume#385]
I am trying to install in a clean python 3.8 environment on OS X and get the following when I try to import cloud-volume:

```
>>> from cloudvolume import CloudVolume
Traceback (most recent call last):
  File "/Users/eric/nobackup/testenv/lib/python3.8/site-packages/crc32c/__init__.py", line 25, in <module>
    from crc32c import cffi as _crc32c
  File "/Users/eric/nobackup/testenv/lib/python3.8/site-packages/crc32c/cffi.py", line 20, in <module>
    import crc32c._crc32c_cffi
ModuleNotFoundError: No module named 'crc32c._crc32c_cffi'
```

I have tried some simple things, like the force installation of crc32c, to no effect.

**Comment by william-silversmith** [comment]
try force updating cloud-files and see if the problem persists

**Comment by perlman** [comment]
`pip install --upgrade cloud-files --force`

Same error on CloudVolume import.

Should I try master from github of cloud-files?

**Comment by william-silversmith** [comment]
I think what's happening is `google-crc32c` is conflicting with the `crc32c` library. One way to fix this is to just use Google's. Also there's a bug in their library. :P 

```   # If available, default to CFFI Implementation, otherwise, use pure python.
    try:
        from crc32c import cffi as _crc32c
        implementation = "cffi"
    except ImportError:
        from crc32c import python as _crc32c
>       warnings.warn(RuntimeWarning, "_SLOW_CRC32C_WARNING",)
E       TypeError: category must be a Warning subclass, not 'str'```

**Comment by william-silversmith** [comment]
https://github.com/ICRAR/crc32c
https://github.com/googleapis/python-crc32c

**Comment by william-silversmith** [comment]
Actually, it's even simpler... if I fix the bug, everything works.

```    
warnings.warn("_SLOW_CRC32C_WARNING", RuntimeWarning)
```

**Comment by william-silversmith** [comment]
Looks like these bugs are fixed 16 days ago in google-crc32c version 1.0.0. I can just pin the version to the fixed one.

**Comment by william-silversmith** [comment]
Try upgrading cloudfiles again and see if that fixes it for you.

**Comment by perlman** [comment]
LGTM!

Thanks William!
