### ISSUE TITLE
Invalid provenance file crashes task execution

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/cloud-volume#39]
The provenance file for `pinky40_v11/watershed` contained an additional `,` in line 11:
```code
 1 {
 2 	"sources": ["gs://neuroglancer/pinky40_v11/watershed/"],
 3 	"owners": ["ranl@princeton.edu", "ws9@princeton.edu"],
 4 	"processing": [{
 5 			"method": "imported from s3",
 6 			"by": "ws9@princeton.edu"
 7 		},
 8 		{
 9 			"method": "downsampling with countless",
10 			"by": "ws9@princeton.edu"
11 		},
12 	],
13 	"description": "Globally consistent watershed of the pinky40_v11 affinity."
14 }
```
which crashed the `task_execution.py`:
```python
Traceback (most recent call last):
  File "task_execution.py", line 32, in <module>
    execute()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "task_execution.py", line 19, in execute
    task.execute()
  File "/usr/local/lib/python2.7/dist-packages/neuroglancer/pipeline/tasks.py", line 286, in execute
    self._volume = CloudVolume(self.layer_path, self.mip, bounded=False)
  File "/usr/local/lib/python2.7/dist-packages/cloudvolume/cloudvolume.py", line 118, in __init__
    self.refresh_provenance()
  File "/usr/local/lib/python2.7/dist-packages/cloudvolume/cloudvolume.py", line 360, in refresh_provenance
    provfile = self._fetch_provenance()
  File "/usr/local/lib/python2.7/dist-packages/cloudvolume/cloudvolume.py", line 372, in _fetch_provenance
    provfile = json.loads(provfile)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Expected behavior:
Ignore corrupt provenance - the metadata is irrelevant for task execution.

**Comment by william-silversmith** [comment]
Thanks for reporting this Nico. Initially I was torn on this, since it encourages you to fix the provenance file, but it might make more sense to issue a warning.

**Comment by william-silversmith** [comment]
On second thought, the warning should be better, but this should be an irrecoverable error, and not only for motivational purposes. If we continue to allow processing, say using an empty version of the provenance file, it's likely that it will get committed and overwrite the extremely useful but ill formatted notes already existing.

Alternatively, we could ban editing the provenance file from CloudVolume in cases where the JSON is corrupted. What do you think @nkemnitz?

**Comment by william-silversmith** [comment]
I have another idea that I think I'm just going to go with. We should use json5 (http://json5.org/) instead to make it easier to write the provenance files and make them accept things like trailing commas.

**Comment by nkemnitz** [comment]
I am not sure if I understand: Why is the `provenance` file loaded? I thought that is a human-readable info file with contact information. For running tasks, I should only need the `info` file, right?

If it _is_ necessary to return an error message, then I would say it should go to the maintainers of the dataset/layer, not to the end-user :P

**Comment by william-silversmith** [comment]
You can also use the provenance file to detail how the dataset is being modified and, yes, send messages to maintainers. I'm including a way to override the provenance file in the constructor in another PR.

**Comment by nkemnitz** [comment]
The json5 solution is definitely a suitable workaround for the specific issue I had - thanks.
But I think it does not fix the underlying design flaw: If someone wants to work with the data alone (e.g. getting cutouts), then there is no need to download and parse the (possibly invalid) provenance file.

**Comment by william-silversmith** [comment]
No one has complained about this since this issue was opened, so I'm going to consider my solution a success. :) Only valid provenance files are written!
