### ISSUE TITLE
Semantic Structure Extraction of a Skeleton

### ISSUE THREAD

**Issue by jakobtroidl** [seung-lab/cloud-volume#414]
Hi Will,

I am curious if you know a smart or already existing way to extract the semantic structure of a skeleton created with kimimaro.
For example, I skeletonized this dendrite and want to know which vertices of the skeleton are part of the cell body or part of the spine. 

I appreciate your help! Thanks for this awesome tool ;) Best, Jakob 
 
![Skeleton](https://user-images.githubusercontent.com/29884213/95214781-8cc1f900-07f0-11eb-9f56-56a626240e2c.png)

**Comment by nicholasturner1** [comment]
This isn't a full solution, but you can get a surprising amount of the way to a good solution for spines if you enumerate the paths of the skeleton (https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/skeleton.py#L737), and count how many times each vertex shows up in a path. The vertices that are a part of a spine almost always participate in 1 path assuming that your skeletonization parameters are tuned for this.

**Comment by jakobtroidl** [comment]
The path function was exactly what I was looking for! Thank you so much ;)
