### ISSUE TITLE
Example code for generating "precomputed multi-resolution meshes" for neuroglancer

### ISSUE THREAD

**Issue by donglaiw** [seung-lab/cloud-volume#415]
I'm hoping to display an EM dataset on the `https://neuroglancer-demo.appspot.com/`. So far, I got it working for images and segmentation with `cloud-volume`, by converting and saving them into the precomputed format on the server.

But I'm stuck with the mesh generation. Wonder if there is any example code to turn my 3D segmentation volume into precomputed formats for meshes?

Thanks in advance!

**Comment by william-silversmith** [comment]
Hi donglaiw,

We don't currently support the generation of the multi-resolution meshes but we do support generating the single-resolution format. You can find instructions at https://github.com/seung-lab/igneous

Let me know if you need more assistance. ^_^

**Comment by donglaiw** [comment]
Thanks Will! You guys rock!!

One follow-up question, I just used the latest igneous to generate all the meshes, e.g., `12:0:0-256_0-256_0-100.gz` for seg_id=12. However, the current neuroglancer instance is looking for `12:0`. When I rename it to `12:0`, then it complains `Error retrieving chunk 12: SyntaxError: Unexpected token ] in JSON at position 0`.

**Comment by fcollman** [comment]
You need to generate manifests I think

**Comment by donglaiw** [comment]
Hello Forrest!! Below is the igneous code I used. It seems to have the manifest task there. Anything I miss?
Thanks!

```
        from taskqueue import LocalTaskQueue
        import igneous.task_creation as tc

        # Mesh on 8 cores, use True to use all cores
        sz2 = [256,256,100]
        cloudpath = 'file://'+Do
        tq = LocalTaskQueue(parallel=8)
        tasks = tc.create_meshing_tasks(cloudpath, mip=2, shape=sz2, mesh_dir='mesh')
        tq.insert(tasks)
        tasks = tc.create_mesh_manifest_tasks(cloudpath)
        tq.insert(tasks)
        tq.execute()
```

**Comment by donglaiw** [comment]
Thanks for the speedy response, Will! Yes, adding the `tq.execute()` fix it.

**Comment by donglaiw** [comment]
Hi Will:

I have a question of displaying these meshes with neuroglancer. I hacked it through last time, but somehow it's not working anymore..

- With the script above, I was able to generate ${id}:0:${x0}-${x1}\_${y0}-${y1}\_${z0}-${z1}.gz files under the `mesh/` folder: [folder link](https://rhoana.rc.fas.harvard.edu/ng/snemi_seg/mesh/) 
- on the neuroglancer instance, it displays the image/seg beautifully (thanks to cloud-volume :) ). But it gets an error when I click on a 3D seg, e.g., seg-id=13 here. The developer console says: `Error retrieving chunk 13: HttpError: Fetching "https://rhoana.rc.fas.harvard.edu/ng/snemi_seg/mesh/13:0" resulted in HTTP error 0: Network or CORS error.` [neuroglancer link](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B6e-9%2C%22m%22%5D%2C%22y%22:%5B6e-9%2C%22m%22%5D%2C%22z%22:%5B3e-8%2C%22m%22%5D%7D%2C%22position%22:%5B527.5%2C538.5%2C52.5%5D%2C%22crossSectionScale%22:2.2471402106139635%2C%22projectionOrientation%22:%5B0.12178236246109009%2C0.6502930521965027%2C0.7482568621635437%2C0.04898715019226074%5D%2C%22projectionScale%22:2405.0539553783274%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://https://rhoana.rc.fas.harvard.edu/ng/snemi_im%22%2C%22tab%22:%22source%22%2C%22name%22:%22snemi_im%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://https://rhoana.rc.fas.harvard.edu/ng/snemi_seg%22%2C%22tab%22:%22segments%22%2C%22segments%22:%5B%2210%22%2C%2213%22%5D%2C%22name%22:%22snemi_seg%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22layer%22:%22snemi_seg%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%2C%22partialViewport%22:%5B0%2C0%2C1%2C1%5D%7D)
- When I hacked it by `cp 13:0:0-256_0-256_0-100.gz 13:0`, it complains `Error retrieving chunk 13: SyntaxError: Unexpected token  in JSON at position 1`

Look forward to your help!
Thanks
Donglai

**Comment by william-silversmith** [comment]
Hi donglaiw,

That's extremely cool that you guys are finding this tool useful enough to integrate into your workflow. I think the problem is you need to configure the server behind `https://rhoana.rc.fas.harvard.edu/` to (at least for subdirectory `ng/snemi_seg/`) serve the HTTP header "Access-Control-Allow-Origin: *". There's a few other headers you might want to add while you're at it: 

https://github.com/seung-lab/cloud-volume/wiki/Setting-up-Google-Cloud-Storage#2-set-cors-headers

Let me know if that helps!
Will

**Comment by donglaiw** [comment]
Thanks for the prompt reply!

- I'm not sure if the problem is CORS. I tried [MOESIF chrome plugin](https://chrome.google.com/webstore/detail/moesif-origin-cors-change/digfbfaphojjndkpccljibejjbppifbc?hl=en-US), and it resolves the complaints for CORS.

- The remaining error is: `Error retrieving chunk 13: SyntaxError: Unexpected token in JSON at position 1`

**Comment by donglaiw** [comment]
Hi Willl:

- Thanks for the suggestion! The SNEMI example works beautifully now!!  [link](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B6e-9%2C%22m%22%5D%2C%22y%22:%5B6e-9%2C%22m%22%5D%2C%22z%22:%5B3e-8%2C%22m%22%5D%7D%2C%22position%22:%5B527.5%2C538.5%2C52.5%5D%2C%22crossSectionScale%22:2.2471402106139635%2C%22projectionOrientation%22:%5B0.1217823475599289%2C0.6502930521965027%2C0.7482568621635437%2C0.04898715019226074%5D%2C%22projectionScale%22:2405.0539553783274%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://https://rhoana.rc.fas.harvard.edu/ng/snemi_im%22%2C%22tab%22:%22source%22%2C%22name%22:%22snemi_im%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://https://rhoana.rc.fas.harvard.edu/ng/snemi_seg%22%2C%22tab%22:%22segments%22%2C%22segments%22:%5B%2210%22%2C%2213%22%5D%2C%22name%22:%22snemi_seg%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22layer%22:%22snemi_seg%22%2C%22visible%22:true%7D%2C%22layout%22:%224panel%22%2C%22partialViewport%22:%5B0%2C0%2C1%2C1%5D%7D)

- But when I use the exact same code on the same server with another dataset (more meshes), neuroglancer complains that when I click on a segment (e.g., 4175)`Error retrieving chunk 4175,0/4175:0:0-1024_0-1024_400-500: RangeError: Invalid typed array length: 1679709`. Wonder if you have any suggestion on how to debug it out?   [link](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B3e-8%2C%22m%22%5D%7D%2C%22position%22:%5B2023.5220947265625%2C819.42578125%2C235.739990234375%5D%2C%22crossSectionScale%22:2.8933306363460956%2C%22projectionOrientation%22:%5B0.36625033617019653%2C-0.6499547958374023%2C-0.4240226447582245%2C0.5134435296058655%5D%2C%22projectionScale%22:4096%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://https://rhoana.rc.fas.harvard.edu/ng/MitoEM-R%22%2C%22tab%22:%22source%22%2C%22name%22:%22MitoEM-R%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://https://rhoana.rc.fas.harvard.edu/ng/MitoEM-R_seg_train%22%2C%22tab%22:%22source%22%2C%22name%22:%22MitoEM-R_seg_train%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22layer%22:%22MitoEM-R_seg_train%22%2C%22visible%22:true%2C%22size%22:344%7D%2C%22layout%22:%224panel%22%2C%22partialViewport%22:%5B0%2C0%2C1%2C1%5D%7D)

Thanks
Donglai

**Comment by william-silversmith** [comment]
Cool! That's looking very nice. :) 

When I clicked on your second link, I still got a CORS error:

```
XHRGEThttps://rhoana.rc.fas.harvard.edu/ng/MitoEM-R_seg_train/mesh/4175:0
[HTTP/1.1 404 Not Found 166ms]

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://rhoana.rc.fas.harvard.edu/ng/MitoEM-R_seg_train/mesh/4175:0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Error retrieving chunk 4175: HttpError: Fetching "https://rhoana.rc.fas.harvard.edu/ng/MitoEM-R_seg_train/mesh/4175:0" resulted in HTTP error 0: Network or CORS error.
```

**Comment by donglaiw** [comment]
hmm... does the first link work for you? Both datasets are under the same folder on the server.

**Comment by donglaiw** [comment]
Hi Will:

- Wonder if you have any suggestion for me on what to look into for the `RangeError: Invalid typed array length: 1679709` error?

- Is there a way to visualize/check if the generated mesh file (.gz) is somehow corrupted? 

Thanks again for your help!
Donglai

**Comment by william-silversmith** [comment]
It looks to me like the file is not marked correctly with "Content-Encoding: gzip". When I downloaded it and renamed it to ".gz" I was able to unzip it.

**Comment by donglaiw** [comment]
Ah, found it! Thanks for the observation! The server/.htaccess isn't configured for .gz.. For cloud-volume, I hacked it by copy over the the `xx.gz` to `xx`.. If I do the same thing for the `mesh/`, it works now!!
