### ISSUE TITLE
CloudVolume with multiprocessing.Pool & sharding?

### ISSUE THREAD

**Issue by perlman** [seung-lab/cloud-volume#416]
Is there a "right way" to use a single CloudVolume with multiprocessing.Pool? I am getting errors relating to pickling when running CV on a sharded dataset.

Minimal example:
```python
import multiprocessing
from cloudvolume import CloudVolume

def get_point(vol, point):
    return (vol[point[0], point[1], point[2]])

def main():
    vol = CloudVolume('https://storage.googleapis.com/fafb-ffn1-20200412/segmentation')

    points = [[87122, 63787, 5436], [87813, 63760, 5393], [92360, 69062, 5940], [102097, 58224, 1608]]
    with multiprocessing.Pool(processes=4) as pool:
        futures = []
        for point in points:
            futures.append(pool.apply_async(get_point, args=[vol, point]))
        seg_ids = [f.get() for f in futures]

if __name__ == '__main__':
    main()
```

This generates the following exception:
```Python traceback
Traceback (most recent call last):
  File "test2.py", line 18, in <module>
    main()
  File "test2.py", line 15, in main
    seg_ids = [f.get() for f in futures]
  File "test2.py", line 15, in <listcomp>
    seg_ids = [f.get() for f in futures]
  File "/Users/eric/anaconda3/envs/fafb/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/Users/eric/anaconda3/envs/fafb/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/Users/eric/anaconda3/envs/fafb/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/eric/anaconda3/envs/fafb/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'ShardingSpecification.hash.<locals>.<lambda>'
```

Thanks, Eric.

**Comment by perlman** [comment]
I am able to rework the code using your [tastk-queue](https://github.com/seung-lab/python-task-queue/) and it works.

I'll dig in a bit to see what's different about how pathos calls `multiprocessing`.

**Comment by william-silversmith** [comment]
python-task-queue was specially designed to deal with pickling anonymous
classes and functions by using pathos, which under the hood calls dill. The
default picklers can't deal with them.

"dill is quite flexible, and allows arbitrary user defined classes and
functions to be serialized."

https://pypi.org/project/dill/

https://github.com/seung-lab/python-task-queue/pull/16/files

**Comment by perlman** [comment]
Thanks @william-silversmith.

Is there a particular reason the hashes for sharding need to be lambdas?  (This wasn't an issue before on non-sharded data).
