### ISSUE TITLE
Bbox Z-bounds are treated differently than X/Y-bounds when downloading 3d arrays.

### ISSUE THREAD

**Issue by ceesem** [seung-lab/cloud-volume#417]
When downloading from a cloudvolume using a Bbox object, the first two elements are treated as inclusive while the third element is handled like standard python slicing. For example
```
cv = CloudVolume(my_cloudpath)
bounds = Bbox([100, 100, 100],
              [200, 200, 200] )
image_array = cv.download(bounds)
```
would return an image array with the shape (100, 100, 99) and not (100,100,100). This difference in behavior is not particularly intuitive, or at the very least makes arbitrary assumptions about data anisotropy.

**Comment by william-silversmith** [comment]
That's prettyyyyy weird. I'll look into it.

**Comment by ceesem** [comment]
As you say, it would be pretty weird so I sanity checked myself. All of the components are being handled the same, it was my own mental handling of the anisotropy that made the results a surprise. It's more that to get 5 sections, it is weirder to specify x+6 as the top bound, but consistent across dimensions.
