### ISSUE TITLE
Make CloudVolume's at arbitrary depths in directory structure

### ISSUE THREAD

**Issue by macrintr** [seung-lab/cloud-volume#42]
For some applications, we might have layers that are directly linked (e.g. an image and some pixel-wise mask for that image). What about allowing nested CloudVolumes by extending the depth at which a CloudVolume path can extend? For example, `gs://neuroglancer/pinky40_alignment/test/mask`.

Would start with updating this regex. https://github.com/seung-lab/cloud-volume/blob/b641298115903fd7c31fb2e193b2a5a13aca8114/cloudvolume/cloudvolume.py#L184

**Comment by william-silversmith** [comment]
I'm not entirely sure that works with neuroglancer (never tested), but I
have a PR to do that for filesystem access.

**Comment by william-silversmith** [comment]
https://github.com/seung-lab/cloud-volume/pull/38

**Comment by william-silversmith** [comment]
Merged.
