### ISSUE TITLE
pulling thousands of 2D brain slices

### ISSUE THREAD

**Issue by johnduva** [seung-lab/cloud-volume#425]
I’m trying pull thousands of two-dimensional brain image slices using CloudVolume, but it seems to be a prohibitively slow process. After eight hours, only 100 slices have been completed. Is there anyway of speeding them up? 

_Note: The Bbox is [0, 0, 0],[33792, 25600, 13312]._

**Code:**
```
dir = "s3://private/directory"
vol = CloudVolume(dir, parallel=True, fill_missing=True)

for i in range(13312):
    image = vol[:, :, i]
    pkl.dump(image, open("pickles/image"+str(i)+".pkl", "wb"))
```

**Comment by william-silversmith** [comment]
Hi John, what is the chunk size of the dataset? Larger chunks are faster. Pickling can be a slow operation too. One potential way to speed things up is to download multiple z slices at once and then cut them out in memory before pickling.

**Comment by johnduva** [comment]
Hey William, the chunk size of the dataset is **[132, 100, 52]** according to the output of `print(sess.cv.info)`. 

Hmm, could you give me an example of what the code might look like? Also, how many slices should be in a chunk you think?

**Comment by william-silversmith** [comment]
Thanks for the info! Your chunks are 52 slices thick, but you're downloading them one slice at a time, making your overall downloads occur 51x more than you need them to. Here are two options:

Option 1) FAST, MEMORY INTENSIVE: Download them 52 slices at a time and then write out the files by cutting them out of memory.

```python
vol = CloudVolume(dir, parallel=True, fill_missing=True)

for z in range(vol.voxel_offset.z, vol.voxel_offset.z + vol.shape[2] + 1, vol.chunk_size.z):
    image = vol[:, :, z:z+vol.chunk_size.z]
    for j in range(vol.chunk_size.z):
        image_slice = image[:,:,j]
        pkl.dump(image, open("pickles/image"+str(z+j)+".pkl", "wb"))
```

Option 2) MEDIUM, DISK INTENSIVE: Do what you're doing but cache the last Z chunks on disk

```python
dir = "s3://private/directory"
vol = CloudVolume(dir, parallel=True, fill_missing=True, cache=True)

for z in range(vol.voxel_offset.z, vol.voxel_offset.z + vol.shape[2] + 1):
    if z % vol.chunk_size.z == 0:
        vol.cache.flush()
    image = vol[:, :, z]
    pkl.dump(image, open("pickles/image"+str(z)+".pkl", "wb"))
```

**Comment by johnduva** [comment]
Thanks so much William!
Just to make sure though, that last line in Option 1 is supposed to be `pkl.dump(image_slice` right?

**Comment by johnduva** [comment]
Hey William,
I tried running the code and here are my findings:

Caching the last z chunks, as proposed in Option 2, does not noticeably improve program speed. It saved about 2 second per loop for an average loop time of 37 seconds to get through each z. 

For the first option, I'm not sure if there is a bug or not but I let my cpu run it for a few hours and it never got past `image = vol[:, :, z:z+vol.chunk_size.z]`. I then opened up a separate cell to run a unit test of just `image = vol[:, :, 0: 52]` and the same thing happened.

Interested to hear your thoughts,
John

**Comment by william-silversmith** [comment]
The speed limitation for method 2 is probably due to decompression. If the compression method was gzip, you can get some minor acceleration (~15%?) on EM images and large acceleration (~400%?) on segmentation images with `CFLAGS="$CFLAGS -fPIC" pip install deflate` which CV will automatically use. 

The option 1 unit test is attempting to allocate at least 42 GB of memory. Do you have a machine big enough for that? You can try using fewer than 52 slices to reduce the amount of duplicate work. 13 slices might be a good number (11.2 GB RAM).

**Comment by johnduva** [comment]
Thanks for your help, William. I tried a few of these things but what ended up helping the most was increasing the mip (I used mip=3) and that sped things up a lot. I appreciate your time and guidance.
Best,
John
