### ISSUE TITLE
RGB channel support in CloudVolume?

### ISSUE THREAD

**Issue by manoaman** [seung-lab/cloud-volume#431]
Hi Will,

Does CloudVolume support RGB channel for uploading data?  Or does the tiff stack need to be in gray scale?  Also, is 32 bit image supported?  

Thank you!
-m

```
      (width, height) = image.size
      array = np.array(list(image.getdata()), dtype=np.uint16, order='F')
      array = array.reshape((1, height, width)).T
      vol[:, :, z] = array
```

**Comment by william-silversmith** [comment]
Hi m,

It's a rarely used feature, but in theory CloudVolume does support 3 channel data. You can set "num_channels" to 3 in the info file and from that point on it should work. See if it works for you!

Will

**Comment by manoaman** [comment]
Yes, that is exactly what I tried and I was wondering if I had to reshape an array differently or set dtype=np.uint32 instead.  None of the approach worked so far.  Could I be missing something else?

```
Could not convert data to an integer.
cannot reshape array of size 437760 into shape (1,320,456)
```

Thank you,
-m

**Comment by william-silversmith** [comment]
Hi m,

`437760 / 456 / 320 = 3` which means that the image should be reshaped to (3, height, width). Give that a shot and let me know!

Will

**Comment by manoaman** [comment]
I think I got it working with this Will!  Thanks, I think it had to do with reshaping numpy array.

```
      array = np.array(list(image.getdata()), dtype=np.uint16, order='F')

      array = array.reshape((3, 1, height, width)).T
      vol[:, :, z] = array
      image.close()
```

Although, I always get confused sometimes why I get this error.
```
Could not convert data to an integer.

        Requested cutout not contained within dataset bounds.

        Cloudpath: file:///precomputed
        Requested: Bbox([0, 0, 24],[456, 320, 25], dtype=int32)
        Bounds: Bbox([0, 0, 0],[456, 320, 24], dtype=int32)
        Mip: 0
        Resolution: [25000 25000 25000]

        Set bounded=False to disable this warning.
```

Correct me if I'm wrong.  I think this error occurs when a stack of tiffs are in odd numbers.  i.e.) In this example I had 25 tiffs  I suppose it's always good to have a collection of stacks in even number?

Thank you,
-m

**Comment by manoaman** [comment]
Hi @william-silversmith ,

I'm trying to load RGB channel images on Neuroglancer and it appears image appears flipped on both horizontally and vertically.  And this image supposed to be blue but does not appear as expected.  Could I be reshaping numpy array incorrectly with the latest CloudVolume code?   Thanks, -m

```
array = np.array(list(image.getdata()), dtype=np.uint8, order='F')

array = array.reshape((3, 1, height, width)).T
vol[:, :, z, :] = array
```

<img width="1780" alt="Screen Shot 2021-05-18 at 6 18 27 PM" src="https://user-images.githubusercontent.com/47464840/119066566-e7315380-b994-11eb-8ee7-81f56bb9a992.png">

**Comment by william-silversmith** [comment]
Hi m,

Sorry I missed your last message! I hope you were able to figure it out. The bounds start at zero, so if you were numbering from 1, that could have triggered the bounds error.

The kind of error you are currently experiencing is one of the most annoying to debug unfortunately... It means that the data are being incorrectly transposed one or more times throughout the sequence from image loading to CloudVolume upload. 

The image data could be written in ABGR or RGBA order. It can help to look at the first four entries of `list(image.getdata())` to figure that out. Unfortunately, I forget which one Neuroglancer likes.. You can try flipping the channels and see if that helps. If that doesn't go anywhere, are you sure the image you're loading should be read as `F` order? You can try `C` order, flipping the shape order, turning on and off the `.T`.

**Comment by william-silversmith** [comment]
Rather, I should have written `RGB` vs `BGR` since there are only three channels.

**Comment by manoaman** [comment]
Hi Will, no worries at all and thank you for your continued help!!

It turns out that Neuroglancer can change the mapping of RGB channels with Shader's control so I'm doubting shaping the numpy array seems more relevant to the issue.  So far I haven't succeeded yet.

Two questions came up to me.

First, looking at the image, what I see is contiguous RGB tuples.  In other words, `[(0,0,0),(0,0,0),.........]` is what I see from looking at the raw data.  Interestingly, gray scale image which I tried for other sample cases were `[0,0,0,.....]` and `F` order seemed to work.  Although, shouldn't I be using both `C` orders for both of these cases?  I'm not quite sure if I've been using the correct orders at this point.

Second question, what does CloudVolume expect of the numpy array to be structured on uploading?  Should it be in the order of `[width, height, z, rgb]` ?  Typically with grayscale images, I transposed an array into `[width, height, z]` by `.T`.  Where would RGB values fit in to this?  Could it be `[width, height, rgb, z]`

```
      array = array.reshape((3, 1, height, width)).T
       vol[:, :, z, :] = array
```

Thanks again for your help!
-m

**Comment by manoaman** [comment]
Should I be swapping z and RGB before upload to CloudVolume?

```
array = array.reshape((3, 1, height, width)).T
array[:, :, [3, 2]] = array[:, :, [2, 3]]
vol[:, :, :, z] = array
```

**Comment by william-silversmith** [comment]
Hi m,

CloudVolume/Neuroglancer expects the final result as F-order X,Y,Z,RGB I believe. However, if you have it in C order, it'll be automatically converted to F order. 

If your data are structured as RGB triples, yea, it does seem like C order is more likely. However, it could also be neither... It's possible you might need to invoke `np.moveaxis` if the shape doesn't seem right.

Hope that's helpful. I've spent many hours debugging similar issues, it only gets slightly easier with practice unfortunately.

**Comment by manoaman** [comment]
Agh, it is really a tough task debugging n-darray and reshaping an image.  I'm separating an issue by looking at a smaller sample image to see if reshaping a numpy array is working as expected.

Suppose I have an image with a RGB channel with a shape in (784,3), and reshaping it to (28, 28, 1, 3).  This is how the change appears.

Shouldn't this match to F-order X,Y,Z,RGB format which CloudVolume expects?

```
array = array.reshape((width, height, 1, 3))
print(array.shape)
print(array)
```
```
(784, 3)
[[  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  1   1   1]
 [  1   1   1]
 [  0   0   0]
 [  0   0   0]
 [  0   0   0]
 [  1   1   1]
 [  1   1   1]


 ---

  ------------
(28, 28, 1, 3)
[[[[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  1   1   1]]

  [[  1   1   1]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  0   0   0]]

  [[  1   1   1]]

  [[  1   1   1]]

  [[  0   0   0]]


  ---

```

**Comment by william-silversmith** [comment]
Hey m, 

It's pretty tricky. It looks okay at a glance. If you can share an image file, I might be able to help more.

**Comment by manoaman** [comment]
Hi @william-silversmith , that would be great.  Do you have an email address where I can send my link to the shared Google Drive of RAW files and my running code?  Thanks!

**Comment by william-silversmith** [comment]
Yes you can write me at william.silversmith@princeton.edu

**Comment by manoaman** [comment]
Thank you Will, just shared with your account!

**Comment by william-silversmith** [comment]
Resolved over email and updated the wiki. https://github.com/seung-lab/cloud-volume/wiki/Example-Single-Machine-Dataset-Upload

**Comment by spikeliu** [comment]
I wonder if cloud-volume is able to work on dataset with more than 3 channels. Say I have a spatial transcriptomics with thousands of data channels, each of which can be seen as a single gene expression heatmap, if I want to upload it, to use `vol[:,:,z] = vol_local` may require too much memory when the size of the dummy figure is very large, but if I use `vol[:,:,z, channel_id] = vol_local_single_channel`, the python code won't generate precomputed binary chunks. 
I can think of a way to deal with this, which is to slice the dummy figure on the x-y plate, like` vol[start_x:end_x, start_y:end_y, z] = vol_local_fit_this_chunk`, but one has to take care of the aligned writes themselves.

**Comment by william-silversmith** [comment]
For more than 3-channel data, CloudVolume isn't designed to handle that case efficiently right now. Internally, the data would have to be chunked to ensure that each bit downloaded wasn't too big. CloudVolume's main job is to follow the Precomputed format.

If you're working with that kind of data, https://github.com/zarr-developers/zarr-python/ might be a good option. It seems neuroglancer might even be able to display it (not sure about N-dimensions though).

https://github.com/google/neuroglancer

Let me know if that works for you, otherwise we can discuss further. It's certainly a great and interesting use case.

**Comment by spikeliu** [comment]
Some updates: One of my colleagues has tried something as described in https://github.com/google/neuroglancer/issues/240#issuecomment-901661050, it seems zarr format can take good care of chunking data (as long as the channel dim is not split, neuroglancer can display it), but for now it does not support multi-resolution data. Also, dense data may take too much disk space when there are thousands of single genes to store. I think I will look more into the "[collections of xxxx annotations](https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md)" from the precomputed format because it supports to store sparse dataset and can display it in both 2D and 3D windows, though there seems to be no existing simple APIs to create it. I can only find some useful information in https://github.com/google/neuroglancer/issues/227.
