### ISSUE TITLE
option to save files without `.gz` extension

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/cloud-volume#432]
currently, cloud-volume saves local precomputed files with an extension `.gz`
while neuroglancer access files without extension, it would help the visualization of local precomputed volume by removing the extension. This could be added as a feature.

**Comment by william-silversmith** [comment]
Hi Jingpeng, there's no way to note the metadata outside of the header information in the file if we do away with the extension. To help with visualization, there are a few tips and tricks you can use.

1) Use the cloudvolume built-in server `cv.viewer()` which will automatically strip `.gz`
2) Use nginx as a static file server with the gzip extension installed: http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html

**Comment by jingpengw** [comment]
I think gzip has some magic bits to start with. 
anyway, we have some other issues accessing the files.
Unfortunately, the web server is out of our control..

**Comment by william-silversmith** [comment]
It does, but we also support uncompressed files. If we look only at the magic bits, there's a 1 in 2^16 chance (assuming random bits) of accidentally identifying a file as gzip.

**Comment by william-silversmith** [comment]
Also, even if CloudVolume changes to write the files without the gzip extension, neuroglancer still would need to be modified to read the header instead of looking at only the http "Content-Encoding" header.

**Comment by jingpengw** [comment]
yes, I realized that as well. The web server needs to provide this
information. Or neuroglancer have to be smart enough to check the magic
bits.

**Comment by jingpengw** [comment]
it turns out that our web server can not even list the chunk files since the file number exceeds the maximum threshold...
This might be a common problem for local storage and serving. This feature is not necessary then.

**Comment by william-silversmith** [comment]
What threshold did they exceed? For `ls`? Try using `find .` it works in an online fashion.

**Comment by jingpengw** [comment]
I am not sure about the exact file number threshold. I am not the manager
of the server.
