### ISSUE TITLE
Error initialising CloudVolume: invalid start byte

### ISSUE THREAD

**Issue by schlegelp** [seung-lab/cloud-volume#444]
Hi! I'm trying to open `precomputed://gs://fafb-ffn1-20190805/tissue_mask_argmax` but run into an error:

```Python
>>>  tissue_vol = CloudVolume('precomputed://gs://fafb-ffn1-20190805/tissue_mask_argmax', mip=5, fill_missing=True)
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-93-4d4e982b13f4> in <module>
----> 1 tissue_vol = CloudVolume('precomputed://gs://fafb-ffn1-20190805/tissue_mask_argmax', mip=5, fill_missing=False)

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/cloudvolume.py in __new__(cls, cloudpath, mip, bounded, autocrop, fill_missing, cache, compress_cache, cdn_cache, progress, info, provenance, compress, compress_level, non_aligned_writes, parallel, delete_black_uploads, background_color, green_threads, use_https, max_redirects, mesh_dir, skel_dir, agglomerate, secrets)
    205     path = strict_extract(cloudpath)
    206     if path.format in REGISTERED_PLUGINS:
--> 207       return REGISTERED_PLUGINS[path.format](**kwargs)
    208     else:
    209       raise UnsupportedFormatError(

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/__init__.py in create_precomputed(cloudpath, mip, bounded, autocrop, fill_missing, cache, compress_cache, cdn_cache, progress, info, provenance, compress, compress_level, non_aligned_writes, parallel, delete_black_uploads, background_color, green_threads, use_https, max_redirects, mesh_dir, skel_dir, secrets, **kwargs)
     43       info=info, provenance=provenance,
     44       max_redirects=max_redirects,
---> 45       use_https=use_https # for parsing redirects
     46     )
     47 

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/metadata.py in __init__(self, cloudpath, config, cache, info, provenance, max_redirects, use_https)
     53 
     54     if info is None:
---> 55       self.refresh_info(max_redirects=max_redirects)
     56       if self.cache and self.cache.enabled:
     57         self.cache.check_info_validity()

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/metadata.py in refresh_info(self, max_redirects, force_fetch)
    177         return self.info
    178 
--> 179     self.info = self.redirectable_fetch_info(max_redirects)
    180 
    181     if self.cache:

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/metadata.py in redirectable_fetch_info(self, max_redirects)
    238 
    239     for _ in range(max_redirects):
--> 240       info = self.fetch_info()
    241 
    242       if 'redirect' not in info or not info['redirect']:

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/metadata.py in fetch_info(self)
    195     Returns: dict
    196     """
--> 197     info = CloudFiles(self.cloudpath, secrets=self.config.secrets).get_json('info')
    198 
    199     if info is None:

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudfiles/cloudfiles.py in get_json(self, paths, total)
    238 
    239   def _progress_description(self, prefix):
--> 240     if isinstance(self.progress, STRING_TYPES):
    241       return prefix + ' ' + self.progress
    242     else:

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudfiles/cloudfiles.py in <listcomp>(.0)
    238 
    239   def _progress_description(self, prefix):
--> 240     if isinstance(self.progress, STRING_TYPES):
    241       return prefix + ' ' + self.progress
    242     else:

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudfiles/cloudfiles.py in decode(content)
    236     if self._path.protocol == 'mem':
    237       self.num_threads = 0
--> 238 
    239   def _progress_description(self, prefix):
    240     if isinstance(self.progress, STRING_TYPES):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

I can't entirely rule out that something about the bucket/permissions changed but this used to work in the past (last tried ~1 year ago). Any pointers very welcome! :)

**Comment by schlegelp** [comment]
Confirmed that it still works with cloud volume `1.11.0`

**Comment by william-silversmith** [comment]
Hi Phil! I wasn't able to reproduce it on my end. A big change in CV is that we started using CloudFiles versus the old Storage system. Can you confirm you have the latest CloudFiles installed? `pip install cloud-files -U`

https://github.com/seung-lab/cloud-files

**Comment by schlegelp** [comment]
Thanks. I tried updating `cloud-volume` and `cloud-files` to their respective most recent versions. Error has changed:

```Python
---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudfiles/connectionpools.py in get_connection(self, secrets, endpoint)
     55       try:
---> 56         conn = self.pool.get(block=False)
     57         self.pool.task_done()

~/.pyenv/versions/3.7.5/lib/python3.7/queue.py in get(self, block, timeout)
    166                 if not self._qsize():
--> 167                     raise Empty
    168             elif timeout is None:

Empty: 

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-5-5a42c4c4e35c> in <module>
----> 1 tissue_vol = CloudVolume('precomputed://gs://fafb-ffn1-20190805/tissue_mask_argmax', mip=5, fill_missing=True)

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/cloudvolume.py in __new__(cls, cloudpath, mip, bounded, autocrop, fill_missing, cache, compress_cache, cdn_cache, progress, info, provenance, compress, compress_level, non_aligned_writes, parallel, delete_black_uploads, background_color, green_threads, use_https, max_redirects, mesh_dir, skel_dir, agglomerate, secrets)
    205     path = strict_extract(cloudpath)
    206     if path.format in REGISTERED_PLUGINS:
--> 207       return REGISTERED_PLUGINS[path.format](**kwargs)
    208     else:
    209       raise UnsupportedFormatError(

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/__init__.py in create_precomputed(cloudpath, mip, bounded, autocrop, fill_missing, cache, compress_cache, cdn_cache, progress, info, provenance, compress, compress_level, non_aligned_writes, parallel, delete_black_uploads, background_color, green_threads, use_https, max_redirects, mesh_dir, skel_dir, secrets, **kwargs)
     43       info=info, provenance=provenance,
     44       max_redirects=max_redirects,
---> 45       use_https=use_https # for parsing redirects
     46     )
     47 

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/metadata.py in __init__(self, cloudpath, config, cache, info, provenance, max_redirects, use_https)
     53 
     54     if info is None:
---> 55       self.refresh_info(max_redirects=max_redirects)
     56       if self.cache and self.cache.enabled:
     57         self.cache.check_info_validity()

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/metadata.py in refresh_info(self, max_redirects, force_fetch)
    177         return self.info
    178 
--> 179     self.info = self.redirectable_fetch_info(max_redirects)
    180 
    181     if self.cache:

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/metadata.py in redirectable_fetch_info(self, max_redirects)
    238 
    239     for _ in range(max_redirects):
--> 240       info = self.fetch_info()
    241 
    242       if 'redirect' not in info or not info['redirect']:

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudvolume/datasource/precomputed/metadata.py in fetch_info(self)
    195     Returns: dict
    196     """
--> 197     info = CloudFiles(self.cloudpath, secrets=self.config.secrets).get_json('info')
    198 
    199     if info is None:

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudfiles/cloudfiles.py in get_json(self, paths, total)
    390 
    391     if not multiple_return and contents and contents[0]['error']:
--> 392       raise contents[0]['error']
    393 
    394     contents = [ decode(content) for content in contents ]

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudfiles/cloudfiles.py in download(path)
    310       server_hash_type = None
    311       try:
--> 312         with self._get_connection() as conn:
    313           content, encoding, server_hash, server_hash_type = conn.get_file(path, start=start, end=end)
    314 

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudfiles/cloudfiles.py in _get_connection(self)
    246     return self._interface_cls(
    247       self._path,
--> 248       secrets=self.secrets,
    249     )
    250 

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudfiles/interfaces.py in __init__(self, path, secrets)
    361     global GC_POOL
    362     self._path = path
--> 363     self._bucket = GC_POOL[path.bucket].get_connection(secrets, None)
    364 
    365   def get_path_to_file(self, file_path):

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudfiles/connectionpools.py in get_connection(self, secrets, endpoint)
     57         self.pool.task_done()
     58       except queue.Empty:
---> 59         conn = self._create_connection(secrets, endpoint)
     60       finally:
     61         self.outstanding += 1

~/.local/lib/python3.7/site-packages/tenacity/__init__.py in wrapped_f(*args, **kw)
    327         @_utils.wraps(f)
    328         def wrapped_f(*args, **kw):
--> 329             return self.call(f, *args, **kw)
    330 
    331         def retry_with(*args, **kwargs):

~/.local/lib/python3.7/site-packages/tenacity/__init__.py in call(self, fn, *args, **kwargs)
    407             retry_object=self, fn=fn, args=args, kwargs=kwargs)
    408         while True:
--> 409             do = self.iter(retry_state=retry_state)
    410             if isinstance(do, DoAttempt):
    411                 try:

~/.local/lib/python3.7/site-packages/tenacity/__init__.py in iter(self, retry_state)
    366             retry_exc = self.retry_error_cls(fut)
    367             if self.reraise:
--> 368                 raise retry_exc.reraise()
    369             six.raise_from(retry_exc, fut.exception())
    370 

~/.local/lib/python3.7/site-packages/tenacity/__init__.py in reraise(self)
    184     def reraise(self):
    185         if self.last_attempt.failed:
--> 186             raise self.last_attempt.result()
    187         raise self
    188 

~/.pyenv/versions/3.7.5/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    426                 raise CancelledError()
    427             elif self._state == FINISHED:
--> 428                 return self.__get_result()
    429 
    430             self._condition.wait(timeout)

~/.pyenv/versions/3.7.5/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

~/.local/lib/python3.7/site-packages/tenacity/__init__.py in call(self, fn, *args, **kwargs)
    410             if isinstance(do, DoAttempt):
    411                 try:
--> 412                     result = fn(*args, **kwargs)
    413                 except BaseException:
    414                     retry_state.set_exception(sys.exc_info())

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cloudfiles/connectionpools.py in _create_connection(self, secrets, endpoint)
    155     client = Client(
    156       credentials=secrets,
--> 157       project=self.project,
    158     )
    159 

~/.pyenv/versions/3.7.5/lib/python3.7/site-packages/google/cloud/storage/client.py in __init__(self, project, credentials, _http, client_info, client_options)
    123             credentials=credentials,
    124             client_options=client_options,
--> 125             _http=_http,
    126         )
    127 

TypeError: __init__() got an unexpected keyword argument 'client_options'
```

Looks like an issue with the version of a dependency to me. This is with Python 3.7.5 and here's a snapshot of installed packages:

<details>
<summary><pre>pip3 list</pre></summary>
<br>
<pre>
Package                       Version                 Location
----------------------------- ----------------------- -------------------------------------------------------------------------------------------
-lotly                        4.6.0
addict                        2.3.0
adjustText                    0.7.3
alabaster                     0.7.12
alignment                     1.0.10
alphashape                    1.0.2
analytics-python              1.2.9
anyio                         2.0.2
appdirs                       1.4.4
appnope                       0.1.0
apptools                      4.5.0
arrow                         0.15.5
asciitree                     0.3.3
attrs                         19.3.0
Babel                         2.8.0
backcall                      0.1.0
backports-abc                 0.5
binaryornot                   0.4.4
bleach                        3.1.0
blessings                     1.7
bokeh                         1.4.0
boto3                         1.14.4
botocore                      1.17.4
brainmappy                    0.2.6                   /Users/philipps/Google Drive/Cloudbox/Github/brainmappy
Brotli                        1.0.7
brotlipy                      0.7.0
cached-property               1.5.2
cachetools                    4.0.0
certifi                       2019.11.28
cffi                          1.14.0
chardet                       3.0.4
Click                         7.0
click-log                     0.3.2
cloud-files                   1.24.1
cloud-volume                  3.8.0
colorama                      0.4.3
colorcet                      2.0.2
compressed-segmentation       2.0.1
configobj                     5.0.6
connectcatmaid                0.0.1                   /Users/philipps/Google Drive/Cloudbox/Python/connect_catmaid
cookiecutter                  1.7.0
crc32c                        2.0.1
cryptography                  2.9.2
curlify                       2.2.1
cycler                        0.10.0
Cython                        0.29.21
dataclasses                   0.6
decorator                     4.4.1
deflate                       0.3.0
defusedxml                    0.6.0
descartes                     1.1.0
dill                          0.3.1.1
diskcache                     4.1.0
docutils                      0.15.2
DracoPy                       0.0.15
dynetx                        0.2.2
edit-distance                 1.0.4
entrypoints                   0.3
envisage                      4.9.2
fafbseg                       1.1.0                   /Users/philipps/Google Drive/Cloudbox/Github/fafbseg-py
fastcluster                   1.1.26
fasteners                     0.15
fastremap                     1.10.2
feather-format                0.4.0
flybrains                     0.1.0                   /Users/philipps/Google Drive/Cloudbox/Github/navis-flybrains
fpzip                         1.1.4
freetype-py                   2.1.0.post1
fury                          0.6.0
future                        0.18.2
fuzzy-match                   0.0.1
fuzzywuzzy                    0.18.0
gevent                        20.6.2
gitdb                         4.0.5
GitPython                     3.1.11
google-api-core               1.22.0
google-api-python-client      1.10.0
google-apitools               0.5.31
google-auth                   1.20.0
google-auth-httplib2          0.0.4
google-auth-oauthlib          0.4.1
google-cloud-core             1.3.0
google-cloud-storage          1.35.1
google-crc32c                 1.0.0
google-resumable-media        1.2.0
googleapis-common-protos      1.51.0
greenlet                      0.4.16
gsheets                       0.4.1
gspread                       3.1.0
h5py                          3.1.0
hemipy                        0.1.0                   /Users/philipps/Google Drive/Cloudbox/Github/2020hemibrain/hemibrain_analyses/Python/hemipy
holoviews                     1.12.7
httplib2                      0.17.0
hvplot                        0.5.2
idna                          2.7
imageio                       2.6.1
imagesize                     1.2.0
importlib-metadata            1.6.1
infinite                      0.1
inflection                    0.5.0
iniconfig                     1.1.1
inquirer                      2.6.3
ipydatawidgets                4.0.1
ipykernel                     5.1.3
ipython                       7.15.0
ipython-genutils              0.2.0
ipywidgets                    7.5.1
jedi                          0.15.1
Jinja2                        2.10.3
jinja2-time                   0.2.0
jmespath                      0.10.0
joblib                        0.14.1
JPype1                        1.2.0
json5                         0.5.1
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                6.1.11
jupyter-console               6.1.0
jupyter-core                  4.6.1
jupyter-server                1.2.1
jupyterlab                    3.0.3
jupyterlab-hdf                0.5.1
jupyterlab-server             2.0.0
K3D                           2.7.4
keyring                       21.1.0
kiwisolver                    1.1.0
lacroix                       0.0.3
leidenalg                     0.8.2
line-profiler                 3.0.2
llvmlite                      0.35.0
Markdown                      3.2.2
MarkupSafe                    1.1.1
matplotlib                    3.2.2
mayavi                        4.7.1
meshio                        4.0.16
meshparty                     1.8.0
mistune                       0.8.4
mock                          3.0.5
monotonic                     1.5
more-itertools                8.4.0
morphops                      0.1.11
mpi4py                        3.0.3
msgpack                       1.0.0
multiprocess                  0.70.9
multiwrapper                  0.1.1
navis                         0.3.2                   /Users/philipps/Google Drive/Cloudbox/Github/navis
nbclassic                     0.2.5
nbconvert                     5.6.1
nbformat                      4.4.0
nbsphinx                      0.5.0
ncollpyde                     0.14.0
ndlib                         5.0.0
netdispatch                   0.0.3
networkx                      2.5
neuprint-python               0.4.5+13.g93a5256.dirty /Users/philipps/Google Drive/Cloudbox/Github/neuprint-python
neuroglancer                  2.8
NEURON                        7.8.1.1
notebook                      6.0.2
numba                         0.52.0
numexpr                       2.7.2
numpy                         1.19.5
numpydoc                      0.9.2
oauth2client                  4.1.3
oauthlib                      3.1.0
open3d                        0.12.0
openpyscad                    0.4.0
orjson                        3.4.8
p-tqdm                        1.3.3
packaging                     20.4
pandas                        1.0.4
pandocfilters                 1.4.2
panel                         0.7.0
param                         1.9.2
parso                         0.5.1
pathos                        0.2.5
patsy                         0.5.1
pexpect                       4.7.0
pickleshare                   0.7.5
Pillow                        7.2.0
Pint                          0.11
pip                           20.2.4
pkginfo                       1.5.0.1
plotly                        4.14.1
pluggy                        0.13.1
plyfile                       0.7.2
polyscope                     0.1.2
posix-ipc                     1.0.4
pox                           0.2.7
poyo                          0.5.0
ppft                          1.6.6.1
prometheus-client             0.7.1
prompt-toolkit                2.0.10
protobuf                      3.12.4
psutil                        5.4.3
ptyprocess                    0.6.0
py                            1.8.2
py4j                          0.10.9.1
pyarrow                       0.15.1
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pyclustertend                 1.4.9
pycparser                     2.20
pyct                          0.4.6
pyface                        6.1.2
pyglet                        1.4.10
Pygments                      2.5.2
pykdtree                      1.3.4
pylru                         1.2.0
pymaid                        0.111                   /Users/philipps/Google Drive/Cloudbox/Github/PyMaid
PyMCubes                      0.1.0
pymeshfix                     0.14.1
pynndescent                   0.5.1
pynrrd                        0.4.2
pyoctree                      0.2.10
PyOpenGL                      3.1.5
pyOpenSSL                     19.1.0
pyparsing                     2.4.5
pyperclip                     1.8.0
pypng                         0.0.20
PyQt5                         5.15.0
PyQt5-sip                     12.8.0
pyreadr                       0.3.6
pyrsistent                    0.15.6
pySankey2                     2.0.1
pysimdjson                    3.1.1
pytest                        6.2.2
python-catmaid                2.0.0
python-dateutil               2.8.0
python-editor                 1.0.4
python-igraph                 0.8.2
python-jsonschema-objects     0.3.12
python-Levenshtein            0.12.0
pytz                          2019.3
pyvista                       0.25.3
pyviz-comms                   0.7.2
PyWavelets                    1.1.1
PyYAML                        5.2
pyzmq                         18.1.1
qgrid                         1.1.1
qtconsole                     4.7.3
QtPy                          1.9.0
rdata                         0.2.2
readchar                      2.0.1
readme-renderer               24.0
requests                      2.24.0
requests-futures              1.0.0
requests-oauthlib             1.3.0
requests-toolbelt             0.9.1
retry                         0.9.2
retrying                      1.3.3
rfc3986                       1.4.0
rpy2                          3.3.2
rsa                           4.6
s3transfer                    0.3.3
scikit-image                  0.16.2
scikit-learn                  0.24.0
scipy                         1.6.0
scooby                        0.5.6
seaborn                       0.11.0
selenium                      3.141.0
Send2Trash                    1.5.0
setuptools                    51.1.0
Shapely                       1.6.4.post2
simplegeneric                 0.8.1
simplejpeg                    1.3.8
simplejson                    3.17.2
six                           1.14.0
skeletor                      0.2.10                  /Users/philipps/Google Drive/Cloudbox/Github/skeletor
sklearn                       0.0
smmap                         3.0.4
sniffio                       1.2.0
snowballstemmer               2.0.0
sockjs-tornado                1.0.7
Sphinx                        3.3.1
sphinx-autodoc-typehints      1.11.0
sphinx-bootstrap-theme        0.7.1
sphinx-materialdesign-theme   0.1.11
sphinxcontrib-applehelp       1.0.1
sphinxcontrib-devhelp         1.0.1
sphinxcontrib-htmlhelp        1.0.2
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.2
sphinxcontrib-serializinghtml 1.1.3
statsmodels                   0.11.1
tables                        3.6.1
tenacity                      6.2.0
terminado                     0.8.3
testpath                      0.4.4
texttable                     1.6.2
threadpoolctl                 2.1.0
tifffile                      2020.8.25
toml                          0.10.2
torch                         1.7.0
tornado                       6.1
tqdm                          4.50.1
traitlets                     4.3.3
traits                        6.0.0
traitsui                      6.1.3
traittypes                    0.2.1
trimesh                       3.8.18
twine                         3.3.0
typing-extensions             3.7.4.1
tzlocal                       2.0.0
ujson                         1.35
umap-learn                    0.3.10
uritemplate                   3.0.1
urllib3                       1.25.11
vedo                          2020.4.2
visbrain                      0.4.5
vispy                         0.6.6
vtk                           8.1.2
wcwidth                       0.2.4
webencodings                  0.5.1
wheel                         0.35.1
whichcraft                    0.6.1
widgetsnbextension            3.5.1
xarray                        0.16.1
xxhash                        2.0.0
zipp                          3.1.0
zmesh                         0.4.0
zope.event                    4.4
zope.interface                5.1.0
zstandard                     0.14.0
</pre>
</details>

Do you spot anything in there?

**Comment by william-silversmith** [comment]
This looks like a dependency problem with the Google Cloud Storage library. Usually when stuff like this crops up, I recommend creating a new virtual env and installing from scratch `pip install cloud-volume[all_viewers]`. Alternatively, here is the latest pip freeze from CV. We record the dependencies that would have been installed every day, so if there's a particular date you'd like to view let me know.

```
attrs==20.3.0
boto3==1.17.5
botocore==1.20.5
Brotli==1.0.9
brotlipy==0.7.0
cachetools==4.2.1
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
click==7.1.2
cloud-files==1.24.1
cloud-volume==3.8.0
compressed-segmentation==2.0.1
crc32c==2.2
cryptography==3.4.4
deflate==0.3.0
dill==0.3.3
DracoPy==0.0.15
fastremap==1.11.1
fpzip==1.1.4
gevent==21.1.2
google-api-core==1.26.0
google-auth==1.25.0
google-cloud-core==1.6.0
google-cloud-storage==1.35.1
google-crc32c==1.1.2
google-resumable-media==1.2.0
googleapis-common-protos==1.52.0
greenlet==1.0.0
idna==2.10
importlib-metadata==3.4.0
inflection==0.5.1
iniconfig==1.1.1
jmespath==0.10.0
json5==0.9.5
jsonschema==3.2.0
Markdown==3.3.3
multiprocess==0.70.11.1
numpy==1.20.1
orjson==3.4.8
packaging==20.9
pathos==0.2.7
Pillow==8.1.0
pkg-resources==0.0.0
pluggy==0.13.1
posix-ipc==1.0.5
pox==0.2.9
ppft==1.6.6.3
protobuf==3.14.0
psutil==5.4.3
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyrsistent==0.17.3
pysimdjson==3.2.0
pytest==6.2.2
python-dateutil==2.8.1
python-jsonschema-objects==0.3.13
pytz==2021.1
requests==2.25.1
rsa==4.6
s3transfer==0.3.4
simplejpeg==1.4.0
six==1.15.0
tenacity==6.3.1
toml==0.10.2
tqdm==4.56.1
typing-extensions==3.7.4.3
urllib3==1.25.11
zipp==3.4.0
zope.event==4.5.0
zope.interface==5.2.0
zstandard==0.15.1
```

**Comment by schlegelp** [comment]
Thanks! Updating all the google packages did the trick!
