### ISSUE TITLE
install fails on python 3.9

### ISSUE THREAD

**Issue by xgui3783** [seung-lab/cloud-volume#463]
Dear all,

On trying to install cloudvolume on python 3.9, an error was encountered [github action log](https://github.com/FZJ-INM1-BDA/siibra-python/runs/2411702878?check_suite_focus=true#step:4:229):

```sh
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
cloud-volume depends on tqdm@ git+https://github.com/seung-lab/tqdm.git#egg=tqdm#egg=tqdm 
```

On python version 3.8 or below, installation went smoothly.

**Comment by william-silversmith** [comment]
Hi, it looks like from the log, numpy wasn't found and some pip
backtracking occurred that resulted in it downloading a very old version of
CV that emitted that error.

Try explicitly installing numpy before cloud-volume (on a previous command
line) as CV dependencies can depend on its header files being present. Give
it a try and see if that happens again?

**Comment by xgui3783** [comment]
installing numpy prior to installing cloudvolume indeed resolve the issue [link to ci](https://github.com/FZJ-INM1-BDA/siibra-python/runs/2412148237?check_suite_focus=true). 

Hmm, looking back at the log, it looks super weird that pip keeps on trying to collect earlier and earlier version of cloudvolume, until it finds a version that pip refuse to install.

Thanks for clearing that up!

**Comment by william-silversmith** [comment]
pip made an update a few months ago that is much stricter about resolving
dependencies. I feel very ambivalent about how it was rolled out and
implemented though it ultimately is a good idea and I appreciate the free
work they do to keep the ecosystem running.
