### ISSUE TITLE
Calling Skeleton.to_swc() and Skeleton.from_swc() changes the topology of simple swc file

### ISSUE THREAD

**Issue by shreyasingh1** [seung-lab/cloud-volume#466]
See below code snippet, code output, and [attached swc file](https://drive.google.com/file/d/1WPo1SwH7N9P8NjBq8rNfREGLidoIpYrS/view?usp=sharing) (save in in local destination "Downloads" / "sample_test_swc" / "tree_1.swc")

As shown in code output, calling Skeleton.from_swc() and then Skeleton.to_swc() changes the structure of vertices in a simple swc file. In the original swc file, Vertex 2 is the only node with Vertex 1 as parent. In the swc file after Skeleton.to_swc() and Skeleton.from_swc() are called, Vertices 8 and 10 now have Vertex 1 as parent. The order of the remaining vertices also differs in the second swc file.

Is this a problem with Skeleton.to_swc() and Skeleton.from_swc()? Or perhaps a problem with the input swc file? I cannot understand what in the functions would cause such a significant change in swc structure.

**input swc:** 20 points that form a sequential line, each point has only one parent. Vertex 1 has a parent of -1, vertex 2 has a vertex 1 as parent, vertex 3 has vertex 2 as parent, etc.

**output swc:** 20 points. Vertex 8 and 10 now have vertex 1 as parent, and remaining vertex structure is also different.

**output:**
```
Original SWC

   vertex structure           x          y           z         r parent
3       1         0  -18.458370  23.227150  -84.035016  1.000000     -1
4       2         0  -18.159709  22.925778  -82.984344  1.000000      1
5       3         0  -17.861047  22.624407  -82.984344  1.000000      2
6       4         0  -17.562385  22.624407  -82.984344  1.000000      3
7       5         0  -16.965061  22.021663  -82.984344  1.000000      4
8       6         0  -16.965061  21.720292  -82.984344  1.000000      5
9       7         0  -16.069075  21.720292  -82.984344  1.000000      6
10      8         0  -16.069075  21.117548  -80.883000  1.000000      7
11      9         0  -15.770414  20.816176  -80.883000  1.000000      8
12     10         0  -15.770414  20.514805  -80.883000  1.000000      9
13     11         0  -15.770414  20.816176  -80.883000  1.000000     10
14     12         0  -16.069075  21.117548  -80.883000  1.000000     11
15     13         0  -16.069075  21.418920  -80.883000  1.000000     12
16     14         0  -16.069075  20.816176  -78.781655  1.000000     13
17     15         0  -15.471752  20.213433  -76.680311  1.000000     14
18     16         0  -15.471752  19.309318  -76.680311  1.000000     15
19     17         0  -15.471752  19.007946  -75.629639  1.000000     16
20     18         0  -15.173090  18.706574  -74.578966  1.000000     17
21     19         0  -14.874428  18.706574  -74.578966  1.000000     18
22     20         0  -14.575766  18.405202  -74.578966  1.000000     19


Orig SWC -> Skel -> New SWC

   vertex structure           x          y          z    r  parent
14      1         0  -18.458370  23.227150 -84.035019  1.0    -1.0
15      8         0  -16.069075  21.117548 -80.883003  1.0     1.0
16     12         0  -15.770414  20.816175 -80.883003  1.0     8.0
17     11         0  -15.770414  20.514805 -80.883003  1.0    12.0
18      9         0  -16.069075  21.418921 -80.883003  1.0     8.0
19      7         0  -16.069075  20.816175 -78.781654  1.0     9.0
20     15         0  -15.471752  20.213432 -76.680313  1.0     7.0
21     14         0  -15.471752  19.309319 -76.680313  1.0    15.0
22     13         0  -15.471752  19.007946 -75.629639  1.0    14.0
23     16         0  -15.173090  18.706573 -74.578964  1.0    13.0
24     17         0  -14.874428  18.706573 -74.578964  1.0    16.0
25     18         0  -14.575766  18.405203 -74.578964  1.0    17.0
26     10         0  -16.069075  21.720291 -82.984344  1.0     1.0
27      5         0  -16.965061  21.720291 -82.984344  1.0    10.0
28      6         0  -16.965061  22.021664 -82.984344  1.0     5.0
29      4         0  -17.562386  22.624407 -82.984344  1.0     6.0
30      3         0  -17.861048  22.624407 -82.984344  1.0     4.0
31      2         0  -18.159710  22.925777 -82.984344  1.0     3.0
```

**code to reproduce output:**
```
from cloudvolume import Skeleton
from pathlib import Path
from io import StringIO
import pandas as pd

#loading and printing sample swc
source_segments = (Path().resolve().parents[5] / "Downloads" / "sample_test_swc" / "tree_1.swc").as_posix()
with open(str(source_segments), "r") as f:
    contents = f.read()
    
string_io = StringIO(contents)
df = pd.read_table(
    string_io,
    names=["vertex", "structure", "x", "y", "z", "r", "parent"],
    sep=" "
)
print("Original SWC\n")
print(df[3:])
print("")
print("")


#converting swc to skeleton object
skel = Skeleton.from_swc(contents) 

#converting skeleton back to swc
swc = Skeleton.to_swc(skel)

string_io = StringIO(swc)
df = pd.read_table(
    string_io,
    names=["vertex", "structure", "x", "y", "z", "r", "parent"],
    sep=" "
)
print("Orig SWC -> Skel -> New SWC\n")
print(df[14:])
```

**Comment by william-silversmith** [comment]
It looks like there's some kind of problem. Thanks for bringing this to my attention!

Original: 

<img width="819" alt="image" src="https://user-images.githubusercontent.com/2517065/116330710-12f95900-a79c-11eb-8da0-c4756f6e111f.png">

from_swc(to_swc()):

<img width="822" alt="image" src="https://user-images.githubusercontent.com/2517065/116330739-299fb000-a79c-11eb-9866-d424d747bdeb.png">

However, simply having a different structure in the SWC isn't too surprising. The SWC file treats skeletons as a rooted tree  while cloudvolume.Skeleton treats them as a general graph with arbitrary edges and vertices. Cycling a skeleton from_swc through to_swc will lose the root information and cause an arbitrary root to be chosen. I think we could fix that by detecting roots in an swc file and storing them in the Skeleton object so that if to_swc was called, the original roots would be preferred.

The structure problem at the bottom of the image though looks more like a straight up bug. I'll have to figure out what's causing that.

**Comment by william-silversmith** [comment]
Sorry, lots of meetings today. I will be taking a look at this in more detail tomorrow.

**Comment by william-silversmith** [comment]
It looks like part of this issue is due to the call to "remove_disconnected_vertices()". Still investigating.

**Comment by william-silversmith** [comment]
Nevermind, that wasn't correct. It looks like the problem is that the swc has two pairs of identical vertex locations, though they have different IDs and parents. There are several calls to `consolidate()` in the code that remove the duplicates. I'm guessing that this is behavior that is not wanted. Can I ask what kind of process generated these duplicates?

**Comment by william-silversmith** [comment]
I should explain that these SWC readers/writers were created to manage the production of skeletons that are pieced together from many subunits, so our own skeletons initially contain many trivial duplicates that we like to eliminate. I can't make the claim that our SWC IO system fully supports all kinds of inputs (yet) but bug reports like this help push it in that direction.

**Comment by shreyasingh1** [comment]
@william-silversmith Ah I see, that makes sense, and thank you for your time spent looking into it so far!
These swc files are manual traces that map neuron pathways in the brain. Perhaps because they are manual, some points were duplicated. Regardless, preserving the integrity of the swc when we upload to and download from S3 would be ideal for us. Do you have any thoughts as to how we could get around this? One idea could be passing an additional argument where True = call consolidate() and False = do not call consolidate()?

**Comment by william-silversmith** [comment]
I'm looking into the feasibility of that kind of a strategy. The connected components algorithm I have written might depend on zero duplicates. I'll give an update within a day or two.

**Comment by william-silversmith** [comment]
I think I have something that will work for your purposes. This is a very limited improvement, but the SWC after passing through from_swc and to_swc should retain the same structure but the edges and vertices might have a different numbering scheme. It's more difficult to expand this idea to the entire skeleton subsystem. Would you mind giving #470 a try and see if it works for you?

**Comment by shreyasingh1** [comment]
Hi William, many apologies for the delay on this -I have been out of the lab for a few weeks-  and thank you for your thoroughness. I tried rerunning the code I posted in original issue using the latest version of the cloud-volume master branch.  The output SWC looks the same to me, with the topology still altered beyond just the numbering scheme. Should I be seeing something different? At your convenience, would you mind providing an example conversion showing the changes that you made?

**Comment by william-silversmith** [comment]
Hi again! Here's my test that seems to be passing.

```python
def test_read_duplicate_vertex_swc():
  test_file = """
1 0 -18.458370 23.227150 -84.035016 1.000000 -1
2 0 -18.159709 22.925778 -82.984344 1.000000 1
3 0 -17.861047 22.624407 -82.984344 1.000000 2
4 0 -17.562385 22.624407 -82.984344 1.000000 3
5 0 -16.965061 22.021663 -82.984344 1.000000 4
6 0 -16.965061 21.720292 -82.984344 1.000000 5
7 0 -16.069075 21.720292 -82.984344 1.000000 6
8 0 -16.069075 21.117548 -80.883000 1.000000 7
9 0 -15.770414 20.816176 -80.883000 1.000000 8
10 0 -15.770414 20.514805 -80.883000 1.000000 9
11 0 -15.770414 20.816176 -80.883000 1.000000 10
12 0 -16.069075 21.117548 -80.883000 1.000000 11
13 0 -16.069075 21.418920 -80.883000 1.000000 12
14 0 -16.069075 20.816176 -78.781655 1.000000 13
15 0 -15.471752 20.213433 -76.680311 1.000000 14
16 0 -15.471752 19.309318 -76.680311 1.000000 15
17 0 -15.471752 19.007946 -75.629639 1.000000 16
18 0 -15.173090 18.706574 -74.578966 1.000000 17
19 0 -14.874428 18.706574 -74.578966 1.000000 18
20 0 -14.575766 18.405202 -74.578966 1.000000 19
"""

  skel = Skeleton.from_swc(test_file)
  assert skel.vertices.shape[0] == 20
  skel2 = Skeleton.from_swc(skel.to_swc())
  assert skel2.vertices.shape[0] == 20
  assert Skeleton.equivalent(skel, skel2)

  print(skel2.to_swc())
```

It outputs this file:
```
# ORIGINAL_SOURCE CloudVolume 4.1.0
# CREATURE 
# REGION
# FIELD/LAYER
# TYPE
# CONTRIBUTOR 
# REFERENCE
# RAW 
# EXTRAS 
# SOMA_AREA
# SHINKAGE_CORRECTION 
# VERSION_NUMBER 4.1.0
# VERSION_DATE 2021-06-11T04:49:39.108842
# SCALE 1.000000 1.000000 1.000000

1 0 -18.458370 23.227150 -84.035019 1.000000 -1
2 0 -18.159710 22.925777 -82.984344 1.000000 1
3 0 -17.861048 22.624407 -82.984344 1.000000 2
4 0 -17.562386 22.624407 -82.984344 1.000000 3
5 0 -16.965061 22.021664 -82.984344 1.000000 4
6 0 -16.965061 21.720291 -82.984344 1.000000 5
7 0 -16.069075 21.720291 -82.984344 1.000000 6
8 0 -16.069075 21.117548 -80.883003 1.000000 7
9 0 -15.770414 20.816175 -80.883003 1.000000 8
10 0 -15.770414 20.514805 -80.883003 1.000000 9
11 0 -15.770414 20.816175 -80.883003 1.000000 10
12 0 -16.069075 21.117548 -80.883003 1.000000 11
13 0 -16.069075 21.418921 -80.883003 1.000000 12
14 0 -16.069075 20.816175 -78.781654 1.000000 13
15 0 -15.471752 20.213432 -76.680313 1.000000 14
16 0 -15.471752 19.309319 -76.680313 1.000000 15
17 0 -15.471752 19.007946 -75.629639 1.000000 16
18 0 -15.173090 18.706573 -74.578964 1.000000 17
19 0 -14.874428 18.706573 -74.578964 1.000000 18
20 0 -14.575766 18.405203 -74.578964 1.000000 19
```

The `Skeleton.equivalent` call checks to make sure the edge graphs are isomorphic using networkx as well as checks for matching vertex values.

**Comment by shreyasingh1** [comment]
Ah i see, that does look correct! For some reason, I am unable to replicate it, which is probably an environment error on my end. 

I git cloned the master branch and then did `pip install -e .` Is there something else I should do to access the most updated version of the repo?

**Comment by william-silversmith** [comment]
That's pretty strange! Have you tried using a [virtual environment](https://docs.python.org/3/tutorial/venv.html) or anaconda?

**Comment by shreyasingh1** [comment]
Ah so interestingly, after re-testing in a clean conda enviornment with only cloud-volume installed, the test passes like you show! But when I then go install our lab's repo [brainlit](https://github.com/neurodata/brainlit), and rerun the test, it fails. Brainlit is the repo where we leverage cloudvolume, so it would be important for this fix to work with brainlit installed.

During the brainlit installation, I get this dependency conflict that hasn't popped up before: _ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cloud-files 1.28.1 requires urllib3[secure]>=1.26.3, but you have urllib3 1.24.2 which is incompatible._

Do you think our urllib3 version is the source of this issue?

**Comment by william-silversmith** [comment]
I think the problem is this line in brainlit's requirements.txt:

```
 cloud-volume==1.6.0
```

https://github.com/neurodata/brainlit/blob/develop/requirements.txt#L4

Brainlit is pinned to CV 1.6.0 but the latest version is 4.2.0.

**Comment by shreyasingh1** [comment]
Fixed this on our end and now the test is passing for me. Thanks for keeping up with this and thanks again for the fix!

**Comment by william-silversmith** [comment]
Glad it works! Enjoy the holiday! 🎇
