### ISSUE TITLE
Handling of zeros by .get_roots() 

### ISSUE THREAD

**Issue by bjm5164** [seung-lab/cloud-volume#469]
Passing lists of supervoxel IDs containing zeros to CloudVolume.get_roots() causes only the first zero in the list to be dropped, while subsequent zeros return a root ID of zero. I am not sure if this is intentional, but this could cause indexing headaches if it isn't noticed and handled afterwards.

**Comment by william-silversmith** [comment]
Even removing the first zero could cause indexing headaches. I think we had assumed that the segids we're sending are unique. I guess that was a bad assumption. Maybe we should remove zeros and reinsert them into the output.

**Comment by bjm5164** [comment]
Yeah. In reality, removing all zeros before looking up rootIDs is beneficial anyway, but I wanted to point out the behavior in case someone tries this without realizing what is happening (as I did at first).

**Comment by jefferis** [comment]
But if cloudvolume would look after it, so much the better!

**Comment by william-silversmith** [comment]
Right now we return an array of root IDs. It seems to be we might be better served by returning a dictionary.
