### ISSUE TITLE
~/.cloudvolume/project_name required?

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/cloud-volume#47]
I noticed that the CloudVolume initialization crashes if the `~/.cloudvolume/project_name` file is missing. However, it works perfectly fine if the file is _empty_. Why is that?

**Comment by william-silversmith** [comment]
The project_name thing is a little weird. For instance, it shouldn't be required if you're using s3.

Maybe we should only check for it if you create a Google Storage CloudVolume. I can't imagine that it worked for you if that was the case.

**Comment by nkemnitz** [comment]
Hm, I am _only_ working with Google Storage at the moment. Empty file works fine for me...

**Comment by william-silversmith** [comment]
Ah it looks like the google-secret.json includes the project ID. Maybe I
can drop that step completely?

**Comment by nkemnitz** [comment]
Fixed in [feat: removed requirement for project_name file](https://github.com/seung-lab/cloud-volume/commit/b3fd2539e20b66442a958d7629da6b2da7a81a80). Thanks, Will!
