### ISSUE TITLE
Key error is raised if key 'sharding' doesn't exist

### ISSUE THREAD

**Issue by SridharJagannathan** [seung-lab/cloud-volume#472]
https://github.com/seung-lab/cloud-volume/blob/5db65a9f096fd94526b7b2fa00974013089f97fe/cloudvolume/datasource/precomputed/skeleton/metadata.py#L88

In the above line, if the key 'sharding' did not exist in the first place it produces the following error:
```
KeyError: 'sharding'
```

**Comment by SridharJagannathan** [comment]
@william-silversmith Please feel free to merge the PR #473 to resolve this issue. I noticed this error while running test cases for my python package: https://github.com/SridharJagannathan/pyroglancer

**Comment by william-silversmith** [comment]
Thanks! I just merged your change and it'll go out in the next release.
