### ISSUE TITLE
creating sharded multi resolution meshes

### ISSUE THREAD

**Issue by SridharJagannathan** [seung-lab/cloud-volume#475]
Hi @william-silversmith ,
I'm trying to create a pipeline in the `pyroglancer` software that can produce sharded multi resolution meshes.
I think I'm nearly there (unsharded multi res meshes work), as part of the multi res meshes as per the spec here:
https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/meshes.md#multi-resolution-mesh-manifest-file-format
I need to create a fragment data file and a manifest file.

Now the requirement is that i need to put the fragment data before the manifest file in the same shard.
So far, I use the function `synthesize_shards` to create shards for the binary files with labels as seg ids.
The manifest data seem to work as I can read them over from using the lines 
https://github.com/seung-lab/cloud-volume/blob/ffdc1e1eda4c25c89abe460f6e588946ebf7ff44/cloudvolume/datasource/precomputed/mesh/multilod.py#L188

Can you please tell me now, how I can add a fragment data in front of this binary file (manifest), yet keeping them in the same shard.

This is in essence the reverse of what is happening here:
https://github.com/seung-lab/cloud-volume/blob/ffdc1e1eda4c25c89abe460f6e588946ebf7ff44/cloudvolume/datasource/precomputed/mesh/multilod.py#L249

**Comment by SridharJagannathan** [comment]
The relevant spec details from https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/meshes.md#multi-resolution-mesh-manifest-file-format:

> If the sharded format is used, the mesh fragment data file is located immediately before the manifest file in the same shard data file. The starting offset within that shard data file is not specified explicitly but may be computed from the starting offset of the manifest file and the sum of the mesh fragment sizes specified in the manifest.

**Comment by william-silversmith** [comment]
Hi! I have a similar project to do with `igneous`. I think a specialized version of `synthesize_shards` will have to be written because we want the minishard index to point to the manifest and then we calculate the location of the data from the manifest.

**Comment by SridharJagannathan** [comment]
Thanks @william-silversmith , yes would be good to collaborate as well. I have made a PR #477 to resolve this issue of having offsets for shards, can you please check and let me know.

**Comment by SridharJagannathan** [comment]
Closed via #477
