### ISSUE TITLE
Add a tutorial of how to generate and upload mesh (vectorgraph type) data from scratch

### ISSUE THREAD

**Issue by spikeliu** [seung-lab/cloud-volume#479]
Thanks a million for creating a series of wonderful tools for people to view neuro-data. I wonder if there is a tutorial of how to generate mesh or skelton data from scratch (could be from segmentation data by other tools, or just manually created toy dataset, like randomly generate a obj file then convert it to draco format with some info data structure accepted by neuroglancer) and upload it through could-volume in this repo or somewhere on the internet. I searched a lot of places but can not find one. All I can found is data specification from neuroglancer's repo. It could be that I miss something information valuable, I would be really appreciate if anyone can point out where I can find such information.

**Comment by william-silversmith** [comment]
Hi, we also have a pipeline for producing neuroglancer datasets called [Igneous](https://github.com/seung-lab/igneous). Give it a look!
