### ISSUE TITLE
change the max_mip variable to mip_stop?

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/cloud-volume#481]
currently, the `max_mip` variable do not actually create that mip level, but stops before that mip level, it is not inclusive. We should either make it really inclusive or rename it to `mip_stop`? The first option might be better and all the downstream code will still work?

https://github.com/seung-lab/cloud-volume/blob/5db65a9f096fd94526b7b2fa00974013089f97fe/cloudvolume/datasource/precomputed/metadata.py#L133

**Comment by william-silversmith** [comment]
Sure, we could make that inclusive. I don't think max_mip is used too frequently, so not a huge change.

**Comment by william-silversmith** [comment]
Would you mind submitting a PR?

**Comment by jingpengw** [comment]
sure. check it out here:
https://github.com/seung-lab/cloud-volume/pull/483

**Comment by william-silversmith** [comment]
Released in CV 5.0.0
