### ISSUE TITLE
Release pin on psutil version

### ISSUE THREAD

**Issue by chrisroat** [seung-lab/cloud-volume#489]
I'm not familiar with psutil, but was curious if the pin on psutil is still necessary (no real problem if it is):

https://github.com/seung-lab/cloud-volume/blob/9bcb69314d61e309ff9c3e2e972594a89262e448/setup.py#L31

**Comment by william-silversmith** [comment]
I looked into this and releasing the pin looks like it shouldn't be a problem (I think!).

**Comment by william-silversmith** [comment]
Released in 5.1.1 Sorry for the wait!

**Comment by chrisroat** [comment]
No apology needed at all.  Thank you for all your work on this!
