### ISSUE TITLE
Cache manifests

### ISSUE THREAD

**Issue by schlegelp** [seung-lab/cloud-volume#493]
Hi Will! I did some line profiling for `GrapheneUnshardedMeshSource.get` with `cache=True`. Once the actual mesh fragments have been cached, the bottleneck in subsequent calls appears to be [`fetch_manifest`](https://github.com/seung-lab/cloud-volume/blob/b6a651789891fbeb5b7ff36c644c4fa48790e622/cloudvolume/datasource/graphene/mesh/unsharded.py#L63) where ~2/3 of the time is spent. I was wondering if you see any mileage in caching results of that method? Perhaps a simple `lru_cache` might do the trick?

**Comment by william-silversmith** [comment]
That's an interesting point. Graphene is harder to cache than other data because it's dynamic, so you never know when the cache is stale. On the other hand, it doesn't change THAT fast usually. Let me talk to Sven about what he thinks is the best approach. There might be a way to note that a neuron is finished and immutable.

**Comment by schlegelp** [comment]
Thanks for looking into it! Wouldn't you expect the file manifest for a given root ID to always be the same? Any change - split or merge - should result in a new root ID, right?

**Comment by william-silversmith** [comment]
That's an excellent point. Maybe we should just cache it period.

**Comment by nkemnitz** [comment]
There is a brief period after the merge/split when the final mesh is not yet fully generated and the graph server will return an alternative set of mesh fragments in the manifest.

**Comment by nkemnitz** [comment]
Maybe the graph server could set an [Expires](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires) header to the manifest response in such a case.

**Comment by william-silversmith** [comment]
Just not sure how to represent a time-based caching system without adding more complexity to the system. It's not possible to determine how old an ID is there? Maybe we can assume segments older than X hrs are okay?

**Comment by schlegelp** [comment]
For most use-cases on our end the short period between merge/split and re-meshing won't be an issue. 

Perhaps in a first pass `get_mesh()` (or `CloudVolume` itself) could accept something like a `cache_manifests` parameter which is `False` by default? That way users can decide whether they want speed up at the risk of potentially getting incomplete meshes.
