### ISSUE TITLE
Not Able to Access The Full Bounds of Neuroglancer Data

### ISSUE THREAD

**Issue by samf915** [seung-lab/cloud-volume#497]
I wish to export random samples of cross-sectional data from the available neuroglancer page on the [mouse brain](https://ngl.microns-explorer.org/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%2C%22position%22:%5B221652.515625%2C186789.640625%2C21075.5%5D%2C%22crossSectionScale%22:3.836162440866783%2C%22projectionOrientation%22:%5B-0.04156983271241188%2C-0.024576794356107712%2C-0.005357755348086357%2C-0.9988189339637756%5D%2C%22projectionScale%22:489587.6696286937%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22precomputed://https://bossdb-open-data.s3.amazonaws.com/iarpa_microns/minnie/minnie65/em%22%2C%22subsources%22:%7B%22default%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22tab%22:%22source%22%2C%22shaderControls%22:%7B%22normalized%22:%7B%22range%22:%5B86%2C172%5D%7D%7D%2C%22name%22:%22img65%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22precomputed://https://bossdb-open-data.s3.amazonaws.com/iarpa_microns/minnie/minnie35/em%22%2C%22subsources%22:%7B%22default%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22tab%22:%22source%22%2C%22shaderControls%22:%7B%22normalized%22:%7B%22range%22:%5B112%2C172%5D%7D%7D%2C%22name%22:%22img35%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://iarpa_microns/minnie/minnie65/seg%22%2C%22tab%22:%22source%22%2C%22annotationColor%22:%22#8f8f8a%22%2C%22selectedAlpha%22:0.41%2C%22notSelectedAlpha%22:0.06%2C%22segments%22:%5B%22864691134064155671%22%2C%22864691135293126156%22%2C%22864691135387899829%22%2C%22864691135937286404%22%2C%22864691136443719299%22%2C%22864691136812081779%22%5D%2C%22segmentQuery%22:%22864691135269913253%2C%20864691135293126156%2C%20864691135303399847%2C%20864691135307240262%2C%20864691135358985048%2C%20864691135367308281%2C%20864691135386593409%2C%20864691135428608048%2C%20864691135446864980%2C%20864691135463706181%2C%20864691135544579880%2C%20864691135560721377%2C%20864691135590150923%2C%20864691135644850415%2C%20864691135697462549%2C%20864691135700443515%2C%20864691135748826153%2C%20864691135754758610%2C%20864691135785592772%2C%20864691135937286404%2C%20864691135946888545%2C%20864691136812081779%2C%20864691136951664863%2C%20864691136952074207%22%2C%22colorSeed%22:1689220695%2C%22name%22:%22seg65%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://iarpa_microns/minnie/minnie35/seg%22%2C%22tab%22:%22segments%22%2C%22annotationColor%22:%22#8a8a8a%22%2C%22segments%22:%5B%22864691137827278437%22%2C%22864691138020403235%22%2C%22864691138081021535%22%2C%22864691138134948293%22%2C%22864691138142870469%22%2C%22864691138153699060%22%2C%22864691138178964470%22%2C%22864691138345166401%22%5D%2C%22name%22:%22seg35%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22seg65%22%7D%2C%22layout%22:%7B%22type%22:%22xy-3d%22%2C%22orthographicProjection%22:true%7D%7D). To do this, I use the CloudVolume function to import the dataset:

`mouse_dataset = CloudVolume('https://storage.googleapis.com/iarpa_microns/minnie/minnie65/seg',
  mip=0, fill_missing=True)`

and then I randomly generate x, y, and z values using the minimum/maximum values of each coordinate given on the neuroglancer page in order to obtain my cross section (in this case, a 16x16 2d cross section):
`size=16`
`x1=random.randint(27648, 453631-size)`
  `y1=random.randint(27648, 388095-size)`
 ` z=random.randint(7904, 27903)`
 ` x2=x1+size`
 ` y2=y1+size`
`data=mouse_dataset[x1:x2, y1:y2, z]`

The only problem is that configuring the randomly-generated x, y, and z coordinates in this manner often results in an out of bounds error, and one can deduce from the information given in the error that the allowed bounds are (26385, 218809) for x, (30308, 161359) for y, and (14850, 27858) for z. Of course, this is a problem since data exists far outside of these ranges. I'd greatly appreciate any help in trying to resolve this issue. Thank you!

Also, it's worth noting that going through the same procedure for the [fly brain](https://hemibrain-dot-neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%2C%22position%22:%5B19086.521484375%2C17306.71875%2C18124.5%5D%2C%22crossSectionScale%22:9.076565034035978%2C%22crossSectionDepth%22:-37.62185354999912%2C%22projectionScale%22:109219.18067006872%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%7B%22url%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.2/segmentation%22%2C%22subsources%22:%7B%22default%22:true%2C%22properties%22:true%2C%22mesh%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22tab%22:%22segments%22%2C%22objectAlpha%22:0.3%2C%22name%22:%22segmentation%22%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22size%22:290%2C%22visible%22:true%2C%22layer%22:%22segmentation%22%7D%2C%22layout%22:%22xy-3d%22%7D) yields no errors, and I can exactly set the bounds in my python code as they are shown on the neuroglancer page.

**Comment by nkemnitz** [comment]
I guess you found the solution, but just for completeness: The Neuroglancer view in the link is set to a pixel resolution of 4 nm x 4 nm (the original imaging resolution for this dataset) and all voxel coordinates are based on that resolution. However, the highest available resolution for the aligned and rendered EM and segmentation layer is 8 nm x 8 nm - that is also the one CloudVolume fetches for MIP0. So the entire Minnie65 segmentation is indeed confined to [26385, 218809) for x and [30308, 161359) for y.
