### ISSUE TITLE
SWC to NPY file format support?

### ISSUE THREAD

**Issue by manoaman** [seung-lab/cloud-volume#500]
Hi Will,

Does cloud-volume or related software libraries support SWC file format to NPY (Numpy) file format conversion?  I'm searching for ways to use SWC files with Tensorflow and I was wondering if you support the feature on the file type conversion from skeletons.  Any suggestions?

Thank you,
-m

**Comment by william-silversmith** [comment]
Hi m!

Yes it does if you are okay with separate files for vertices and edges.

```python
from cloudvolume import Skeleton
import numpy as np

with open("123.swc", "rt") as f:
    swctext = f.read()

skel = Skeleton.from_swc(swctext)
np.save("123-verts.npy", skel.vertices)
np.save("123-edges.npy", skel.edges)
np.save("123-radii.npy", skel.radii)
```

If you're clever, you can probably find a way to include vertices and edges into a single file.

**Comment by manoaman** [comment]
Thank you Will!
