### ISSUE TITLE
Issue with caching service on Windows 10

### ISSUE THREAD

**Issue by schlegelp** [seung-lab/cloud-volume#512]
Hi Will. I had someone open an issue in `navis` (navis-org/navis#75). We tracked it down to the caching service in `cloud-volume`:

```Python
>>> vol = CloudVolume('precomputed://gs://iarpa_microns/minnie/minnie65/seg', cache=True)
File "C:\Users\sebas\anaconda3\envs\test\lib\site-packages\cloudvolume\cloudvolume.py", line 228, in __new__
    return REGISTERED_PLUGINS[path.format](**kwargs)
  File "C:\Users\sebas\anaconda3\envs\test\lib\site-packages\cloudvolume\datasource\precomputed\__init__.py", line 99, in create_precomputed
    mesh = PrecomputedMeshSource(meta, cache_service, config, readonly)
  File "C:\Users\sebas\anaconda3\envs\test\lib\site-packages\cloudvolume\datasource\precomputed\mesh\__init__.py", line 17, in __new__
    mesh_meta = PrecomputedMeshMetadata(meta, cache)
  File "C:\Users\sebas\anaconda3\envs\test\lib\site-packages\cloudvolume\datasource\precomputed\mesh\metadata.py", line 17, in __init__
    self.info = self.fetch_info()
  File "C:\Users\sebas\anaconda3\envs\test\lib\site-packages\cloudvolume\datasource\precomputed\mesh\metadata.py", line 71, in fetch_info
    info = self.cache.download_json(self.meta.join(self.mesh_path, 'info'))
  File "C:\Users\sebas\anaconda3\envs\test\lib\site-packages\cloudvolume\cacheservice.py", line 343, in download_json
    res = res[path]
KeyError: 'mesh/info'
```

With `cache=False` there is no problem. I will push a work-around for `navis` but perhaps you have an idea where this is coming from? The code works like a charm for me on OSX but the guy is on Windows 10 - so perhaps related to the OS?

**Comment by schlegelp** [comment]
Oh and I should have mentioned this is with `7.0.0`.

**Comment by william-silversmith** [comment]
Yea, it looks like there's likely a conversion problem between `\` and `/`. Since the original target is `/` and the key is passed in as `meshdir/info` something goes wrong when the filesystem needs to look for `meshdir\info`. I'll have to do some debugging as in this case I might have to do a find and replace. Usually I like to just concatenate paths together not modify them, but this might need it.

**Comment by william-silversmith** [comment]
Thanks for reporting the issue Philipp!

**Comment by william-silversmith** [comment]
@schlegelp I think I have a fix for the problem you found. I'll give it a merge tomorrow but if you have a chance to test it on your end that would be great! I got it working on a virutalized copy of windows.

**Comment by schlegelp** [comment]
Hi Will & Happy new year! Sorry for the late response. Unfortunately I don't have access to a Windows machine but I can ask the guy who originally reported the issue to test. Is it merged yet?

**Comment by william-silversmith** [comment]
Hi Philipp, HAPPY NEW YEAR! 🎇 It worked for me but is not merged yet (sorry just slipped my mind). If you'd like me to merge it I can do it without waiting for the test, but it's more likely to serve their needs if they check it works.
