### ISSUE TITLE
Issue with Import in Anaconda on Apple Silicon (M1)

### ISSUE THREAD

**Issue by dokato** [seung-lab/cloud-volume#518]
After successful installation after I try to import, I get:

```
ImportError: dlopen(/Users/user/miniforge3/envs/newpyg/lib/python3.8/site-packages/simplejpeg/_jpeg.cpython-38-darwin.so, 2): Symbol not found: _tjCompress2
  Referenced from: /Users/user/miniforge3/envs/newpyg/lib/python3.8/site-packages/simplejpeg/_jpeg.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/user/miniforge3/envs/newpyg/lib/python3.8/site-packages/simplejpeg/_jpeg.cpython-38-darwin.so
```

I'm using python 3.8.12 and MacOS BigSur 11.6 (Apple M1).

**Comment by william-silversmith** [comment]
Huh, that's pretty weird! I'm on the same python version, hardware, and OS. I use the regular virtualenv rather than anaconda though. I just tried installing `simplejpeg` with pip on anaconda and it looked like it was installing from source. Maybe a bad source install is the issue? The binary installs on PyPI seem to work pretty well.

If you'd like simplejpeg binaries on condaforge, I can ask the maintainer if they'd be willing to do that.

**Comment by dokato** [comment]
I don't mind, I tried with pip too: `pip install -U simplejpeg`, but same thing...

**Comment by william-silversmith** [comment]
Did you notice if it was a binary or a source install?

**Comment by dokato** [comment]
Sorry, how can you tell? Probably binary, right?
```
Using cached simplejpeg-1.6.3-cp38-cp38-macosx_11_0_arm64.whl
```

**Comment by dokato** [comment]
Huh, interestingly on version  3.9.9 it works flawless. Sorry about that, must have been something messed up with my environment then 🤔

**Comment by william-silversmith** [comment]
Yea, if it's a wheel it's a binary. If it says .tar.gz it's a source installation (and there will be compilation messages too). 

I was just able to reproduce your issue in my conda environment. I've encountered this problem before when compiling my own C extensions but I don't remember the way to fix it.

Here's a version of that error for someone having problems with C++ boost-python: https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean

**Comment by william-silversmith** [comment]
I'll leave an issue for the simplejpeg maintainer. They might appreciate knowing that certain versions of anaconda python are breaking.

**Comment by william-silversmith** [comment]
The simplejpeg maintainer figured it out. On M1 if you're doing a source install, make sure to add `arch -arm64` before pip and it'll build correctly.

**Comment by zhihaozheng** [comment]
@william-silversmith It seems like we are having the same issue with pyspng-seunglab, Anaconda in M1, when trying to install cloudvolume. Does it mean we should try a different version of Python? Or we should use virtualenv in stead? I couldn't if there's a general solution from the conversations above.

**Comment by william-silversmith** [comment]
Hi Zhihao,

The method above may be a general way of solving this issue, but I suppose I could put binaries on Anaconda and that might make things easier.

**Comment by zhihaozheng** [comment]
Sorry, by `the method above`, do you mean source install the package, basically,

```
git clone git@github.com:seung-lab/pyspng-seunglab.git
cd pyspng-seunglab

conda create -n env python=3.9
conda activate env
pip install -e .
```

**Comment by william-silversmith** [comment]
No just write `arch -arm64 pip install pyspng-seunglab` or alternatively `arch -x86_64 pip install pyspng-seunglab` depending on whether rosetta2 is enabled on your terminal.

**Comment by zhihaozheng** [comment]
@william-silversmith Which numpy version did you use for pyspng-seunglab and cloudvolume? With 1.23.1 numpy, it can be imported used in python (3.9.12). but when we do `arch -arm64 pip install pyspng-seunglab`, it complaints that numpy failed to build from wheels, and exits from pyspng install.

**Comment by william-silversmith** [comment]
It uses an isolated build with oldest-supported-numpy to make sure that all numpy installs will be compatible. I guess the oldest supported numpy on conda doesn't have a binary.

**Comment by william-silversmith** [comment]
I'm trying to add wheels to conda, but it may take a little bit. 

https://github.com/conda-forge/staged-recipes/pull/19856

**Comment by william-silversmith** [comment]
@zhihaozheng I just tried installing pyspng-seunglab in a conda environment and it worked fine. Have you tried following a guide to create a rosetta2 terminal? 

https://www.youtube.com/watch?v=9W8rTTE1WEA

**Comment by dokato** [comment]
hey @william-silversmith I'm not sure what changed but now, starting from fresh environment (again, M1 arm), I'm trying:

```sh
$ conda create -n "new python=3.9
$ conda activate new
$ conda install ipython
$ arch -arm64 pip install cloud-volume  --force-reinstall
```

but this fail during import:

```py
In [1]: import cloudvolume as cv
[...]
File ~/miniconda3/envs/new/lib/python3.9/site-packages/cloudvolume/chunks.py:24, in <module>
     22 import compresso
     23 import fastremap
---> 24 import zfpc
     26 from PIL import Image
     28 from .lib import yellow

File ~/miniconda3/envs/new/lib/python3.9/site-packages/zfpc/__init__.py:5, in <module>
      2 import enum
      3 import numpy as np
----> 5 import zfpy
      7 __all__ = [ "compress", "decompress" ]
      9 DATA_TYPES = {
     10   None: 0,
     11   np.int32: 1,
   (...)
     14   np.float64: 4,
     15 }

ImportError: dlopen(/Users/dominik/miniconda3/envs/new/lib/python3.9/site-packages/zfpy.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_stream_close'
```

**Comment by dokato** [comment]
BTW I tested on `i386` and `arm64` architectures.

**Comment by dokato** [comment]
okay, fixed by installing `zfpy` separately through conda not as a dependency of cloud-volume

**Comment by william-silversmith** [comment]
Hi dokato, that's pretty odd. I'm working with the zfpy people to make it easier to install, but it's kind of slow going. I'll see how installing CV on conda goes for me and see if it's easily fixable.
