### ISSUE TITLE
Support Fancy Indexing 

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/cloud-volume#527]
This can be used in conjunction with #522 to make for efficient point queries in a natural representation.

**Comment by william-silversmith** [comment]
This has been in production since November 2022.

**Comment by jasonkena** [comment]
Is there any chance we'll be able to set points using fancy indexing @william-silversmith?

`vol[xs,ys,zs] = np.array(...)`

**Comment by william-silversmith** [comment]
This is a possibility, but is very inefficient (you have to download the entire chunk, decompress it, edit it, decompress it, and upload it again). It's something I could explore. There are some efficiencies that could be had by clustering points that lie in the same chunk.

**Comment by jasonkena** [comment]
That would be great! The use case I'm considering is setting values in the volume at all the skeleton vertices (for use with the Euclidean Distance Transform). I can probably work around it now by passing all the points when processing each chunk, filtering for valid points, but this would allow for a cleaner solution :D

**Comment by william-silversmith** [comment]
Can you describe your use case a little more? I wonder if I might have a suggestion for how to do what you need that might already be supported.

**Comment by jasonkena** [comment]
Sorry for the late reply. I wanted to do something like [this](https://github.com/jasonkena/ChunkPipeline/blob/16f519ab254a6495cb98279df5062875d1f5ab54/scripts/igneous/feature_transform.py#L122C1-L137C17). I ended up using `zarr`.

**Comment by william-silversmith** [comment]
I think I might have a similar kind of thingee going on here if that's useful: https://github.com/seung-lab/kimimaro/blob/master/kimimaro/utility.py#L270

**Comment by jasonkena** [comment]
Thanks! I'll have a look.
