### ISSUE TITLE
Edge case for graphene unique

### ISSUE THREAD

**Issue by Mencu** [seung-lab/cloud-volume#535]
Hi William!

I've noticed an edge case that throws an error in the unique function of graphene frontend (`cloud-volume/frontends/graphene.py`): https://github.com/seung-lab/cloud-volume/blob/d492675854543e0c292616979ec14ff5f13e09c9/cloudvolume/frontends/graphene.py#L178

In the case when segids (optional parameter of the `unique()` function) is None, line 178 throws a `TypeError: NonType object is not iterable` in the for-loop.

Is this intended or is it just a small bug? 

Best,
Andrei

**Comment by william-silversmith** [comment]
This fix is released in 8.5.3.  Commit 913582c08853310f3a6e0620941296d80181dd2b
