### ISSUE TITLE
Viewing a Local Filesystem CloudVolume Generated Precomputed Dataset from tiff Files

### ISSUE THREAD

**Issue by yanyanming77** [seung-lab/cloud-volume#548]
Hi everyone: 

I'm currently running neuroglancer in a docker container on my local machine. I'm using a tiff stack ~14GB. I used CloudVolume to chunk the volumes. The tiff is 8583x8562x100.  So far I've created the info file and different chunks of pre-computed data, but in neuroglancer nothing is being visualized. Can anyone shed some light on what is causing this?  Thank you very much! 

The attached files are: 1) screenshot of the info file 2) samples of precomputed chunks 3) current neuroglancer visualization

<img width="292" alt="ng-info" src="https://user-images.githubusercontent.com/78001469/181685746-984af811-e78c-4211-8577-e55132e0ddca.png">
<img width="548" alt="ng-chunks" src="https://user-images.githubusercontent.com/78001469/181685888-03198b2b-3a47-4a23-9514-db90024a23b1.png">
 <img width="1885" alt="ng-viz" src="https://user-images.githubusercontent.com/78001469/181685924-9464dffe-96ea-439d-924e-9bc5d2202983.png">

**Comment by william-silversmith** [comment]
Hi!

What is likely going wrong is that neuroglancer doesn't like the .gz
extensions on the files.

If you write:

cv.viewer()

This will start a web server locally that will be able to talk to
neuroglancer that understands file extensions.

Will

**Comment by william-silversmith** [comment]
Just FYI, if you are thinking of also using Igneous, the Igneous CLI has a command: `igneous view $DIRECTORY [--ng $LOCAL_NEUROGLANCER_URL]` by default it will use neuroglancer-demo.appspot.com/

**Comment by yanyanming77** [comment]
Hi Will - Thanks for your reply! I'm planning to move forward to Igneous after I succeeded in CloudVolume. 

I added a script which establishes the cv.viewer() (screenshot 1), and it's listening to localhost:1337 (screenshot 2), but It shows a fetching error in neuroglancer (screenshot 3). I've mapped the port of the container (nginx --> 8001, and 1337 --> 8002), so neuroglancer is running on localhost8001, and the source I specified is <precomputed://http://localhost:8002//precomputed/em>. Am I on the right direction?

Thanks! 

Ming
<img width="392" alt="ng-cv_viewer" src="https://user-images.githubusercontent.com/78001469/181842808-c0307327-e0b7-491a-a07c-174aa50e2d39.png">
<img width="532" alt="ng-docker" src="https://user-images.githubusercontent.com/78001469/181842821-f8ba8242-a5a9-40ab-a6f5-0a1ae715ddf8.png">
<img width="1439" alt="ng-viz" src="https://user-images.githubusercontent.com/78001469/181842843-d58e0202-cd03-4120-9ce6-336cfc74942f.png">

**Comment by william-silversmith** [comment]
Sorry i should have used port 8002

**Comment by yanyanming77** [comment]
Hi Will - still no luck. I tried not specifying the additional path, now it says cannot find the info file...:(
<img width="524" alt="ng-viz1" src="https://user-images.githubusercontent.com/78001469/181844418-acb38667-1605-4806-a005-5f2aba636d2a.png">

**Comment by william-silversmith** [comment]
I guess you can try adding the path back in. In the first example there
were double slashes that didn't look right

**Comment by yanyanming77** [comment]
Hi Will:

My precomputed file (420_420_1000 folder) is located in the path '/precomputed/em'. And when I typed 'localhost:8001/precomputed/em/info' in Chrome, an info file automatically download. But when I tried 'localhost:8002/precomputed/em/info', it's a 404 not found error. I'm suspecting is the 8002 is not talking to 8001? Is there anything else I could be wrong? 

Ming

**Comment by yanyanming77** [comment]
I also checked the precomputed chunks, there are 114,444 chunks (files xxxx.gz) in the path: /precomputed/em/420_420_100, with no subdirectories...and I think the number makes sense, given my volume is 8583x8562x100, and chunk size is 256x256x1. Do all of these looks right?

**Comment by william-silversmith** [comment]
Well, the browser should be independently looking at localhost:8002. Can you give the igneous command a try without reference to the docker container? Then you can at least verify everything is working right before adding in the extra  layer.

**Comment by yanyanming77** [comment]
Hi will: Thanks for your reply! I also tried the igneous command but still nothing is being displayed. I checked the 'show chunck statistics' and it seems no precomputed formats are being read (screenshot below)? If this is the case, is it possibly due to the configuration of the nginx server? Thanks! 

<img width="952" alt="image" src="https://user-images.githubusercontent.com/78001469/182468917-85006d3a-c20f-40c7-86a2-c10fa4a1a368.png">

**Comment by yanyanming77** [comment]
When looking at the developer console, it seems all the chunks weren't retrieved successfully. Are there any possible reasons why it happens? All 28,611 chunks are in <precomputed/em/420_420_1000>. Thanks! 

<img width="573" alt="image" src="https://user-images.githubusercontent.com/78001469/182478894-df066d26-81a6-49f3-ba4d-5e7681dfc184.png">

**Comment by william-silversmith** [comment]
When you're running the `igneous view` command, there should be a log of the requests the server is getting in the same terminal. Can you also show me that?

**Comment by yanyanming77** [comment]
Sure. This is what I see when running `igneous view`.
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/78001469/182485145-d5494713-8295-4b88-9549-0f5f0b4d87a6.png">

It's weird. When I tried visualizing a NIFTI file's precomputed volumes, neuroglancer had no problem reading .gz files.

**Comment by william-silversmith** [comment]
Thanks! NIFTI uses a different implementation on Neuroglancer's backend so it might be looking for the .gz by default. 

It looks like your server isn't getting any requests if that's the end of the log. I do think you should be switching the URL to precomputed://http://localhost:1337/ though (possibly with the path, try both ways).

**Comment by yanyanming77** [comment]
Hi Will:

It won't work in the docker container (I still couldn't figure out why after exposing both port 80 and 1337). But it seems working on my local machine, looking at the statistics and most of the files are loaded successfully and there is something there. This is what I saw (image below), but do you know how to adjust the settings to see the image? I've tried tweaking the opacity and the 'normalized' setting but nothing happened. My image is lightsheet image data and can be seen well when adjusting the opacity/intensity in ImageJ. 

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/78001469/182492784-835c8dfb-a8e4-47a4-9ccc-030aad253762.png">

**Comment by william-silversmith** [comment]
Sure! One thing you can try is adjusting the shader code in the text box. It could read something like:

```
#uicontrol invlerp normalized
void main() {
    emitGrayscale(normalized() * 10.0);
}
```
You can adjust the factor 10.0 to be higher or lower until you get what you want. Just make sure there is a decimal point or it will be considered an integer and not compile.

**Comment by yanyanming77** [comment]
Thanks Will! I'm able to see the image (yay!!!). The next step would be exploring igneous for further chunking (I'll start later).
Meanwhile, can you shed some light on why there are always several files that are loaded unsuccessfully? 
And is it able to share this visualization via a link with other people?  And how could I achieve that? 
Thanks!

**Comment by william-silversmith** [comment]
Fantastic! I'm glad you can finally start using Neuroglancer!

> The next step would be exploring igneous for further chunking (I'll start later).

Start by checking out the options under `igneous image xfer`. It should be pretty easy to do.

> Meanwhile, can you shed some light on why there are always several files that are loaded unsuccessfully?

This could be either a failed upload, corrupt data, broken server, or even not enough memory in the browser. Can you show a picture?

> And is it able to share this visualization via a link with other people? And how could I achieve that?

You'll need to find a server that can make this available on a stable basis. Once you have that, I think you might be able to configure nginx to find the .gz files: https://docs.nginx.com/nginx/admin-guide/web-server/compression/

That has a better chance of scaling and being reliable than the cloudvolume server that is mainly for debugging. However, you can use that in a pinch by setting the port appropriately and setting your OS and firewall to allow connections to that port.

**Comment by yanyanming77** [comment]
Hi Will: You are one of the best developers I met ever! 
The error I got is: 
<img width="712" alt="image" src="https://user-images.githubusercontent.com/78001469/182502123-01caa627-67ad-4631-83cf-34ec826fe5f1.png">

And the statistics show:
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/78001469/182502176-774b61e8-2a9d-49d2-8f88-2a6a8a918d33.png">

As I zoom out, the number of failed files increases. 

For CORS policy issue, why does it happen to some of the files but not others? I started the NeuroGlancer server using `npm run dev-server`

**Comment by william-silversmith** [comment]
Thanks Ming, I try. :) 

The error you got unfortunately can be confusing. That error appears under two conditions: (a) the server is not properly configured to issue the correct CORS headers (b) a file is missing and so an error response is sent (that doesn't have CORS headers).

You should check if the failed files really do not exist on your filesystem. If they do exist, there's at least more information we can work with. If they do not exist, something broke during the import.

Will

**Comment by yanyanming77** [comment]
Ooops I'm guessing it might be due to some of the files being bugged by Icloud... I'll try again on another computer. Btw, is the method `npm run dev-server` the correct way of getting neuroglancer to run on the local machine?

**Comment by william-silversmith** [comment]
Ah gottcha, yea any network funkiness would be good to check. `npm run dev-server` is a perfectly fine way to start Neuroglancer.

**Comment by yanyanming77** [comment]
Thanks!!! I'll try not to bug you too much when I got into Igneous :)

**Comment by william-silversmith** [comment]
No worries. Please read the Igneous README and `igneous --help` (and for relevant subcommands) but don't worry about bugging me. :)

**Comment by yanyanming77** [comment]
Hi William:

Back to neuroglancer...I was distracted by other stuff

So, to refresh, I'm testing using 100 slices of 8583 x 8562 tiff files, I started from the previously generated CloudVolume precomputed chunks (chunk by 512 x 512 x 1), located in the <precomputed/em/420_420_1000> path. Then I created a new folder <new_precomputed> to hold the new chunks and <queue_folder> to hold the queue. The commands I used are:

`igneous image xfer file://precomputed/em file://new_precomputed/em --queue queue_folder --downsample --fill-missing --shape 256,256,16`

 and then 

`igneous execute ./my-queue`

After running the first command, the info and provenance file is created under <new_precomputed/em>, and after running the second command, the <420_420_1000> is also created, but after a while, it stuck:
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/78001469/185021397-4aeba65f-292b-42f3-b5ff-f61f2d084253.png">

And looking at the chunks generated under <420_420_1000>, it seems Z is still chunked by 1, not 16 as I specified? 
<img width="186" alt="image" src="https://user-images.githubusercontent.com/78001469/185021952-deefb687-f29c-491c-a255-9ba753cf6e85.png">

Am I on the right track? Is there anything I did incorrectly?

**Comment by william-silversmith** [comment]
Hi again, thanks for reaching out! 

Yes, there is an error in the command as written. You specified `--shape` which affects the shape of the task in memory, but not the ultimate chunk size that will be rendered. Use `--chunk-size` for that.

By default, `igneous execute` will continue to poll even when no tasks are available (so you can have a bunch of workers standing by and feed them more tasks). Use the command `igneous execute -x $QUEUE` to exit when there are no tasks remaining. Part of the reason for this design choice is that when using an SQS queue, SQS provides unreliable estimates of the number of tasks remaining.

**Comment by yanyanming77** [comment]
Hi William: thanks for your reply! 

I've changed to `igneous image xfer file://precomputed/em file://new_precomputed/em --queue queue_folder --downsample --fill-missing --chunk-size 256,256,16
igneous execute ./queue_folder`

Now in terminal it's: 
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/78001469/185214330-da4237f5-6cc2-400f-82cd-fa588110518d.png">

And I see these folders are created and are being constantly updated. 
<img width="916" alt="image" src="https://user-images.githubusercontent.com/78001469/185214463-134d06fe-0ea8-4b38-b1f2-bbf58e39f9d0.png">

It's been a while and it's still processing, I wonder if it's right for a volume of around 14 GB? and how would I figure there are no tasks remaining? 

Thanks!

**Comment by william-silversmith** [comment]
Installing Igneous will also install the `ptq` command. Write `ptq --help` and `ptq status queue_folder` and that should give you what you want.

**Comment by william-silversmith** [comment]
Fantastic! Glad it's working for you. Don't hesitate to ask for help if you need it.

**Comment by yanyanming77** [comment]
Sure, thanks a lot for your help!

**Comment by yanyanming77** [comment]
hi Will: 

I'm setting up nginx for holding neuroglancer. Now my volume is 7153x7153x13200, and have used cloud volume to generate isotropic chunks with size 1024x1024x1. Loading in these chunks in neuroglancer is very slow and only a few tiles are showing when zooming out. I wonder if this is where Igneous comes into play? (i.e., generate finer chunks for faster read?)

Thanks! 
Ming

**Comment by william-silversmith** [comment]
Bingo. It seems like you already have the first layer of downsamples based on the arguments mentioned above. Would you mind sharing your info file? It will help me advise on the correct Igneous arguments.

**Comment by yanyanming77** [comment]
Sure! Here's the info file generated by cloudvolume xy chunking
<img width="297" alt="image" src="https://user-images.githubusercontent.com/78001469/188017804-46d8c2cf-fbfd-45a9-9233-09bba3afd0c9.png">

**Comment by william-silversmith** [comment]
Thanks Ming! This looks cutoff, but since there is no `,` next to the last closing brace, I believe there is only a single mip level generated.

Try doing these commands:
```
igneous image downsample PATH --mip 0 --queue ./queue
igneous [-p PARALLEL] execute -x ./queue # you can also just run multiple instances of this command
```

**Comment by yanyanming77** [comment]
hi Will: 

This is how I specified to generate the info file, please let me know if they look right.
<img width="533" alt="image" src="https://user-images.githubusercontent.com/78001469/188019120-3d60f5d5-e0cb-453e-939c-402bc58783b0.png">

In addition, can I confirm that the mip level means the number of resolutions? since there the resolution for my set is [500,500,500], we set mip=0?

And in the igneous command below, the <PATH> is the path to the precomputed chunks generated by cloudvolume (...precomputed/em)? 
`igneous image downsample <PATH> --mip 0 --queue queue_folder --downsample --fill-missing --chunk-size 128,128,64`
`igneous --parallel 4 execute -x queue_folder`

**Comment by william-silversmith** [comment]
Hi Ming,

Yes your CloudVolume info looks fine. 

`--mip 0` means the 0th (i.e. first and highest) resolution layer. Since you have only one layer, 0 is correct. If you need to do more downsampling later, you set mip to num_layers-1. 

The `--downsample` flag in your command is only for the `xfer` command. Since you're downsampling an existing layer, it's redundant and not supported. If you filled the entire volume, no need for `--fill-missing` either, it's only for if you expect that there will be chunks missing.

Otherwise, your commands look good!

Will

**Comment by yanyanming77** [comment]
Thanks will!! It's running now, let's see how it goes :)

**Comment by william-silversmith** [comment]
Awesome! Let me know how it works out for you.

**Comment by yanyanming77** [comment]
hi Will: there's an error that stops the program, an EmptyVoluemeException? I tried re-running multiple times and kept getting this error. 
<img width="583" alt="image" src="https://user-images.githubusercontent.com/78001469/188029569-aa7520c3-7272-43c0-85ab-8c213d72d6fc.png">

**Comment by william-silversmith** [comment]
Hi Ming,

This is due to either the entire rectangular volume not being filled OR is due to missing files that should be there. If the former, rerun with `--fill-missing`.

Will

**Comment by yanyanming77** [comment]
Thanks Will! I'll try it out

**Comment by yanyanming77** [comment]
Hi William: 

Igneous tasks finished and the volumes are loaded very fast in neuroglancer! Thanks for your help! 
Now I could slide through the 2D z-planes, I wonder is there a way that I could view the image in terms of a 3D volume (not just the 2D slices)? or do I need to generate a separate layer for that?

Best,
Ming

**Comment by william-silversmith** [comment]
Hi Ming,

If you have a segmentation, you can generate meshes and skeletons with
Igneous. However, if you'd just like to see the image in 3D, you can
experiment with Neuroglancer's volume rendering mode (though it is
experimental and may not work).

**Comment by yanyanming77** [comment]
hi William: 

The volume rendering mode doesn't seem to work haha, nothing changed after clicking it. 
By saying segmentation, do you mean the 3d reconstructions based on the same volume and create another layer for segmentation to be able to view in both 2D slice and 3d segmentation?

**Comment by william-silversmith** [comment]
Dang that's too bad, I didn't really expect it to work though (I've never seen it working outside of screenshots). 

Yea, by segmentation I mean a separate layer of labeled voxels. For example, like this [fly hemibrain volume](https://hemibrain-dot-neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%2C%22position%22:%5B17114%2C20543%2C18610%5D%2C%22crossSectionScale%22:54.23751620061224%2C%22crossSectionDepth%22:-37.62185354999912%2C%22projectionScale%22:64770.91726975332%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/emdata/clahe_yz/jpeg%22%2C%22tab%22:%22source%22%2C%22name%22:%22emdata%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.0/segmentation%22%2C%22tab%22:%22segments%22%2C%22name%22:%22segmentation%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%7B%22url%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.0/rois%22%2C%22subsources%22:%7B%22default%22:true%2C%22properties%22:true%2C%22mesh%22:true%7D%2C%22enableDefaultSubsources%22:false%7D%2C%22pick%22:false%2C%22tab%22:%22segments%22%2C%22selectedAlpha%22:0%2C%22saturation%22:0%2C%22objectAlpha%22:0.8%2C%22ignoreNullVisibleSet%22:false%2C%22meshSilhouetteRendering%22:3%2C%22colorSeed%22:2685294016%2C%22name%22:%22roi%22%7D%2C%7B%22type%22:%22annotation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.0/synapses%22%2C%22tab%22:%22rendering%22%2C%22ignoreNullSegmentFilter%22:false%2C%22shader%22:%22#uicontrol%20vec3%20preColor%20color%28default=%5C%22red%5C%22%29%5Cn#uicontrol%20vec3%20postColor%20color%28default=%5C%22blue%5C%22%29%5Cn#uicontrol%20float%20preConfidence%20slider%28min=0%2C%20max=1%2C%20default=0%29%5Cn#uicontrol%20float%20postConfidence%20slider%28min=0%2C%20max=1%2C%20default=0%29%5Cn%5Cnvoid%20main%28%29%20%7B%5Cn%20%20setColor%28defaultColor%28%29%29%3B%5Cn%20%20setEndpointMarkerColor%28%5Cn%20%20%20%20vec4%28preColor%2C%200.5%29%2C%5Cn%20%20%20%20vec4%28postColor%2C%200.5%29%29%3B%5Cn%20%20setEndpointMarkerSize%282.0%2C%202.0%29%3B%5Cn%20%20setLineWidth%282.0%29%3B%5Cn%20%20if%20%28prop_pre_synaptic_confidence%28%29%3C%20preConfidence%20%7C%7C%5Cn%20%20%20%20%20%20prop_post_synaptic_confidence%28%29%3C%20postConfidence%29%20discard%3B%5Cn%7D%5Cn%22%2C%22linkedSegmentationLayer%22:%7B%22pre_synaptic_cell%22:%22segmentation%22%2C%22post_synaptic_cell%22:%22segmentation%22%7D%2C%22filterBySegmentation%22:%5B%22post_synaptic_cell%22%2C%22pre_synaptic_cell%22%5D%2C%22name%22:%22synapse%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/mito_20190717.27250582%22%2C%22pick%22:false%2C%22tab%22:%22segments%22%2C%22selectedAlpha%22:0.82%2C%22name%22:%22mito%22%2C%22visible%22:false%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/mask_normalized_round6%22%2C%22pick%22:false%2C%22tab%22:%22segments%22%2C%22selectedAlpha%22:0.53%2C%22segments%22:%5B%222%22%5D%2C%22name%22:%22mask%22%2C%22visible%22:false%7D%5D%2C%22showSlices%22:false%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22segmentation%22%7D%2C%22layout%22:%22xy-3d%22%2C%22selection%22:%7B%7D%7D).

**Comment by yanyanming77** [comment]
Thanks William!! I'll talk to my colleague and move to that step if it's needed.

**Comment by yanyanming77** [comment]
hi William, quick question, by any chance does neuroglancer have an option for orthoslicer (a limited MIP view)?

**Comment by william-silversmith** [comment]
Do you mean resolution or viewing plane? Press spacebar to limit the viewing plane. To limit resolution, you can use this widget:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/2517065/188234187-6d76e0ac-7901-40bf-a71b-cb0e90e569fe.png">

**Comment by yanyanming77** [comment]
Thank you! 

Best,
Ming

**Comment by william-silversmith** [comment]
Hi Ming,

Yes this is the right track. Try doing only the localhost domain without an
additional path e.g. precomputed://http://localhost:1337/

**Comment by william-silversmith** [comment]
Closing this as there has not been activity in a while. Please feel free to reopen.
