### ISSUE TITLE
Install requirement not found: zfpc

### ISSUE THREAD

**Issue by ivan-marroquin** [seung-lab/cloud-volume#555]
Hi,

Thanks for making available this package!

When I try to install the package, everything seems to going well until the install process tries to download the package "zfpc":

python_3.6.5/lib/python3.6/site-packages/secretstorage/__init__.py:14: UserWarning: jeepney.integrate.blocking is deprecated: please use jeepney.io.blocking instead.
  from jeepney.integrate.blocking import connect_and_authenticate
python_3.6.5/lib/python3.6/site-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.utils import int_from_bytes
Collecting cloud-volume
  Downloading cloud_volume-8.9.1-py3-none-any.whl (229 kB)
     |████████████████████████████████| 229 kB 1.9 MB/s 
Requirement already satisfied: numpy>=1.13.3 in ./python_3.6.5/lib/python3.6/site-packages (from cloud-volume) (1.17.4)
Collecting pathos
  Downloading pathos-0.2.8-py2.py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 1.0 MB/s 
Collecting posix-ipc>=1.0.4; sys_platform != "win32"
  Downloading posix_ipc-1.0.5.tar.gz (96 kB)
     |████████████████████████████████| 96 kB 593 kB/s 
Collecting DracoPy<2.0.0,>=1.0.0
  Downloading DracoPy-1.2.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 3.3 MB/s 
Collecting python-jsonschema-objects>=0.3.3
  Downloading python_jsonschema_objects-0.4.1-py2.py3-none-any.whl (27 kB)
Collecting fastremap>=1.12.0
  Downloading fastremap-1.13.3-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.2 MB)
     |████████████████████████████████| 4.2 MB 3.2 MB/s 
Requirement already satisfied: six>=1.10.0 in ./python_3.6.5/lib/python3.6/site-packages (from cloud-volume) (1.12.0)
Requirement already satisfied: chardet>=3.0.4 in ./python_3.6.5/lib/python3.6/site-packages (from cloud-volume) (3.0.4)
Collecting pyspng-seunglab~=1.0.0
  Downloading pyspng_seunglab-1.0.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 1.8 MB/s 
Requirement already satisfied: requests>=2.22.0 in ./python_3.6.5/lib/python3.6/site-packages (from cloud-volume) (2.26.0)

ERROR: Could not find a version that satisfies the requirement zfpc (from cloud-volume) (from versions: none)
ERROR: No matching distribution found for zfpc (from cloud-volume)

Any suggestions?

Kind regards,

Ivan

**Comment by william-silversmith** [comment]
Hi Ivan,

Python 3.6 reached end of life last year and is no longer supported. Try
using Python 3.7 through 3.10 and you should have a better experience.

Will

**Comment by ivan-marroquin** [comment]
Hi @william-silversmith,

Thanks for the information!

ivan
