### ISSUE TITLE
zfpy prevents cloud-volume from working out of the box on macOS arm64

### ISSUE THREAD

**Issue by perlman** [seung-lab/cloud-volume#561]
The currently available `zfpy` does not work on arm64, leading to cloud-volume being unusable out-of-the-box:

```
>>> import cloudvolume
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eric/nobackup/envs/test-env/lib/python3.9/site-packages/cloudvolume/__init__.py", line 74, in <module>
    from .datasource.precomputed import register as register_precomputed
  File "/Users/eric/nobackup/envs/test-env/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/__init__.py", line 3, in <module>
    from .image import PrecomputedImageSource
  File "/Users/eric/nobackup/envs/test-env/lib/python3.9/site-packages/cloudvolume/datasource/precomputed/image/__init__.py", line 23, in <module>
    from .... import sharedmemory, chunks
  File "/Users/eric/nobackup/envs/test-env/lib/python3.9/site-packages/cloudvolume/chunks.py", line 24, in <module>
    import zfpc
  File "/Users/eric/nobackup/envs/test-env/lib/python3.9/site-packages/zfpc/__init__.py", line 5, in <module>
    import zfpy
ImportError: dlopen(/Users/eric/nobackup/envs/test-env/lib/python3.9/site-packages/zfpy.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (_stream_close)
>>> 
```

The quick fix is to comment out `import fpzip` in `cloudvolume/chunks.py` (https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/chunks.py#L38) and replace it with something like "raise ImportError".

I am confused as to why `except ImportError:` fails to catch the ImportError exception.

I've encountered this with python 3.9 & 3.10. I've yet to see zfpy actually work on an arm64 Mac (but that's an issue for zfpy, not cloud-volume.).

**Comment by william-silversmith** [comment]
Hi Eric,

It's true, perhaps I should make zfpy more optional. The current status of zfpy's arm64 support can be seen here: https://github.com/LLNL/zfp/issues/175

I managed to compile it myself, but it seems my statically linked solution was not preferable or not compatible with automated CI.

**Comment by perlman** [comment]
Wow, nice to see the effort going into making it work! (And I very much get why you're interested in the floating point fields.)

But, yes, optional would be a quick path to restore `pip install` & go functionality on mac arm64.

**Comment by william-silversmith** [comment]
By the way, here's a compiled fat binary for zfpy 1.0.0 for py39. This might tide you over in the meantime: 
[zfpy-1.0.0-cp39-cp39-macosx_10_9_universal2.whl.zip](https://github.com/seung-lab/cloud-volume/files/9923127/zfpy-1.0.0-cp39-cp39-macosx_10_9_universal2.whl.zip)

**Comment by jefferis** [comment]
@scachero FYI

**Comment by jasper-tms** [comment]
@william-silversmith you're a true hero for sharing that zfpy wheel

**Comment by william-silversmith** [comment]
no prob! lmk if you need other python versions of it.

**Comment by jasper-tms** [comment]
I would take 3.10 as well if you have it handy!

**Comment by william-silversmith** [comment]
Here are wheels for py38,py39,py310, and py311

[wheels.zip](https://github.com/seung-lab/cloud-volume/files/10147553/wheels.zip)

**Comment by william-silversmith** [comment]
This should be resolved now. Sorry for the delay!
