### ISSUE TITLE
float32 bounding box error in decompressing

### ISSUE THREAD

**Issue by HHHit** [seung-lab/cloud-volume#577]
While downloading a data, I found it is using float32 bounds. And while I download the data, I encountered the following error. How to fix it?
` File "src/compressed_segmentation.pyx", line 220, in compressed_segmentation.decompress\
 File "src/compressed_segmentation.pyx", line 194, in compressed_segmentation.decompress_helper\
TypeError: 'numpy.float32' object cannot be interpreted as an integer`

**Comment by william-silversmith** [comment]
Hi, neuroglancer bounds are supposed to be integers (they are measured in voxels). It sounds like the info file is corrupt. Would you mind sharing the scale you are downloading?

**Comment by HHHit** [comment]
Thanks for the quick reply! I am downloading using mip=4, and I am trying to download the Microns dataset m343 
precomputed://gs://iarpa_microns/minnie/minnie65/seg_m343

**Comment by william-silversmith** [comment]
Thank you! I can reproduce this and will look into it.

**Comment by HHHit** [comment]
Thanks a lot!

**Comment by william-silversmith** [comment]
This is released in 8.19.1. Thanks for reporting! Floating point voxel_offsets with non-zero decimals are not yet supported.
