### ISSUE TITLE
Why are my data chunks in `.gz` format?

### ISSUE THREAD

**Issue by jasper-tms** [seung-lab/cloud-volume#578]
Hi Will, I'm trying to create local precomputed datasets for the first time (I've always done Google Cloud-backed datasets previously), and I think I have some parameter wrong but I can't figure out which one. Here's how I'm making a new cloudvolume:

```python
volume_size = [5940, 11496, 7843]
voxel_size = 75
precomputed_path = 'file:///mnt/radagast_ssd_v1/fly_leg_xnh/180917_sample5GadNLSfemale/fly_leg_sample5_stitched'

info = CloudVolume.create_new_info(
    num_channels = 1,
    layer_type = 'image',
    data_type = 'uint8',
    encoding = 'raw',
    resolution = [voxel_size, voxel_size, voxel_size],
    voxel_offset = [0, 0, 0],
    chunk_size = [64, 64, 64],
    volume_size = volume_size,
)
vol = CloudVolume(precomputed_path, info=info)
vol.commit_info()
```
I'm then iterating over some chunks of a zarr file, swapping around some axes, and saving the data to the precomputed volume:
```python
<some for loops over x y and z>
    data = zarray[z:z+chunk_size, y:y+chunk_size, x:x+chunk_size]
    vol[y:y+chunk_size, x:x+chunk_size, z:z+chunk_size] = data.T.swapaxes(0, 1)
```

Oddly I'm seeing that all of the binary data files in my `75_75_75/` subfolder have `.gz` extensions. I'm able to open this precomputed data again through CloudVolume, so it must be in a format that CloudVolume knows how to process, but I can't visualize it in neuroglancer/neuromancer, e.g. [neuromancer link](https://neuromancer-seung-import.appspot.com/#!%7B%22layers%22:%5B%7B%22source%22:%22precomputed://https://radagast.hms.harvard.edu/ssd_v1/fly_leg_xnh/180917_sample5GadNLSfemale/fly_leg_sample5_stitched%22%2C%22type%22:%22image%22%2C%22blend%22:%22default%22%2C%22shaderControls%22:%7B%7D%2C%22name%22:%22fly_leg_sample5_stitched%22%7D%5D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B75%2C75%2C75%5D%2C%22voxelCoordinates%22:%5B1374.9854736328125%2C1099.44091796875%2C4097%5D%7D%7D%2C%22zoomFactor%22:1.5643777068911031%7D%2C%22layout%22:%22xy%22%7D) gives `Access to fetch at 'https://radagast.hms.harvard.edu/ssd_v1/fly_leg_xnh/180917_sample5GadNLSfemale/fly_leg_sample5_stitched/75_75_75/1216-1280_960-1024_4096-4160' from origin 'https://neuromancer-seung-import.appspot.com' has been blocked by CORS policy`. This seems to be because it's looking for a file without the `.gz` extension. (I don't think it's actually a CORS issue – here's [another precomputed volume](https://neuromancer-seung-import.appspot.com/#!%7B%22layers%22:%5B%7B%22source%22:%22precomputed://https://radagast.hms.harvard.edu/ssd_v1/fly_leg_xnh/180917_sample2GadNLSfemale/unaligned_volumes/120nm_down/reconstruction1_2018%22%2C%22type%22:%22image%22%2C%22blend%22:%22default%22%2C%22shaderControls%22:%7B%7D%2C%22name%22:%22reconstruction1_2018%22%7D%5D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B120%2C120%2C120%5D%2C%22voxelCoordinates%22:%5B1586.078125%2C1583.7574462890625%2C1600%5D%7D%7D%2C%22zoomFactor%22:676.878469011398%7D%2C%22layout%22:%224panel%22%7D) in the same folder on my server, and it loads fine, but this one doesn't have `.gz` formatted chunks).

The info file of my dataset looks fine – encoding is raw, not gzip, so I'm not sure what I'm missing:
```bash
$ cat info 
{
  "data_type": "uint8",
  "num_channels": 1,
  "scales": [
    {
      "chunk_sizes": [
        [
          64,
          64,
          64
        ]
      ],
      "encoding": "raw",
      "key": "75_75_75",
      "resolution": [
        75,
        75,
        75
      ],
      "size": [
        5940,
        11496,
        7843
      ],
      "voxel_offset": [
        0,
        0,
        0
      ]
    }
  ],
  "type": "image"
}
```

I hope I'm just missing some bool parameter somewhere that I need to flip, but sorry I haven't been able to find it myself.

I'm using cloud-volume 8.19.2 from PyPI, python 3.9.13, and Ubuntu 18.04.

Thanks a lot!

**Comment by william-silversmith** [comment]
Hi Jasper, the filesystem doesn't store the encoding type so we use a file
extension to note which bitstream compression type is in use. Cloudvolume
and cloudfiles know how to handle the conversion.

Use cv.viewer() or the igneous view command to start a local server that
can communicate with Neuroglancer.

Will

**Comment by jasper-tms** [comment]
Hi Will,

My goal is to have a precomputed volume on my server that I can serve over https to a web app like https://neuromancer-seung-import.appspot.com/. If I first make my precomputed volume on google cloud storage, then rsync that to my server, I get a local precomputed dataset in a format that works for this. (The second link in my first post was made this way.) Is there a way to make this happen without this hack of first saving the volume on google cloud storage?

**Comment by william-silversmith** [comment]
Hi Jasper,

Sorry this issue is creeping up again! The filesystem has no way to tell
Neuroglancer that the files are encoded with gzip, which is embedded in the
"Content-Encoding" HTTP metadata. If you use the CloudVolume server, which
is file extension aware, Neuroglancer can read from that server
(precomputed://http://localhost:1337). Alternatively, you can configure
your web server to strip .gz suffixes and put "gzip" in the
"Content-Encoding" field.

You can read more in this previous issue here:
https://github.com/seung-lab/cloud-volume/issues/432

Will

**Comment by jasper-tms** [comment]
This dataset isn't that big and I'd be perfectly fine not gzipping my files here. In fact, it looks like when I `gsutil cp`ed a cloudvolume from google cloud to my server, `gsutil` unzipped the files and saved them as raw, which is why I was then able to serve my local copy of the precomputed volume directly to neuroglancer.

Looks like the answer to my questions is that I needed to include `compress=False` in my CloudVolume constructor. I was expecting `encoding="raw"` in the info file to be enough, and my confusion arose from the fact that I was wrong about that. After figuring this out, I'm now happily converting my zarr to uncompressed precomputed format, and the first link in my initial post now shows data. Thanks for the help figuring this out!
