### ISSUE TITLE
How do I set up a secret file to access password protected file?

### ISSUE THREAD

**Issue by manoaman** [seung-lab/cloud-volume#581]
Hi @william-silversmith ,

In the example, I do see various ways to set up a secret file to access Cloud storages.
https://github.com/seung-lab/cloud-volume#credentials

Do you have an example of setting up a plain secret for simple basic authentication done on Apache/Nginx servers which require a user name and a password?  I wasn't quite sure if the json file can be set up as the following?

(json)
```
{
  "username": "<username>",
  "password": "<pass>"
}
```

(Local)
```
# ~/.cloudvolume/secrets/file-server.com.json
cv = CloudVolume(..., secrets="file-server.com.json")
```

(Kaggle notebook)
```
# /kaggle/input/file-server.com.json
cv = CloudVolume(..., secrets="/kaggle/input/file-server.com.json")
```

Can you guide me the correct way to configure?

Thank you,
-m

**Comment by william-silversmith** [comment]
Hi m,

At the moment we don't have support for http basic auth. Is it possible to set your volume to public read? 

We support reading from some servers with http, but we don't have support for writing to http. There's a lot of different protocols and I'm not sure which ones to implement?

If you can tell me more about your situation, that would be helpful!

Will

**Comment by manoaman** [comment]
Hi Will,

Yes, for the public read, I was able to run CloudVolume without a problem.  I'm specifically interested in read operation as described in [example](https://github.com/seung-lab/cloud-volume/wiki/Reading-Public-Data-Examples) and [example](https://neurodata.io/data/allen_atlas/).  Not writing to the storage at the moment.  The difference from this example is that I'd like to access the data in `precomputed://(http|https)://<domain name>/precomputed_path` format.  There are instances when I would like to allow only to the limited number of people to access the files hosted on the legacy file server with pass protection on http protocols. (http, https). 

-m

**Comment by william-silversmith** [comment]
Hi m,

I'm a bit occupied at the moment to develop a full solution today, but I think this might give you enough to get started.

https://github.com/seung-lab/cloud-files/blob/master/cloudfiles/interfaces.py#L631

I think if you follow this StackOverflow post: 

https://stackoverflow.com/questions/26745462/how-do-i-use-basic-http-authentication-with-the-python-requests-library

You can set `resp = requests.get(key, headers=headers, auth=requests.HTTPBasicAuth(USER, PASSWORD))` manually and see if that works for you. Let me know if that does what you need and we can discuss a more official version.

Will

**Comment by manoaman** [comment]
Hi Will,

Modification on `interfaces.py` seems to work.
https://github.com/seung-lab/cloud-files/blob/master/cloudfiles/interfaces.py#L624

```
 @retry
  def get_file(self, file_path, start=None, end=None):
    key = self.get_path_to_file(file_path)

    print(f'Key is.....{key}')
    session = requests.Session()
    session.auth = ('xxxxxxxx','xxxxxxxx')

    if start is not None or end is not None:
      start = int(start) if start is not None else 0
      end = int(end - 1) if end is not None else ''
      headers = { "Range": "bytes={}-{}".format(start, end) }
      # resp = requests.get(key, headers=headers)
      resp = session.get(key, headers=headers)
    else:
      # resp = requests.get(key)
      resp = session.get(key)
```

**Comment by william-silversmith** [comment]
Interesting! I wonder if we get a performance benefit from using a session object. I will take a look into integrating something like this when I have a moment.

**Comment by manoaman** [comment]
Thank you @william-silversmith !  It will be useful feature to have at the moment.

**Comment by william-silversmith** [comment]
Hi m,

Check out this version of CloudFiles and let me know if this does what you need:

https://github.com/seung-lab/cloud-files/pull/82

**Comment by manoaman** [comment]
Hi @william-silversmith ,

I'm sorry for my late reply.  Had a busy week..

I saw the changes and look great to me.  One correction I made is modified this line to explicitly add self to reference the session object. [correcting](https://github.com/seung-lab/cloud-files/blob/8961fab44be4391ecfead1e0fc334139b1cf2f66/cloudfiles/interfaces.py#L607) 

```
      self.session.auth = (secrets['user'], secrets['password'])
```

Otherwise, the script saved a mesh object without any issues.  Would this version become available on pip?

Thank you so much!
-m

**Comment by william-silversmith** [comment]
Hi m!

I just pushed a fix and will release this version soon with a few other goodies.

**Comment by manoaman** [comment]
Thank you @william-silversmith !!!

**Comment by william-silversmith** [comment]
Hi m,

I forgot to mention, the newest release of CloudFiles has this capability now.

Thanks for writing in!
