### ISSUE TITLE
How can I add an precomputed annotation layer?

### ISSUE THREAD

**Issue by liuyx599** [seung-lab/cloud-volume#583]
Through the readme tutorial, I was able to successfully establish precomputed image layers and segmentation layers and visualize them in the neuroglancer. Now I have an `annotation_points.txt` file records the coordinate positions (x, y, z) of key points (or rather special skeleton nodes) of segments with different IDs in the segmentation. How can I visualize key point information with different IDs based on existing layers. In other words, how should I add an annotation layer that I can select segments with different IDs in the neuroglancer and display the key points in the corresponding segment, rather than all the points being displayed.

```python
def create_image_layer(destination, shape, pos=(0,0,0), resolution=[16,16,40], image_layer=False):
    data_type = "uint64"
    layer_type = "segmentation"

    info = CloudVolume.create_new_info(
        num_channels 	= 1,
        layer_type	=  layer_type,
        data_type	=  data_type,   
        encoding	= 'raw',
        resolution	= resolution,
        voxel_offset = pos,
        mesh  = 'mesh',
        chunk_size	= [64, 64, 16],
        volume_size	= shape
    )

    vol = CloudVolume(destination, compress=False, info=info, parallel=False)  # 默认为True
    print(vol.info)
    vol.commit_info()
    return vol

source_path = r'./demo.h5'     # segmentation results
img = readh5(source_path)
target_path = r'precomputed://file:///usr/home/demo'
vol = create_image_layer(target_path, img.shape, pos=(0,0,0), resolution=[4,4,40], image_layer=image_layer)
vol[:,:,:,0] = img[:,:,:]
```

Some of the contents in my key point information file `annotation_points.txt` are as follows, each row represents a key node coordinate.
```
835.000000,710.000000,2.000000
670.000000,570.000000,6.000000
838.000000,690.000000,5.000000
830.000000,650.000000,7.000000
830.000000,669.000000,8.000000
750.000000,582.000000,8.000000
830.000000,630.000000,13.000000
810.000000,600.000000,18.000000
790.000000,590.000000,21.000000
790.000000,590.000000,25.000000
....
```

**Comment by william-silversmith** [comment]
Hi! Unfortunately, CloudVolume does not yet support annotations. I have been meaning to add this support, but other projects keep getting in the way. Would be happy to help someone add a PR!

**Comment by liuyx599** [comment]
Can I convert my txt file into an SWC file and add a skeleton layer? I think my key point information is essentially the nodes of the skeleton, but there is no information such as radius or parent-child node relationships. If I could change my approach and add a skeleton layer, how should I proceed

**Comment by william-silversmith** [comment]
That would work, but in order to see anything, I *think* you'd need to have parents hooked up, but that might have changed in newer versions of neuroglancer. You can try it without them first.

Use `cv.skeleton.meta` functions to upload a skeleton info file. Strip off the default attributes. Then, once you convert to an SWC:

```python
from cloudvolume import Skeleton

skel = Skeleton.from_swc(swc_text)
skel.id = 1
cv.skeleton.upload(skel)
```

**Comment by william-silversmith** [comment]
You can also check out this repo which might have annotation capabilities. I haven't used it though.

https://github.com/BrainCOGS/precomputed_annotations

**Comment by liuyx599** [comment]
I won't add annotations layer, instead of adding a skeleton layer, according to your code strategy, I added the following skeleton layers under the vol of the segmentation layer above my codes. However, how should I write the skeleton's `info` file
```python
    swc_file= 'sample.swc'
    raw_file = open(swc_file ,'r')
    swc_text = raw_file.read()

    skel = Skeleton.from_swc(swc_text)
    skel.id = 1
    vol.skeleton.upload(skel)
```
examples of my demo.swc:
the swc format
1 | 2 | 3 | 4 |5 |6 | 7
-- | -- | -- | -- | -- | -- | --
Sample number | Structure Identifier | x position | y position | z position | radius | parent sample
```
0 0 290.0 10.0 5.0 1.0 -1
1 0 10.0 290.0 3.0 1.0 -1
2 6 5.0 1110.0 5.0 1.0 -1
3 6 5.0 1110.0 6.0 1.0 -1
4 0 880.0 690.0 112.0 1.0 -1
5 0 867.0 1205.0 112.0 1.0 -1
6 0 668.0 1240.0 112.0 1.0 -1
7 6 10.0 90.0 109.0 1.0 -1
8 0 10.0 70.0 111.0 1.0 -1
9 0 10.0 70.0 113.0 1.0 -1
...
```

The file structure of the usr/home/demo directory is as follows
-4_4_40
-info
-skeletons
  --1
when I tried add skeletons in neuroglancer, it reported usr/home/demo/skeletons/info resulted in HTTP error 404:Not found
