### ISSUE TITLE
cv.download and cv.download_point shift to the next full multiple of 128

### ISSUE THREAD

**Issue by Lauenburg** [seung-lab/cloud-volume#589]
**Issue**

I am experiencing issues when trying to crop out subvolumes from the H01 dataset. The bounding boxes I use are always shifted to the next full multiple of 128 in the x and y directions and the next multiple of 32 in the z direction. This leads to two potential issues:

1. The shifted location (sub-volume) might be empty, resulting in an `EmptyVolumeException`.
2. I have to adjust my bounding box to match the 128x128x32 steps. This means I am downloading a considerably larger subvolume than required, and the center of the volume is shifted such that the observed instance might even be partially out of view. As a result, I have to crop out an even larger subvolume and perform local post-processing.

**Question**

Is it expected behavior that the `download` and `download_point` functions do not allow me to download arbitrary subvolumes, but only multiples of 128x128x32?

**Elaboration**

I am attempting to retrieve subvolumes from the following locations:

- gs://h01-release/data/20210601/c3
- gs://h01-release/data/20210729/c3/synapses/whole_ei_onlyvol

I want to visualize these subvolumes in a tool for proofreading. I have tried using both the `download` and `download_point` functions.

For the download function, here is an example code snippet I have used:

- `download`
```python
# Map the bounding box coordinates to a dictionary
crop_box_dict = {
    'z1': crop_bbox[0],
    'z2': crop_bbox[1],
    'y1': crop_bbox[2],
    'y2': crop_bbox[3],
    'x1': crop_bbox[4],
    'x2': crop_bbox[5]
}

# Retrieve the order of the coordinates (xyz, xzy, yxz, yzx, zxy, zyx)
cord_order = list(synanno.coordinate_order.keys())

# Create the bounding box for the current synapse
bound = Bbox(
    [
        crop_box_dict[cord_order[0] + '1'],
        crop_box_dict[cord_order[1] + '1'],
        crop_box_dict[cord_order[2] + '1']
    ],
    [
        crop_box_dict[cord_order[0] + '2'],
        crop_box_dict[cord_order[1] + '2'],
        crop_box_dict[cord_order[2] + '2']
    ]
)

# Convert coordinate resolution values to integers
coord_resolution = [int(res) for res in synanno.coordinate_order.values()]

# Retrieve the source and target images from the cloud volume
cropped_img = synanno.source_cv.download(bound, coord_resolution=coord_resolution, mip=0)
cropped_gt = synanno.target_cv.download(bound, coord_resolution=coord_resolution, mip=0)
```

For the download_point function, here is an example code snippet I have used:

```python
  # Retrieve the order of the coordinates (xyz, xzy, yxz, yzx, zxy, zyx)
  cord_order = list(synanno.coordinate_order.keys())

  # Convert coordinate resolution values to integers
  coord_resolution = [int(res) for res in synanno.coordinate_order.values()]

  # Retrieve the source and target images from the cloud volume
  size = {'x':128, 'y':128, 'z':32}
  size_order = [size[cord_order[0]], size[cord_order[1]], size[cord_order[2]]]
  point = [bbox_dict[idx][cord_order[0]], bbox_dict[idx][cord_order[1]], bbox_dict[idx][cord_order[2]]]
  cropped_img = synanno.source_cv.download_point(point, size=size_order, coord_resolution=coord_resolution, mip=0)          
  cropped_gt = synanno.target_cv.download_point(point, size=size_order, coord_resolution=coord_resolution, mip=0)
```

**Comment by william-silversmith** [comment]
Hi! Have you tried setting `CloudVolume(..., fill_missing=True)`? This fills the empty chunks with zeros.

**Comment by Lauenburg** [comment]
Amazing! That was just what I needed. Thank you so much!!!
