### ISSUE TITLE
Problem with Downloading Graphene Meshes

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/cloud-volume#590]
@akhileshh I think I might need help figuring out what the right fix is here.

When downloading a graphene mesh with the below code, different results are had with CV 8.10 and the latest version. I've tracked this down to our changes in https://github.com/seung-lab/cloud-volume/pull/567 and its bugfix changes.

The issue seems to be that level 10 is requested prior to that change, but it gets punted down to level 6 from the max_meshed_layer. Is this a problem with CloudVolume, a server misconfiguration, or is the new code right? The new code omits the cell body though. (!)

```python
import cloudvolume
vol = cloudvolume.CloudVolume(
	'graphene://https://prodv1.flywire-daf.com/segmentation/1.0/fly_v31', 
	use_https=True
)
segid = 720575940634984800
m = vol.mesh.get([segid])[segid]
with open(f"{segid}.obj", "wb") as f:
	f.write(m.to_obj())
```

**Comment by akhileshh** [comment]
Looks like this might be a server issue. The manifest generation in v1 chunkedgraph is not the same as v2, I think it is missing fragments because of skip connections.

**Comment by william-silversmith** [comment]
The fix for v1 should be deployed per Akhilesh. Thank you!
