### ISSUE TITLE
Cloud volume that is made on linux machine does not open in neuroglancer in safari

### ISSUE THREAD

**Issue by copypasteearth** [seung-lab/cloud-volume#591]
Hello,

I am running a server on a linux machine that saves cloud volumes from images so they can be opened in neuroglancer, the problem is that if I run the server locally on my MacOS machine everything works fine, but if I deploy to a linux machine there is errors reading the chuncks in safari. could this be a server configuration issue? Everything loads fine in chrome, but when i try safari i get these errors
<img width="749" alt="chuncks" src="https://github.com/seung-lab/cloud-volume/assets/6181334/31fbe9a3-5090-4c9a-bcb4-0a5f60787ee3">

**Comment by william-silversmith** [comment]
Hi! How are you serving the chunks? It kind of looks like the chunks are gzipped and are not being served correctly.

CloudVolume includes a server that understands how to read `.gz` files. 

https://github.com/seung-lab/cloud-volume#viewing-a-precomputed-volume-on-disk

**Comment by copypasteearth** [comment]
@william-silversmith I am using a flask server with a GET endpoint and serving the .gz files directly. Should I be wrapping those files with something?

**Comment by william-silversmith** [comment]
Try using the CloudVolume server and see if that works for you. Neuroglancer does not understand the .gz extension. You need to strip it and correctly assign "Content-Encoding: gzip: in the header.

**Comment by copypasteearth** [comment]
@william-silversmith I cannot use the built in server. We are using a custom neuroglancer. In chrome everything works fine. It just won't work in safari

**Comment by william-silversmith** [comment]
Is your server accessible from the internet?

**Comment by copypasteearth** [comment]
Yes

**Comment by copypasteearth** [comment]
If I go to the GET url for a chunk, in chrome it downloads the .gz file whole but in safari it downloads the file without the .gz extension and its contents are just a bunch of numbers an dashes

**Comment by william-silversmith** [comment]
I was thinking more can you share the URL? Otherwise it's a bit hard to debug. I would recommend checking the headers on the requests in safari and looking to see if there are differneces.

**Comment by copypasteearth** [comment]
Sorry I cannot share the url. It works fine when I am running the webserver locally on my Mac, but when I run it on Linux then I have the problem. It is an Apache airflow server on a docker compose image

**Comment by william-silversmith** [comment]
If you can share the headers on the same request in Chrome and Safari, that might be helpful.

**Comment by copypasteearth** [comment]
Here is safari

`Request
GET /api/v1/imaging_suite/data/precomputed_volumes/CDF75295-5F86-498A-883F-49F5224B911E/Control/Sample_1/uCT//decal/13530.0_13530.0_13530.0/768-896_640-768_0-2 HTTP/1.1
Accept: /
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: my server
Origin: https://neuroglancer-demo.appspot.com
Referer: https://neuroglancer-demo.appspot.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15

Response
HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://neuroglancer-demo.appspot.com
Cache-Control: no-cache
Connection: close
Content-Disposition: inline; filename=768-896_640-768_0-2.gz
Content-Encoding: gzip
Content-Length: 6741
Content-Type: application/octet-stream
Date: Mon, 17 Jul 2023 22:53:16 GMT
ETag: "1689631189.5351033-6741-3579390298"
Last-Modified: Mon, 17 Jul 2023 21:59:49 GMT
Server: gunicorn
Set-Cookie: session=d19e6c6b-e3d8-4bdf-8394-b571c1a4011c.8cZSRs7XbDV075s7LufjVG0xKDg; Expires=Wed, 16 Aug 2023 22:53:16 GMT; HttpOnly; Path=/; SameSite=Lax
Vary: Origin
X-Robots-Tag: noindex, nofollow`

**Comment by william-silversmith** [comment]
Potentially a problem:

`Content-Disposition: inline; filename=768-896_640-768_0-2.gz` 

I'm not sure how that affects Neuroglancer.

As a hack, you can gunzip all the files in your image and see if that fixes things. Another approach is to try encoding your images as PNG or JPEG which will avoid the gzip issue.

**Comment by copypasteearth** [comment]
@william-silversmith stripping the Content-Disposition from the response headers fixed the problem, Thank you
