### ISSUE TITLE
Downloading H01's 4nm_raw Retrieves Only Zeros, Despite Non-Zero Contents in NG

### ISSUE THREAD

**Issue by Lauenburg** [seung-lab/cloud-volume#594]
**Issue:** 

Subvolumes downloaded from the [gs://h01-release/data/20210601/4nm_raw](gs://h01-release/data/20210601/4nm_raw) (sourced from the [H01 release page](https://h01-release.storage.googleapis.com/data.html)) are found to contain only zeros. When visualized using Neuroglancer's (NG) live demo, these volumes also appear as all-zero/black. 

However, interestingly, when 'Create as Image Layer' option is selected in NG, the electron microscopy (EM) data is correctly rendered, indicating non-zero values in the volume. 

**How to reproduce this issue:**

Below is the minimal code to reproduce this issue:

```python
from cloudvolume import CloudVolume, view

cv = CloudVolume('https://storage.googleapis.com/h01-release/data/20210601/4nm_raw')
img = cv.download_point((256696, 199480, 2002), mip=0, size=(512, 512, 64))
view(img)
```

**Question:**

How can I retrieve the non-zero information in these volumes using CloudVolume, in the same way Neuroglancer does when creating an image layer?

**Additional Information:**

1. [Link to Neuroglancer view showing zero content](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B3.3e-8%2C%22m%22%5D%7D%2C%22position%22:%5B515874.875%2C356234.90625%2C2664.495361328125%5D%2C%22crossSectionScale%22:1%2C%22projectionScale%22:1048576%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210729/c3/synapses/whole_ei_onlyvol%22%2C%22tab%22:%22source%22%2C%22segments%22:%5B%5D%2C%22name%22:%22whole_ei_onlyvol%22%7D%2C%7B%22type%22:%22new%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210601/4nm_raw%22%2C%22tab%22:%22source%22%2C%22name%22:%224nm_raw%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%224nm_raw%22%7D%2C%22layout%22:%224panel%22%2C%22layerListPanel%22:%7B%22visible%22:true%7D%7D)

2. [Link to Neuroglancer view after 'Create as Image Layer' operation](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B3.3e-8%2C%22m%22%5D%7D%2C%22position%22:%5B515874.875%2C356234.90625%2C2664.495361328125%5D%2C%22crossSectionScale%22:1%2C%22projectionScale%22:1048576%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210729/c3/synapses/whole_ei_onlyvol%22%2C%22tab%22:%22source%22%2C%22segments%22:%5B%5D%2C%22name%22:%22whole_ei_onlyvol%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210601/4nm_raw%22%2C%22tab%22:%22source%22%2C%22name%22:%224nm_raw%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%224nm_raw%22%7D%2C%22layout%22:%224panel%22%2C%22layerListPanel%22:%7B%22visible%22:true%7D%7D)

**Comment by fcollman** [comment]
- When you use the coordinates you provided, you end up in a black section of the [imagery](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B3.3e-8%2C%22m%22%5D%7D%2C%22position%22:%5B256696.5%2C199480.5%2C2002.5%5D%2C%22crossSectionScale%22:1%2C%22projectionScale%22:1048576%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210729/c3/synapses/whole_ei_onlyvol%22%2C%22tab%22:%22source%22%2C%22segments%22:%5B%5D%2C%22name%22:%22whole_ei_onlyvol%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://h01-release/data/20210601/4nm_raw%22%2C%22tab%22:%22source%22%2C%22name%22:%224nm_raw%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%224nm_raw%22%7D%2C%22layout%22:%224panel%22%2C%22layerListPanel%22:%7B%22visible%22:true%7D%7D)

however, when you use the coordinates you provided in your neuroglancer links everything works as designed.
515874, 356234, 2664

I suspect you might be confused because in some neuroglancer views there is a disconnect between the resolution of the imagery and/or segmentation data at mip0 and the resolution specified in the neuroglancer view.  So the neuroglancer view might be in 4,4,40 for example, but mip0 has a resolution of 8,8,40.  Cloudvolume allows you to specified the coordinate resolution you are giving in download_point using the coord_resolution keyword argument to help automated this conversion.

**Comment by Lauenburg** [comment]
Thank you for your quick response! Indeed, I find myself a bit puzzled. How can I determine the correct mip0 resolution? The H01 release page indicates a 4nm * 4nm * 33nm resolution for `4nm_raw`, and `CloudVolume('https://storage.googleapis.com/h01-release/data/20210601/4nm_raw').info` returns `'key': '4.0x4.0x33.0', 'resolution': [4, 4, 33]`. Consequently, I wouldn't have presumed to set `coord_resolution` to `8,8,40`.

Moreover, my ultimate goal is to extract identical subvolumes from `4nm_raw` and `whole_ei_onlyvol`, maintaining the same size and location for the purpose of overlaying them. Naively, I would approach it like this:

```python
bound = Bbox([290261, 114472, 248],[290403, 114614, 264], dtype=int32) # range (142, 142, 16)
# Extract source and target images from CloudVolume
cropped_img = 4nm_raw.download(bound, coord_resolution=[8,8,40], mip=0)  # Yields subvolume of shape (284, 284, 20, 1) given the real resolution of 4nm_raw is [4,4,33]
cropped_gt = whole_ei_onlyvol.download(bound, coord_resolution=[8,8,33], mip=0)  # Yields subvolume of shape (142, 142, 16, 1), given the real resolution of whole_ei_onlyvol is [8,8,33]
```

Yet, the code above results in differently-sized cropouts, and the locations also do not match. Currently, I would adjust the coordinates for alignment and downsample the larger subvolume like this:

```python
# Downsample cropped_img to match cropped_gt
resized_img = resize(cropped_img, cropped_gt.shape, mode='reflect', anti_aliasing=True)
```

However, I'm convinced there's a better method. Could you guide me to relevant resources or share how you would approach this?

**Comment by fcollman** [comment]
Where did those 8,8,40 numbers come from? As you said.. the neuroglancer view was in 4,4,40, the cloud-volume mip0 tells you it is in 4,4,40, so both of those locations were giving accurate metadata along with their numbers. 

Where ever the 8,8,40 numbers came from should have done the same.  If you have coordinates without that resolution metadata they aren't ever going to be interpretable.

**Comment by william-silversmith** [comment]
The correct resolution to use for `coord_resolution` is the one that appears in Neuroglancer. I examined the info file for the segmentation, and it appears to be in 8x8x33 nm just like the image. I think Forrest was giving a generic example (most of our data is in 4x4x40 or 8x8x40). 

Here is how I might go about this:

```python
from cloudvolume import CloudVolume, Bbox
import numpy as np
import microviewer

cv_seg = CloudVolume("precomputed://gs://h01-release/data/20210729/c3/synapses/whole_ei_onlyvol", mip=[8,8,33], use_https=True, fill_missing=True)
cv_img = CloudVolume("precomputed://gs://h01-release/data/20210601/4nm_raw", use_https=True, mip=[8,8,33])

bound = Bbox([515873, 356279, 2657],[515873+512, 356279+512, 2657+64], dtype=np.int32) 
labels = cv_seg.download(bound, coord_resolution=[4,4,33])
image = cv_img.download(bound, coord_resolution=[4,4,33])

microviewer.hyperview(image, labels)
```

**Comment by fcollman** [comment]
Ah. I see, yes... what Will said above is right.  

Note that I think that hyperview is using the metadata that is attached to labels and image to make sure that the data is easy to visually overlay even if it's in different resolutions.. so if you are expecting data that is the same shape and trivially overlays this solution isn't going to give you that, you have to do some interpolation.

**Comment by fcollman** [comment]
ah sorry.. no .. Will's solution was to download the imagery also at 8,8,33.  

I don't think this is ideal for your application. 

Casey tried to develop some tooling on top of cloud-volume to handle this for making trivial overlays in matplotlib
(https://github.com/AllenInstitute/ImageryClient), but really I think that a visualization pipeline that draws the lower resolution data using lower resolution pixels and the higher resolution with higher pixels makes the most sense.

**Comment by william-silversmith** [comment]
Yea, if you want to use the 4nm images, you'll have to upsample the segmentation by 2x in X and Y.

**Comment by william-silversmith** [comment]
The low res segmentation drawing would be a neat microviewer feature. Will consider it for the future!

**Comment by Lauenburg** [comment]
Thank you for the extended elaboration. To summarise and clear up any possible misunderstandings:

- ### Recommended Practices - Suggested Solution

If I understand correctly, your advice for my situation is to download both volumes in their original resolution, then downsample or upsample the segmentation to match the image data's resolution? So, I would do something like this:

```python
from cloudvolume import CloudVolume, Bbox
import numpy as np
from skimage.transform import resize
import microviewer

# Define the CloudVolume instances
cv_seg = CloudVolume("precomputed://gs://h01-release/data/20210729/c3/synapses/whole_ei_onlyvol", use_https=True, fill_missing=True)
cv_img = CloudVolume("precomputed://gs://h01-release/data/20210601/4nm_raw", use_https=True)

# Compute the scaling factor
seg_res, img_res = np.array(cv_seg.info['scales'][0]['resolution']), np.array(cv_img.info['scales'][0]['resolution'])
scale = np.where(seg_res/img_res > 0, seg_res/img_res, 1)

# Define the bounding boxes
bound_labels = Bbox([257936, 178139, 1328], [257936+512, 178139+512, 1328+64], dtype=np.int32)
bound_image = Bbox((bound_labels.minpt * scale).astype(int), (bound_labels.maxpt * scale).astype(int))

# Download the data in its actual resolutionlabels = np.squeeze(cv_seg.download(bound_labels, coord_resolution=seg_res))
image = np.squeeze(cv_img.download(bound_image, coord_resolution=img_res))

# Adjust the scale of the label volume
if sum(image.shape) > sum(labels.shape): # up-sampling
    labels = resize(labels, image.shape, mode='constant', preserve_range=True, anti_aliasing=False)
elif sum(image.shape) < sum(labels.shape): # down-sampling
    labels = resize(labels, image.shape, mode='constant', preserve_range=True, anti_aliasing=True)

# View the images
microviewer.hyperview(image, labels)
```

- ### Regarding the argument`coord_resolution`

Will, you stated that:

> The correct resolution to use for `coord_resolution` is the one that appears in Neuroglancer (NG).

The doc string of the [download_point](https://github.com/seung-lab/cloud-volume/blob/29124b4950dc9cb29bbe9e2ad63d5505c1b687e3/cloudvolume/frontends/graphene.py#L150) function states:

> coord_resolution: (rx,ry,rz) the coordinate resolution of the input point. Sometimes Neuroglancer is working in the resolution of another higher res layer, and this can help correct that.

Based on your statement, Will, I'd set the coordinate resolution to the resolution shown in NG. But, based on the docstring and what I understand by "coordinate resolution", I'd set the coordinate resolution to the actual resolution of the dataset I've loaded.
 
However, then again, in your example, you download both volumes in the same resolution by setting the voxel resolution to `mip=[8,8,33]`, effectively downsampling the image volume, and then set `coord_resolution` to the resolution specified in the NG. Thus, I would deduce that the `coord_resolution` should always be set to the resolution depicted in the NG.

**Is it possible to foresee this resolution without first manually loading and viewing a volume in the NG?**

- ### Regarding the resolution of the image volume

@william-silversmith, you mentioned:

> I examined the info file for the segmentation, and it appears to be in 8x8x33 nm, just like the image.

However, doesn't the info file for the image volume (4nm_raw) state a resolution of 4x4x33? At least, that's what it says on my end.

**Comment by fcollman** [comment]
When you pass coordinates to download_point, you should pass the coord_resolution of those coordinates.  If those coordinates came from a neuroglancer view at 4,4,33, then coord_resolution should be 4,4,33.  If they came from coordinates in a segmentation mask that was at 8,8,33 then coord_resolution should be 8,8,33.  Download point is a method on the cloudvolume object, so all it is doing is comparing the resolution of the mip you configured that cloudvolume object to use to the coord_resolution you passed. If there is a mismatch, it will do the conversion for you to convert the positions you passed to the appropriate units for downloading the data. 

So what is the correct thing to do depends ultimately on what the source of your coordinates is.  I hope that clarifies things!

**Comment by Lauenburg** [comment]
@fcollman, thanks for the clarification! Considering your input, I think the above solution should be adequate. It adjusts the coordinates to match the resolution of the specific datasets and accordingly sets the coord_resolution to the individual resolution of these datasets.
