### ISSUE TITLE
Using frangi filter SimpleItk results in empty segmentation

### ISSUE THREAD

**Issue by copypasteearth** [seung-lab/cloud-volume#599]
Hi I am using SimpleItk ObjectnessMeasure for frangi filtering. So if I view one slice I can see the result with pyplot so I know the filter is working. But when I save the image as a segmentation, it is an empty volume. Any ideas?

**Comment by william-silversmith** [comment]
Hi! Can you share a snippet of the code you are using? It'd be helpful to know the dimensions, data type, and info file as well.

**Comment by copypasteearth** [comment]
It was a problem in how i am doing it, closing
