### ISSUE TITLE
Is there a way to get points from a segmentation

### ISSUE THREAD

**Issue by copypasteearth** [seung-lab/cloud-volume#601]
Hello, i am trying to do a concave hull on a segmentation, but I see the alphashape 1.3.1 pyhton library takes in points. Is there some way to get the points of a segmentation from cloud volume somehow?

**Comment by fcollman** [comment]
If the segmentation has a mesh that would be the fastest way.. see cv.mesh.get for small volumes you could download the whole voxel version or iterate over chunks and download and mask to get coordinates of positive voxels, but that would be very intensive and slow.

**Comment by william-silversmith** [comment]
For small volumes, mesh with https://github.com/seung-lab/zmesh and get the vertices. Alternatively, use https://github.com/seung-lab/connected-components-3d/ `cc3d.contacts`. 

Otherwise, I suggest what Forrest said.
