### ISSUE TITLE
Load BossDB S3 URI Error

### ISSUE THREAD

**Issue by JackieZhai** [seung-lab/cloud-volume#604]
Hi Will @william-silversmith, 

When I tried to load BossDB datasets by CloudVolume, there are some errors about “compress_level”:

```Shell
>>> vol = CloudVolume('boss://s3://iarpa_microns/minnie/minnie35/em')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haozhai/anaconda3/envs/Connect/lib/python3.8/site-packages/cloudvolume/cloudvolume.py", line 233, in __new__
    return REGISTERED_PLUGINS[path.format](**kwargs)
TypeError: create_boss() got an unexpected keyword argument 'compress_level'
```

I'm guessing this might be due to an issue with `intern`'s version control? But I'm not sure.
If you have any idea, please tell me.

Best wishes,
Hao (Jackie) Zhai.

**Comment by JackieZhai** [comment]
By the way, is there a way to download a complete BossDB dataset?
Is `igneous-pipeline` or specifically `igneous image xfer` supported to do that?

Thanks a lot!

**Comment by william-silversmith** [comment]
Hi!

The BOSS connector hasn't been used by myself in a while so you likely ran
into a snag.

However, I believe the dataset you are trying to connect to is stored in
precomputed format so try using that first.

Yes, igneous image xfer is the way to go.

Will

**Comment by JackieZhai** [comment]
Thanks for your advice!

I successfully downloaded a part of "Minnie" in `precomputed` format.

Happy holidays!
Jackie
