### ISSUE TITLE
Incompatible with python 3.12

### ISSUE THREAD

**Issue by clbarnes** [seung-lab/cloud-volume#606]
Some dependencies cannot be installed on python 3.12, mainly because those packages do not list their build-time dependencies. Listing here as I hit them:

- [x] compresso
    - fixed by https://github.com/seung-lab/compresso/commit/97d2462d91d5a01e6c50f8e90ec5027169d0f1a4 
- [x] dracopy
    - pinned to <v2, which doesn't include a pyproject.toml and so does not specify that it needs `skbuild`
- [x] pysimdjson

**Comment by william-silversmith** [comment]
Hmm, for compresso it seems that I have released wheels. I think you meant that this is fixed by the checkmark? 

Yes, DracoPy needs a new release. Thanks for reminding me.

**Comment by clbarnes** [comment]
Yes, compresso's fixed, thanks for doing that!

**Comment by clbarnes** [comment]
Unfortunately pysimdjson won't install either!

**Comment by william-silversmith** [comment]
It looks like there's a PR for that with a workaround while it waits to be merged: https://github.com/TkTech/pysimdjson/pull/113

I think I need to overhaul the CloudVolume tests. They've only been able to be run locally for a while.

**Comment by clbarnes** [comment]
By [these benchmarks](https://python-rapidjson.readthedocs.io/en/latest/benchmarks.html#serialization), orjson beats pysimdjson by some margin, has wheels up to and including 3.12, and if the wheels don't exist, the build story is "have a rust compiler released in the last year" rather than the nightmare that building C++ packages from source often is.

I can put together a github actions workflow if that would be helpful.

**Comment by william-silversmith** [comment]
We use both orjson and pysimdjson unfortunately... We use orjson for decoding JSON rapidly as a whole, but pysimdjson has special methods for partial decoding that are necessary for managing very large and numerous json files. This is necessary for processing the spatial index, which we use for creating sharded mesh and skeleton types. It saves hours or days of computation.

**Comment by william-silversmith** [comment]
It's also worth noting that the encoder/decoder amounts to about 5% of the compute time. Most of the time is spent marshaling the decoded objects into python objects in my experience.

**Comment by william-silversmith** [comment]
I posted asking the maintainer of pysimdjson to update their repo. In the meantime, there may be a workaround. I haven't quite gotten this to work yet, but looking at the setup.py file, it seems that if you have cython installed and set `BUILD_WITH_CYTHON=1` in your environment, you can force recythonization (which should fix the issue if your cython is up-to-date).

https://github.com/TkTech/pysimdjson/blob/master/setup.py#L32

**Comment by william-silversmith** [comment]
Looks like py3.12 wheels are available for pysimdjson. https://pypi.org/project/pysimdjson/#files

**Comment by william-silversmith** [comment]
Afaik, this problem is solved.
