### ISSUE TITLE
Installing cloudvolume from an environment fails because of greenlet

### ISSUE THREAD

**Issue by jboulanger91** [seung-lab/cloud-volume#608]
Hi all, 

I'm trying to install cloudvolume from an env. file and greenlet gives me the following error: 
`Building wheel for greenlet (pyproject.toml) did not run successfully.`
Has anyone face the same issue? 

I am on MacOS14.3 and Python3.10.11
Thanks a lot for your help, 
J

**Comment by william-silversmith** [comment]
Hi J,

This is a little odd, it looks like there should be a wheel available for greenlet: greenlet-3.0.3-cp310-cp310-macosx_11_0_universal2.whl 

https://pypi.org/project/greenlet/#files

What version of greenlet was attempted to be installed?

Will

**Comment by jboulanger91** [comment]
I used Python 3.10.13 in my env. and it fixed it. 
Thanks for having a look.
