### ISSUE TITLE
"graphene://middleauth+https://" protocol in a cloudpath does not work

### ISSUE THREAD

**Issue by ceesem** [seung-lab/cloud-volume#610]
As part of the development of graphene integration in Neuroglancer, the auth protocol is provided to neuroglancer as an additional scheme: `graphene://middleauth+https://` instead of just `graphene://https://`. Currently, however that gives the error:

```UnsupportedProtocolError: 
Cloud Path must conform to [FORMAT://PROTOCOL://BUCKET/PATH](format://PROTOCOL//BUCKET/PATH)
```

For convenience in coming to cloudvolume from neuroglancer, it would be nice if this multi-scheme URL were acceptable and treated as equivalent to `graphene://https://`.

**Comment by william-silversmith** [comment]
Not a bad idea. Are there any other `+` types? Should I just selectively delete `middleauth+` or be more generic?

**Comment by chrisj** [comment]
ngauth possibly

https://github.com/google/neuroglancer/blob/145ce39e54bfaaa6fbf106d46c5f5bf613c04155/src/util/special_protocol_request.ts#L76

**Comment by ceesem** [comment]
I wouldn't delete the `middleauth+` per se, but rather treat it as an explicit indication to use the CAVE token header. We actually have one case where we have imagery that's behind authentication, and the Neuroglancer cloudpath is `precomputed://middleauth+https://`. It would actually be perfect if that that indicated how to add the correct header information.

**Comment by william-silversmith** [comment]
Can you share that image case with me? I would like to see if I can get it to work.

**Comment by ceesem** [comment]
This remains an issue, since Neuroglancer requires this auth formatting for its data sources and cloud-volume does not know how to interpret it.

We also now have a neuroglancer skeleton source deployed on datastack `minnie65_phase3_v1` that should be compatible with cloudvolume whose endpoint is `precomputed://middleauth+https://minnie.microns-daf.com/skeletoncache/api/v1/minnie65_phase3_v1/precomputed/skeleton/`, but again cloudvolume does not know how to read the format required by Neuroglancer.

**Comment by william-silversmith** [comment]
First step maybe complete. I think I have `middleauth+https` working in CloudFiles.

https://github.com/seung-lab/cloud-files/pull/106

**Comment by william-silversmith** [comment]
This is released in 10.2.0!

**Comment by ceesem** [comment]
In cloudvolume 11.0.2, the `middleauth+` paths are not working with the same error described above.

Two example cloudpaths that should work to create cloudvolume objects using CAVE tokens are:
* `precomputed://middleauth+https://minnie.microns-daf.com/skeletoncache/api/v1/minnie65_phase3_v1/precomputed`
* `graphene://middleauth+https://minnie.microns-daf.com/segmentation/table/minnie3_v1`

Note that the first case of this is a skeleton source serving precomputed skeletons but requires a CAVE token in the header.

However, both throw an `UnsupportedProtocolError`:
```
Cloud Path must conform to FORMAT://PROTOCOL://BUCKET/PATH
Examples:
  precomputed://gs://test_bucket/em
  gs://test_bucket/em
  graphene://https://example.com/image/em

Supported Formats: None (precomputed), graphene, precomputed, boss, n5, zarr, zarr2, zarr3
Supported Protocols: gs, file, s3, http, https, mem, matrix, tigerdata
```

**Comment by william-silversmith** [comment]
Hi Casey, I just ran those two paths on my machine and didn't see an error. Is your cloud-files version up-to-date? That could be the issue.

**Comment by ceesem** [comment]
Ah, you're right, thank you! My cloudvolume was up to date, but the cloud-files install was at 4.26.0. Upgrading cloud-files to 4.28.0 fixed that.

Unless there's a good reason not to, I feel like you should bump the minimum version of cloud-files from 4.24.0 up to whenever this feature was added, since it is a cloud-volume feature as much as a cloud-files one and the fix was not obvious.

**Comment by william-silversmith** [comment]
This is now released!
