### ISSUE TITLE
Graphene: how to view agglomerated supervoxels

### ISSUE THREAD

**Issue by jakobtroidl** [seung-lab/cloud-volume#611]
I am trying to download segmentation data using CloudVolume from a graphene segmentation. Here's my code + here's a small colab for easy reproducibility. 

```python
from cloudvolume import view
import navis.interfaces.microns as mi

client = mi.get_cave_client(datastack='cortex65')
cv = client.info.segmentation_cloudvolume()  
img = cv.download_point((122527, 95771, 21354), mip=0, size=(512, 512, 64))
print(img.min(), img.max())

view(img, segmentation=True)
```

The result shows each supervoxel individual. How can I view the "agglomerated" segmentation for a graphene based dataset using cloud-volume? 
![Screenshot 2024-04-15 at 2 18 24 PM](https://github.com/seung-lab/cloud-volume/assets/29884213/2a3998b0-efd3-4bc3-9335-82b420575166)

**Comment by william-silversmith** [comment]
Hi Jakob, 

Easy! Just add `agglomerate=True` to `download_point`. You can also add `timestamp=UNIXTIME` where UNIXTIME is a number in seconds if you'd like to select a particular timepoint for the proofread segmentation.

Will

**Comment by jakobtroidl** [comment]
Mega, that's indeed an easy fix! Thanks a bunch for your swift response!
