### ISSUE TITLE
`TypeError` in `download` method of `cloudvolume` when `mip` is `None`

### ISSUE THREAD

**Issue by torms3** [seung-lab/cloud-volume#621]
**Description**:
I encountered a `TypeError` while running a task in our custom Airflow setup. The error occurs when trying to download an image using the `cloudvolume` library. It appears that the `mip` value is `None`, causing an issue when accessing the `resolution` attribute from the scales list.

**Error Traceback**:
```
Traceback (most recent call last):
File "/usr/local/airflow/custom/task_execution.py", line 156, in handle_task
val = custom_worker.process_task(msg['task'])
File "/usr/local/airflow/custom/custom_worker.py", line 9, in process_task
task.execute()
File "/opt/conda/lib/python3.10/site-packages/taskqueue/queueablefns.py", line 78, in execute
self(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/taskqueue/queueablefns.py", line 87, in call
return self.tofunc()()
File "/opt/conda/lib/python3.10/site-packages/igneous/tasks/image/image.py", line 481, in DownsampleTask
return TransferTask(
File "/opt/conda/lib/python3.10/site-packages/igneous/tasks/image/image.py", line 446, in TransferTask
image = src_cv.download(
File "/opt/conda/lib/python3.10/site-packages/cloudvolume/frontends/precomputed.py", line 750, in download
bbox = bbox.convert_units('vx', self.meta.resolution(mip))
File "/opt/conda/lib/python3.10/site-packages/cloudvolume/datasource/precomputed/metadata.py", line 605, in resolution
res = self.info['scales'][mip]['resolution']
TypeError: list indices must be integers or slices, not NoneType
```

**Steps to Reproduce**:
1. Execute the task `DownsampleTask` within our custom Airflow setup.
2. Observe the error traceback as the task attempts to download an image using `cloudvolume`.

**Expected Behavior**:
The `mip` value should be correctly determined and passed to the `resolution` method, preventing the `TypeError`.

**Actual Behavior**:
The `mip` value is `None`, leading to a `TypeError` when trying to access the `resolution` attribute from the scales list.

**Possible Solution**:
Ensure that the `mip` value is correctly set before it is used to access the scales list. Add validation or default values to handle cases where `mip` might be `None`.

**Code Snippet**:
The error occurs in the following method:
```python
def download(
    self, 
    bbox: BboxLikeType, 
    mip: Optional[int] = None, 
    parallel: Optional[int] = None,
    segids: Optional[Sequence[int]] = None, 
    preserve_zeros: bool = False,
    agglomerate: Optional[bool] = None, 
    timestamp: Optional[int] = None, 
    stop_layer: Optional[int] = None,
    renumber: bool = False, 
    coord_resolution: Optional[Sequence[int]] = None,
    label: Optional[int] = None,
) -> VolumeCutout:
    """
    Downloads segmentation from the indicated cutout region.
    """
    if isinstance(bbox, Bbox):
      bbox = bbox.convert_units('vx', self.meta.resolution(mip))
```

A similar method that handles the mip value correctly:

```python
def download_files(
    self,
    bbox: BboxLikeType, 
    mip: Optional[int] = None, 
    parallel: Optional[int] = None,
    segids: Optional[Sequence[int]] = None, 
    agglomerate: Optional[bool] = None, 
    timestamp: Optional[int] = None, 
    stop_layer: Optional[int] = None,
    coord_resolution: Optional[Sequence[int]] = None,
    cache_only: bool = False,
    decompress: bool = True,
):
    """
    Downloads files without rendering to an image.
    """
    if mip is None:
      mip = self.mip

    if isinstance(bbox, Bbox):
      bbox = bbox.convert_units('vx', self.meta.resolution(mip))
```

**Commit information**:
The change was introduced in [commit 60bf99f](https://github.com/seung-lab/cloud-volume/commit/60bf99fab9785cc06a17a69e4c1a34b6f3e15c50).

**Note**:
This issue report was generated by ChatGPT 4o based on the error traceback and code snippets provided by the user. If any additional information or context is needed, please feel free to ask.

**Comment by william-silversmith** [comment]
This is fixed in the most recent release. Thanks for reporting! By the way, ChatGPT did get the right commit, but the wrong function.
