### ISSUE TITLE
simple_merge on empty Skeletons fails

### ISSUE THREAD

**Issue by jasonkena** [seung-lab/cloud-volume#627]
![image](https://github.com/user-attachments/assets/49db79f0-5297-4394-b969-d26f6c7268f1)

Attempting to merge skeletons raises errors if some of them are empty, due to the vertex_attributes being missing. Not sure if this should be handled in cloud-volume or igneous, or if this is expected behavior and I should filter out the non-empty skels before merging.

**Comment by william-silversmith** [comment]
I should probably add some empty filtration in there.

**Comment by william-silversmith** [comment]
This was released on Friday.
