### ISSUE TITLE
Support `background_color=np.nan`

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/cloud-volume#641]
I have a `float32` CloudVolume that potentially contains `0.0` as legitimate data, and `np.nan` to indicate missing data. The cutouts might partially lie outside the dataset volume and the exterior is considered to be `np.nan`.

Currently, downloading a cutout using `CloudVolume(..., bounded=False, background_color=np.nan)` fails due to the forced integer conversions, e.g. here: https://github.com/seung-lab/cloud-volume/blob/3f281e84bde6818b78e7d2f1dd99b7b40c216904/cloudvolume/datasource/precomputed/image/__init__.py#L207

Would it be possible to just remove the conversion and allow any types of float, including `nan` and `inf`?

**Comment by william-silversmith** [comment]
Sure, I don't see why not.

**Comment by william-silversmith** [comment]
This is released in 11.0.2
