### ISSUE TITLE
Compute Normals for Meshes

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/cloud-volume#65]
Sven was trying to decide if something was inside or outside a mesh, and so wanted normals for the meshes. We should have an option to convert faces into normals in vol.mesh.get to make that kind of task easier. Not totally sure what format we'd return. Triangle, normal? Seems wasteful in terms of vertex representation.

**Comment by nkemnitz** [comment]
You are returning meshes as obj file? I don't think you have much choice then, other than returning the _vertex_ normals with the supported `vn` keyword. (And changing the faces to `f v1//vn1 v2//vn2 v3//vn3` ...)

**Comment by william-silversmith** [comment]
We changed cloudvolume to have an obj generator (vol.mesh.save) and a
programmatic accessor (vol.mesh.get). This issue concerns the latter.

**Comment by william-silversmith** [comment]
This is somewhat covered in https://github.com/seung-lab/zmesh

**Comment by william-silversmith** [comment]
This is now totally covered in zmesh.
