### ISSUE TITLE
Check if chunks exist

### ISSUE THREAD

**Issue by macrintr** [seung-lab/cloud-volume#8]
Is there a function written to test if a chunk exists within CloudVolume storage? Could be extended to take a range and return a Bool whether all the chunks that overlap with that range are present.

**Comment by william-silversmith** [comment]
That's an interesting idea! Can you describe the use case a little more?

**Comment by macrintr** [comment]
Here's the scenario I was thinking of:
My single-instance ingest process goes down, but it's not clear at what point (I don't have a queue notifying me of a completed upload). I have an idea of the last stretch of uploads that completed, though, so I restart my ingest at that point. To save time, I use the `exists` method to check if a chunk is present in the remote storage so I only upload the chunks that have not been ingested.

Possibly a low priority feature, because these "boutique" single-instance ingests will be rare.

**Comment by william-silversmith** [comment]
I think for this lab single instance ingests will be rare, but if other people start using CloudVolume to read neuroglancer precomputed, it might not be.

**Comment by william-silversmith** [comment]
Here's two forms of the operator, which one do you like (or suggest one)?

# Calling Exists

## Modal
```
vol = CloudVolume(....)
vol.exists = True
results = vol[ .... ] 
vol.exists = False
# results is now read normally
```

## Function Variant 1
```
results = vol.exists(x_slice, y_slice, z_slice)
```

## Function Variant 2
```
results = vol.exists( np.s_[xslc, yslc, zslc]  ) 
results = vol.exists( (xslice, yslice, zslice) )
```

# Results
Here are a few possibilities for what results can look like:

Per file report (filenames are precomputed chunks):
```
{ filename: True, filename2: False }
```
Per region report (Bbox is a Bbox object instance):
```
{
   True: [ Bbox1, Bbox2, ... ],
   False: [ Bbox3, Bbox4, ... ]
}
```

**Comment by william-silversmith** [comment]
I think I might be partial to Variant 2 + per file report.

**Comment by william-silversmith** [comment]
From slack, Tommy also likes Variant 2 + per file report.
