### ISSUE TITLE
limited cache size

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/cloud-volume#82]
local storage size is limited, can we limit the cache size? 
You can create a FIFO queue, when the total size is over a threshold, delete some cache chunks.

I also need a function to delete specific cached chunk.

**Comment by william-silversmith** [comment]
This is a good idea, I wonder though about some of the start-up performance implications. For instance, say you start a new CloudVolume instance. You need to scan through the cache to sort all files by last modified or created dates. For large caches, this can become burdensome. 

Alternatively, you can establish a weaker form of cache resource limits on a per instance basis which would be more performant, but solves fewer problems. 

What do you think?

**Comment by william-silversmith** [comment]
The other question that's less immediately urgent is do we limit total cache or per dataset cache? Total cache can cause unrelated processes to slow down the current one.

**Comment by william-silversmith** [comment]
Talked with @jingpengw and he had a really interesting idea. We could implement 
1. Deletion of a bbox
2. Preservation of a bbox
3. LRU cache
and the most interesting option
4. Prioritize deletion of data far from a point so he can use Z-ordering.

**Comment by william-silversmith** [comment]
Thinking about this some more, the most basic implementation of (4) is to define a point and radius and delete everything outside this radius. This version is nearly identical to "preserve" except that it's spherical rather than boxy. 

The distance version becomes more sophisticated when it's combined with a max cache size as then it can be used to prioritize the deletions.

**Comment by william-silversmith** [comment]
Previously, 1 and 2 were implemented in #86

**Comment by jingpengw** [comment]
since Will W. is not working on new version of chunkflow, we do not need this for now. will close here.
