### ISSUE TITLE
what does 'block' mean?

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/cloud-volume#85]
@william-silversmith  in put_files function, what does the `block` parameter mean?
does it mean wait until all the uploading was finished? 

https://github.com/seung-lab/cloud-volume/blob/master/cloudvolume/storage.py#L260

**Comment by william-silversmith** [comment]
Yes, that's exactly what it means. I probably should have factored it better... that option isn't really intended for use by others.

**Comment by jingpengw** [comment]
tks. `block` is a little bit misleading. block also means aligned image chunk.
